# ifndef AROS_PREPROCESSOR_VARIADIC_FIRST_HPP
# define AROS_PREPROCESSOR_VARIADIC_FIRST_HPP
#
# define AROS_PP_VARIADIC_FIRST(...) AROS_PP_VARIADIC_FIRST_I(__VA_ARGS__)
#
# define AROS_PP_VARIADIC_FIRST_I(a, ...) a
#
# endif
