# ifndef AROS_PREPROCESSOR_VARIADIC_REST_HPP
# define AROS_PREPROCESSOR_VARIADIC_REST_HPP
#
# define AROS_PP_VARIADIC_REST(...) AROS_PP_VARIADIC_REST_I(__VA_ARGS__)
#
# define AROS_PP_VARIADIC_REST_I(a, ...) __VA_ARGS__
#
# endif 