
#ifndef VIRTIO_BASE
#define VIRTIO_BASE         0x20000000
#endif

#define IRQ_ENBL1 (VIRTIO_BASE + 0xb210) /* bank 1 enable bits */
#define IRQ_ENBL2 (VIRTIO_BASE + 0xb214) /* bank 2 enable bits */
#define IRQ_ENBL3 (VIRTIO_BASE + 0xb218) /* bank 3 enable bits */
#define IRQ_DIBL1 (VIRTIO_BASE + 0xb21C) /* bank 1 disable bits */
#define IRQ_DIBL2 (VIRTIO_BASE + 0xb220) /* bank 2 disable bits */
#define IRQ_DIBL3 (VIRTIO_BASE + 0xb224) /* bank 3 disable bits */

#define IRQ0_BASE               0
#define IRQ_ARM_TIMER           (IRQ0_BASE + 0)
#define IRQ_ARM_MAILBOX         (IRQ0_BASE + 1)
#define IRQ_ARM_DOORBELL_0      (IRQ0_BASE + 2)
#define IRQ_ARM_DOORBELL_1      (IRQ0_BASE + 3)
#define IRQ_VPU0_HALTED         (IRQ0_BASE + 4)
#define IRQ_VPU1_HALTED         (IRQ0_BASE + 5)
#define IRQ_ILLEGAL_TYPE0       (IRQ0_BASE + 6)
#define IRQ_ILLEGAL_TYPE1       (IRQ0_BASE + 7)
#define IRQ_PENDING1            (IRQ0_BASE + 8)
#define IRQ_PENDING2            (IRQ0_BASE + 9)
#define IRQ_JPEG                (IRQ0_BASE + 10)
#define IRQ_USB                 (IRQ0_BASE + 11)
#define IRQ_3D                  (IRQ0_BASE + 12)
#define IRQ_DMA2                (IRQ0_BASE + 13)
#define IRQ_DMA3                (IRQ0_BASE + 14)
#define IRQ_I2C                 (IRQ0_BASE + 15)
#define IRQ_SPI                 (IRQ0_BASE + 16)
#define IRQ_I2SPCM              (IRQ0_BASE + 17)
#define IRQ_SDIO                (IRQ0_BASE + 18)
#define IRQ_UART0               (IRQ0_BASE + 19)
#define IRQ_ARASANSDIO          (IRQ0_BASE + 20)

#define IRQ1_BASE               32
#define IRQ_TIMER0              (IRQ1_BASE + 0)
#define IRQ_TIMER1              (IRQ1_BASE + 1)
#define IRQ_TIMER2              (IRQ1_BASE + 2)
#define IRQ_TIMER3              (IRQ1_BASE + 3)
#define IRQ_CODEC0              (IRQ1_BASE + 4)
#define IRQ_CODEC1              (IRQ1_BASE + 5)
#define IRQ_CODEC2              (IRQ1_BASE + 6)
#define IRQ_VC_JPEG             (IRQ1_BASE + 7)
#define IRQ_ISP                 (IRQ1_BASE + 8)
#define IRQ_VC_USB              (IRQ1_BASE + 9)
#define IRQ_VC_3D               (IRQ1_BASE + 10)
#define IRQ_TRANSPOSER          (IRQ1_BASE + 11)
#define IRQ_MULTICORESYNC0      (IRQ1_BASE + 12)
#define IRQ_MULTICORESYNC1      (IRQ1_BASE + 13)
#define IRQ_MULTICORESYNC2      (IRQ1_BASE + 14)
#define IRQ_MULTICORESYNC3      (IRQ1_BASE + 15)
#define IRQ_DMA0                (IRQ1_BASE + 16)
#define IRQ_DMA1                (IRQ1_BASE + 17)
#define IRQ_VC_DMA2             (IRQ1_BASE + 18)
#define IRQ_VC_DMA3             (IRQ1_BASE + 19)
#define IRQ_DMA4                (IRQ1_BASE + 20)
#define IRQ_DMA5                (IRQ1_BASE + 21)
#define IRQ_DMA6                (IRQ1_BASE + 22)
#define IRQ_DMA7                (IRQ1_BASE + 23)
#define IRQ_DMA8                (IRQ1_BASE + 24)
#define IRQ_DMA9                (IRQ1_BASE + 25)
#define IRQ_DMA10               (IRQ1_BASE + 26)
#define IRQ_DMA11               (IRQ1_BASE + 27)
#define IRQ_DMA12               (IRQ1_BASE + 28)
#define IRQ_AUX                 (IRQ1_BASE + 29)
#define IRQ_ARM                 (IRQ1_BASE + 30)
#define IRQ_VPUDMA              (IRQ1_BASE + 31)

#define IRQ2_BASE               64
#define IRQ_HOSTPORT            (IRQ2_BASE + 0)
#define IRQ_VIDEOSCALER         (IRQ2_BASE + 1)
#define IRQ_CCP2TX              (IRQ2_BASE + 2)
#define IRQ_SDC                 (IRQ2_BASE + 3)
#define IRQ_DSI0                (IRQ2_BASE + 4)
#define IRQ_AVE                 (IRQ2_BASE + 5)
#define IRQ_CAM0                (IRQ2_BASE + 6)
#define IRQ_CAM1                (IRQ2_BASE + 7)
#define IRQ_HDMI0               (IRQ2_BASE + 8)
#define IRQ_HDMI1               (IRQ2_BASE + 9)
#define IRQ_PIXELVALVE1         (IRQ2_BASE + 10)
#define IRQ_I2CSPISLV           (IRQ2_BASE + 11)
#define IRQ_DSI1                (IRQ2_BASE + 12)
#define IRQ_PWA0                (IRQ2_BASE + 13)
#define IRQ_PWA1                (IRQ2_BASE + 14)
#define IRQ_CPR                 (IRQ2_BASE + 15)
#define IRQ_SMI                 (IRQ2_BASE + 16)
#define IRQ_GPIO0               (IRQ2_BASE + 17)
#define IRQ_GPIO1               (IRQ2_BASE + 18)
#define IRQ_GPIO2               (IRQ2_BASE + 19)
#define IRQ_GPIO3               (IRQ2_BASE + 20)
#define IRQ_VC_I2C              (IRQ2_BASE + 21)
#define IRQ_VC_SPI              (IRQ2_BASE + 22)
#define IRQ_VC_I2SPCM           (IRQ2_BASE + 23)
#define IRQ_VC_SDIO             (IRQ2_BASE + 24)
#define IRQ_VC_UART             (IRQ2_BASE + 25)
#define IRQ_SLIMBUS             (IRQ2_BASE + 26)
#define IRQ_VEC                 (IRQ2_BASE + 27)
#define IRQ_CPG                 (IRQ2_BASE + 28)
#define IRQ_RNG                 (IRQ2_BASE + 29)
#define IRQ_VC_ARASANSDIO       (IRQ2_BASE + 30)
#define IRQ_AVSPMON             (IRQ2_BASE + 31)
