# $Id$
TOP=..
CURDIR=rom

include $(TOP)/config/make.cfg

ifeq ($(FLAVOUR),native)
SUBDIRS=aros exec utility alerthook
else
SUBDIRS= aros exec utility dos graphics intuition devs mathffp mathieeesingbas
endif

all:
	%subdirs_q target=all

clean::
	%subdirs_q "Cleaning" clean

setup:
	@true

%common
