##begin config
basename DrawList
version 44.1
classid "drawlist.image"
classdatatype struct DrawListData
##end config
##begin cdef
#include <intuition/imageclass.h>
#include <images/drawlist.h>
##end cdef
##begin cdefprivate
#include "drawlist_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
IM_DRAW
##end methodlist
