##begin config
basename Requester
version 44.1
classid "requester.class"
classdatatype struct RequesterData
##end config
##begin cdef
#include <classes/requester.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
##end cdef
##begin cdefprivate
#include "requester_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
RM_OPENREQ
##end methodlist
