##begin config
version 0.1
residentpri 87
libbase SDIOBase
libbasetype struct SDIOBase
##end config
##begin cdef
#include <inttypes.h>
#include <exec/tasks.h>
##end cdef
##begin cdefprivate
#include "sdio_private.h"
##end cdefprivate
##begin functionlist
int SDIOProbe() ()
uint8_t SDIOReadByte(uint32_t func, uint32_t addr) (D0, D1)
void SDIOWriteByte(uint32_t func, uint32_t addr, uint8_t val) (D0, D1, D2)
int SDIOReadExt(uint32_t func, uint32_t addr, void * buf, uint32_t len, uint32_t incr) (D0, D1, D2, D3, D4)
int SDIOWriteExt(uint32_t func, uint32_t addr, void * buf, uint32_t len, uint32_t incr) (D0, D1, D2, D3, D4)
int SDIOEnableFunction(uint32_t func) (D0)
int SDIOSetBlockSize(uint32_t func, uint32_t size) (D0, D1)
int SDIOIsPresent() ()
int SDIOSetInterrupt(struct Task * task, uint32_t sigmask) (A0, D0)
void SDIOAckInterrupt() ()
##end functionlist
