# $Id$
TOP=../../..
COMPILE_KERNEL = yes # Must have a value, no matter which one

USER_INCLUDES = -I/usr/include

include $(TOP)/config/make.cfg

OBJDIR=$(GENDIR)/filesys

all: setup $(OBJDIR)/emul_handler.o

setup:
	%mkdirs_q $(OBJDIR)

clean::
	-$(RM) $(OBJDIR)

$(OBJDIR)/%.o: %.c
	%compile_q

$(OBJDIR)/%.d: %.c
	%mkdepend_q

%common
%include_deps $(OBJDIR)/emul_handler.d
