##begin config
version 41.1
residentpri 69
libbase BattMemBase
libbasetype struct BattMemBase
libbasetypeextern struct Library
options resautoinit, noautolib
##end config

##begin cdef
#include <resources/battmem.h>
##end cdef

##begin cdefprivate
#include <resources/battmem.h>
#include <battmem_intern.h>
##end cdefprivate

##begin functionlist
void ObtainBattSemaphore() ()
void ReleaseBattSemaphore() ()
ULONG ReadBattMem(APTR buffer, ULONG offset, ULONG length) (A0, D0, D1)
ULONG WriteBattMem(CONST_APTR buffer, ULONG offset, ULONG length) (A0, D0, D1)
##end functionlist
