##begin config
version 0.1
libbasetype struct NetPrefsIPv6Base
residentpri 0
##end config
##begin cdef
#include "ipv6_intern.h"
##end cdef
##begin cdefprivate
##end cdefprivate
##begin functionlist
void ModuleInit(struct NetPrefsBase *NetPrefsBase) (A0)
##end functionlist
