##begin config
basename	EFIFBGfx
libbasetype	struct EFIFBGfxBase
version		45.1
residentpri     9
classptr_field  vsd.efifbgfxclass
classdatatype	struct EFIFBGfxHiddData
classid         CLID_Hidd_Gfx_EFIFB
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "efifbgfx_intern.h"
#include "efifbgfx_hidd.h"
#include "efifbgfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist


##begin class
##begin config
basename EFIFBGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_EFIFB
superclass CLID_Hidd_Display
classdatatype struct EFIFBGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
Show
##end methodlist
##end class


##begin class
##begin config
basename EFIFBGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_EFIFB
superclass CLID_Hidd_ChunkyBM
classdatatype struct EFIFBGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
UpdateRect
##end methodlist
##end class
