##begin config
version 0.1
libbasetype struct NetPrefsEFSBase
residentpri 0
##end config
##begin cdef
#include "envoyfs_intern.h"
##end cdef
##begin cdefprivate
##end cdefprivate
##begin functionlist
void ModuleInit(struct NetPrefsBase *NetPrefsBase) (A0)
##end functionlist
