##begin config
version 41.1
libbase GPBase
libbasetype struct GameportBase
residentpri 44
options noexpunge
beginio_func beginio
abortio_func abortio
##end config
##begin cdefprivate
#include <exec/io.h>
#include "gameport_intern.h"
##end cdefprivate
