/*

Copyright (C) 2005 Neil Cafferkey

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.

*/

#ifndef INTELPRO100_H
#define INTELPRO100_H


/* General */
/* ======= */

#define PRO_FRAGLEN     2


/* Registers */
/* ========= */

#define PROREG_STATUS          0
#define PROREG_INTSTATUS       1
#define PROREG_COMMAND         2
#define PROREG_GENPTR          4
#define PROREG_PORT            8
#define PROREG_EEPROM         14
#define PROREG_MIICONTROL     16
#define PROREG_RXDMABYTECOUNT 20
#define PROREG_FC             25
#define PROREG_PMDR           27
#define PROREG_GENCTRL        28
#define PROREG_GENSTATUS      30


/* EEPROM Data Offsets */
/* =================== */

#define PROROM_ADDRESS0 0
#define PROROM_ADDRESS1 1
#define PROROM_ADDRESS2 2
#define PROROM_PHYINFO0 6
#define PROROM_PHYINFO1 7


/* Interrupt Types */
/* =============== */

#define PROINTB_GENERAL    7
#define PROINTB_RXDONE     6
#define PROINTB_CUINACTIVE 5
#define PROINTB_RXINACTIVE 4
#define PROINTB_MDI        3
#define PROINTB_REQINT     2
#define PROINTB_FCPAUSE    0

#define PROINTF_GENERAL    (1 << PROINTB_GENERAL)
#define PROINTF_RXDONE     (1 << PROINTB_RXDONE)
#define PROINTF_CUINACTIVE (1 << PROINTB_CUINACTIVE)
#define PROINTF_RXINACTIVE (1 << PROINTB_RXINACTIVE)
#define PROINTF_MDI        (1 << PROINTB_MDI)
#define PROINTF_REQINT     (1 << PROINTB_REQINT)
#define PROINTF_FCPAUSE    (1 << PROINTB_FCPAUSE)


/* Register Details */
/* ================ */

/* SCB Status Register */

#define PROREG_STATUSB_CUSTATE 6
#define PROREG_STATUSB_RUSTATE 2

#define PROREG_STATUSF_CUSTATE (0x3 << PROREG_STATUSB_CUSTATE)
#define PROREG_STATUSF_RUSTATE (0xf << PROREG_STATUSB_RUSTATE)

#define PRO_CUSTATE_IDLE      0
#define PRO_CUSTATE_SUSPENDED 1
#define PRO_CUSTATE_LPQACTIVE 2
#define PRO_CUSTATE_HQPACTIVE 3

#define PRO_RUSTATE_IDLE        0
#define PRO_RUSTATE_SUSPENDED   1
#define PRO_RUSTATE_NORESOURCES 2
#define PRO_RUSTATE_READY       4

/* SCB Command Register */

#define PROREG_COMMANDB_CUCMD 4
#define PROREG_COMMANDB_RUCMD 0

#define PROREG_COMMANDF_CUCMD (0xf << PROREG_COMMANDB_CUCMD)
#define PROREG_COMMANDF_RUCMD (0x7 << PROREG_COMMANDB_RUCMD)

/* EEPROM Command Register */

#define PROREG_EEPROMB_DATAIN  3
#define PROREG_EEPROMB_DATAOUT 2
#define PROREG_EEPROMB_SELECT  1
#define PROREG_EEPROMB_CLK     0

#define PROREG_EEPROMF_DATAIN  (1 << PROREG_EEPROMB_DATAIN)
#define PROREG_EEPROMF_DATAOUT (1 << PROREG_EEPROMB_DATAOUT)
#define PROREG_EEPROMF_SELECT  (1 << PROREG_EEPROMB_SELECT)
#define PROREG_EEPROMF_CLK     (1 << PROREG_EEPROMB_CLK)

#define PRO_CUCMD_NOP             (0 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_START           (1 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_RESUME          (2 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_SETSTATSBUFFER  (4 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_DUMPSTATS       (5 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_SETBASE         (6 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_DUMPRESETSTATS  (7 << PROREG_COMMANDB_CUCMD)
#define PRO_CUCMD_STATICRESUME   (10 << PROREG_COMMANDB_CUCMD)

#define PRO_RUCMD_NOP           0
#define PRO_RUCMD_START         1
#define PRO_RUCMD_RESUME        2
#define PRO_RUCMD_RXDMAREDIRECT 3
#define PRO_RUCMD_ABORT         4
#define PRO_RUCMD_SETHEADERSIZE 5
#define PRO_RUCMD_SETBASE       6

/* MII Control Register */

#define PROREG_MIICONTROLB_INT   29
#define PROREG_MIICONTROLB_READY 28
#define PROREG_MIICONTROLB_CMD   26
#define PROREG_MIICONTROLB_PHYNO 21
#define PROREG_MIICONTROLB_REGNO 16
#define PROREG_MIICONTROLB_DATA   0

#define PROREG_MIICONTROLF_INT   (1 << PROREG_MIICONTROLB_INT)
#define PROREG_MIICONTROLF_READY (1 << PROREG_MIICONTROLB_READY)
#define PROREG_MIICONTROLF_CMD   (0x3 << PROREG_MIICONTROLB_CMD)
#define PROREG_MIICONTROLF_PHYNO (0x1f << PROREG_MIICONTROLB_PHYNO)
#define PROREG_MIICONTROLF_REGNO (0x1f << PROREG_MIICONTROLB_REGNO)
#define PROREG_MIICONTROLF_DATA  (0xffff << PROREG_MIICONTROLB_DATA)


/* EEPROM Field Details */
/* ==================== */

/* PHY Information 0 */

#define PROROM_PHYINFO0B_AUI 15
#define PROROM_PHYINFO0B_TYPE 8
#define PROROM_PHYINFO0B_ADDR 0

#define PROROM_PHYINFO0F_AUI     (1 << PROROM_PHYINFO0B_AUI)
#define PROROM_PHYINFO0F_TYPE  (0xf << PROROM_PHYINFO0B_TYPE)
#define PROROM_PHYINFO0F_ADDR (0x1f << PROROM_PHYINFO0B_ADDR)

#define PRO_PHY_DP83840   (4 << PROROM_PHYINFO0B_TYPE)
#define PRO_PHY_DP83840A (10 << PROROM_PHYINFO0B_TYPE)


/* Action Commands */
/* =============== */

#define PROACT_NOP        (0 << PROCB_CONTROLB_ACTION)
#define PROACT_SETADDRESS (1 << PROCB_CONTROLB_ACTION)
#define PROACT_CONFIGURE  (2 << PROCB_CONTROLB_ACTION)
#define PROACT_SETMCAST   (3 << PROCB_CONTROLB_ACTION)
#define PROACT_TX         (4 << PROCB_CONTROLB_ACTION)
#define PROACT_LOADCODE   (5 << PROCB_CONTROLB_ACTION)
#define PROACT_DUMP       (6 << PROCB_CONTROLB_ACTION)
#define PROACT_DIAGNOSE   (7 << PROCB_CONTROLB_ACTION)


/* Control Block Fields */
/* ==================== */

#define PROCB_CONTROL   0
#define PROCB_NEXT      1
#define PROCB_COUNT     2
#define PROCB_FRAGMENTS 2
#define PROCB_ADDRESS   2
#define PROCB_TXINFO    3
#define PROCB_RXINFO    3
#define PROCB_BUFFER    4
#define PROCB_EXTBUFFER 8
#define PROCB_EXTFRAGS  4
#define PROCB_CF0       2
#define PROCB_CF1       3
#define PROCB_CF2       4
#define PROCB_CF3       5
#define PROCB_CF4       6
#define PROCB_CF5       7

/* TX Fragments */

#define PROFRAG_ADDR 0
#define PROFRAG_LEN  1

#define PROFRAG_LENB_LAST 16

#define PROFRAG_LENF_LAST (1 << PROFRAG_LENB_LAST)


/* Control Block Field Detials */
/* =========================== */

#define PROCB_CONTROLB_LAST     31
#define PROCB_CONTROLB_SUSPEND  30
#define PROCB_CONTROLB_INT      29
#define PROCB_CONTROLB_NOCRC    20
#define PROCB_CONTROLB_FLEXIBLE 19
#define PROCB_CONTROLB_ACTION   16
#define PROCB_CONTROLB_DONE     15
#define PROCB_CONTROLB_OK       13
#define PROCB_CONTROLB_UNDERRUN 12

#define PROCB_CONTROLF_LAST     (1 << PROCB_CONTROLB_LAST)
#define PROCB_CONTROLF_SUSPEND  (1 << PROCB_CONTROLB_SUSPEND)
#define PROCB_CONTROLF_INT      (1 << PROCB_CONTROLB_INT)
#define PROCB_CONTROLF_NOCRC    (1 << PROCB_CONTROLB_NOCRC)
#define PROCB_CONTROLF_FLEXIBLE (1 << PROCB_CONTROLB_FLEXIBLE)
#define PROCB_CONTROLF_ACTION   (0x7 << PROCB_CONTROLB_ACTION)
#define PROCB_CONTROLF_DONE     (1 << PROCB_CONTROLB_DONE)
#define PROCB_CONTROLF_OK       (1 << PROCB_CONTROLB_OK)
#define PROCB_CONTROLF_UNDERRUN (1 << PROCB_CONTROLB_UNDERRUN)

#define PROCB_TXINFOB_FRAGCOUNT  24
#define PROCB_TXINFOB_THRESHOLD  16
#define PROCB_TXINFOB_EOF        15
#define PROCB_TXINFOB_BUFFERSIZE  0

#define PROCB_TXINFOF_FRAGCOUNT  (0xff << PROCB_TXINFOB_FRAGCOUNT)
#define PROCB_TXINFOF_THRESHOLD  (0xff << PROCB_TXINFOB_THRESHOLD)
#define PROCB_TXINFOF_EOF        (1 << PROCB_TXINFOB_EOF)
#define PROCB_TXINFOF_BUFFERSIZE (0x3fff << PROCB_TXINFOB_BUFFERSIZE)

#define PROCB_RXINFOB_BUFFERSIZE 16
#define PROCB_RXINFOB_EOF        15
#define PROCB_RXINFOB_SIZEVALID  14
#define PROCB_RXINFOB_FRAMESIZE   0

#define PROCB_RXINFOF_BUFFERSIZE (0x3fff << PROCB_RXINFOB_BUFFERSIZE)
#define PROCB_RXINFOF_EOF        (1 << PROCB_RXINFOB_EOF)
#define PROCB_RXINFOF_SIZEVALID  (1 << PROCB_RXINFOB_SIZEVALID)
#define PROCB_RXINFOF_FRAMESIZE  (0x3fff << PROCB_RXINFOB_FRAMESIZE)

#define PROCB_CF0B_CACHELINESTOP 27
#define PROCB_CF0B_READALIGN     26
#define PROCB_CF0B_MWI           24
#define PROCB_CF0B_ADAPTIVEIFS   16
#define PROCB_CF0B_TXFIFOLIM     12
#define PROCB_CF0B_RXFIFOLIM      8
#define PROCB_CF0B_SIZE           0

#define PROCB_CF0F_ADAPTIVEIFS   0x00ff0000
#define PROCB_CF0F_TXFIFOLIM     0x00007000
#define PROCB_CF0F_RXFIFOLIM     0x00000f00
#define PROCB_CF0F_SIZE          0x0000003f

#define PROCB_CF1B_UNDERRUNRETRIES 25
#define PROCB_CF1B_DISCARDRUNTS    24

#define PROCB_CF1F_DYNAMICTBD      0x80000000
#define PROCB_CF1F_2FRAMESMAX      0x40000000
#define PROCB_CF1F_UNDERRUNRETRIES 0x06000000
#define PROCB_CF1F_DISCARDRUNTS    0x01000000
#define PROCB_CF1F_SAVEBADFRAMES   0x00800000
#define PROCB_CF1F_SAVEOVERRUNS    0x00400000
#define PROCB_CF1F_STDSTATS        0x00200000
#define PROCB_CF1F_STDTXBLOCK      0x00100000
#define PROCB_CF1F_CIINT           0x00080000
#define PROCB_CF1F_TNOINT          0x00040000
#define PROCB_CF1F_TCOSTATS        0x00040000
#define PROCB_CF1F_LATEINT         0x00010000
#define PROCB_CF1F_THROTTLEDMA     0x00008000
#define PROCB_CF1F_RXDMAMAXSIZE    0x00007f00
#define PROCB_CF1F_TXDMAMAXSIZE    0x0000007f

#define PROCB_CF2B_PRIORITY       24
#define PROCB_CF2B_LOOPBACK       22
#define PROCB_CF2B_PREAMBLETYPE   20
#define PROCB_CF2B_NOSOURCEINSERT 19
#define PROCB_CF2B_MCASTWAKE      15
#define PROCB_CF2B_ARPWAKE        14
#define PROCB_CF2B_LINKWAKE       13
#define PROCB_CF2B_VLANARPWAKE    12
#define PROCB_CF2B_VLANTCO        12
#define PROCB_CF2B_TCPCHECKSUM     8
#define PROCB_CF2B_NOCSMA          7
#define PROCB_CF2B_MIIMODE         0

#define PROCB_CF2F_PRIORITY        (0x7 << PROCB_CF2B_PRIORITY)
#define PROCB_CF2F_LOOPBACK        0x00c00000
#define PROCB_CF2F_PREAMBLETYPE    0x00300000
#define PROCB_CF2F_NOSOURCEINSERT  (1 << PROCB_CF2B_NOSOURCEINSERT)
#define PROCB_CF2F_MIIMODE         (1 << PROCB_CF2B_MIIMODE)

#define PROCB_CF3B_CDT            31
#define PROCB_CF3B_CRC16          29
#define PROCB_CF3B_IGNOREUL       28
#define PROCB_CF3B_WAITAFTERWIN   26
#define PROCB_CF3B_NOBCAST        25
#define PROCB_CF3B_PROM           24
#define PROCB_CF3B_ARPFILTER       8
#define PROCB_CF3B_IFS             4
#define PROCB_CF3B_RXPRIORITY      0

#define PROCB_CF3F_CDT            (1 << PROCB_CF3B_CDT)
#define PROCB_CF3F_PROM           (1 << PROCB_CF3B_PROM)
#define PROCB_CF3F_ARPFILTER      (0xffff << PROCB_CF3B_ARPFILTER)
#define PROCB_CF3F_IFS            (0xf << PROCB_CF3B_IFS)
#define PROCB_CF3F_RXPRIORITY     (1 << PROCB_CF3B_RXPRIORITY)

#define PROCB_CF4B_USEFDPIN       31
#define PROCB_CF4B_FORCEFD        30
#define PROCB_CF4B_REJECTFC       29
#define PROCB_CF4B_FDRESTARTFC    28
#define PROCB_CF4B_FDRESTOPFC     27
#define PROCB_CF4B_NOFDTXFC       26
#define PROCB_CF4B_NOMAGICWAKE    25
#define PROCB_CF4B_ADDRESSWAKE    24
#define PROCB_CF4B_LONGRXOK       19
#define PROCB_CF4B_SAVECRC        18
#define PROCB_CF4B_PADDING        17
#define PROCB_CF4B_STRIPPING      16

#define PROCB_CF4F_USEFDPIN      (1 << PROCB_CF4B_USEFDPIN)
#define PROCB_CF4F_PRIFCTHRESH   0x00700000
#define PROCB_CF4F_FCDELAY       0x0000ffff
#define PROCB_CF4F_PADDING       (1 << PROCB_CF4B_PADDING)

#define PROCB_CF5B_ALLMCAST      11
#define PROCB_CF5B_MULTIADDRESS   6
#define PROCB_CF5B_ALTPRIFCFIELD  5

#define PROCB_CF5F_ALLMCAST      (1 << PROCB_CF5B_ALLMCAST)
#define PROCB_CF5F_MULTIADDRESS  (1 << PROCB_CF5B_MULTIADDRESS)


/* Statistics */
/* ========== */

#define PROSTAT_TXFRAMESOK 0
#define PROSTAT_FRAMESDEFERRED 5
#define PROSTAT_RXFRAMESOK 9
#define PROSTAT_RXOVERRUNS 13
#define PROSTAT_TXUNDERRUNS 3


#endif
