##begin config
basename Layout
version 44.1
classid "layout.gadget"
superclass GADGETCLASS
classdatatype struct LayoutData
libbasetype struct LayoutBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/layout.h>
##end cdef
##begin cdefprivate
#include "layout_intern.h"
##end cdefprivate
##begin functionlist
Class *LAYOUT_GetClass() ()
BOOL ActivateLayoutGadget(struct Gadget *gadget, struct Window *window, struct Requester *requester, ULONG object) (A0, A1, A2, D0)
void FlushLayoutDomainCache(struct Gadget *gadget) (A0)
BOOL RethinkLayout(struct Gadget *gadget, struct Window *window, struct Requester *requester, BOOL refresh) (A0, A1, A2, D0)
void LayoutLimits(struct Gadget *gadget, struct LayoutLimits *limits, struct TextFont *font, struct Screen *screen) (A0, A1, A2, A3)
Class *PAGE_GetClass() ()
ULONG SetPageGadgetAttrsA(struct Gadget *gadget, Object *object, struct Window *window, struct Requester *requester, struct TagItem *tags) (A0, A1, A2, A3, A4)
void RefreshPageGadget(struct Gadget *gadget, Object *object, struct Window *window, struct Requester *requester) (A0, A1, A2, A3)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
GM_LAYOUT
GM_DOMAIN
GM_HITTEST
##end methodlist
