##begin config
version 0.1
residentpri 86
libbase BWFMBase
libbasetype struct BWFMBase
##end config
##begin cdef
#include <inttypes.h>
#include <exec/tasks.h>
##end cdef
##begin cdefprivate
#include "bwfm_private.h"
##end cdefprivate
##begin functionlist
int BWFMAttach() ()
uint32_t BWFMChipID() ()
int BWFMStartFirmware(void * fw, uint32_t fwlen, void * nvram, uint32_t nvlen) (A0, D0, A1, D1)
int BWFMGetMAC(uint8_t * mac) (A0)
int BWFMIoctl(uint32_t cmd, int set, void * buf, uint32_t len) (D0, D1, A0, D2)
int BWFMIovar(uint8_t * name, int set, void * buf, uint32_t len) (A0, D0, A1, D1)
int BWFMScan(void * out, int max) (A0, D0)
int BWFMLoadCLM(void * clm, uint32_t clmlen) (A0, D0)
int BWFMTxData(void * eth, uint32_t ethlen) (A0, D0)
int BWFMRxFrame(void * buf, uint32_t bufsize, uint32_t * info) (A0, D0, A1)
int BWFMJoin(uint8_t * ssid, uint32_t ssidlen, uint8_t * pass, uint32_t passlen) (A0, D0, A1, D1)
int BWFMSetRxSignal(struct Task * task, uint32_t sigmask) (A0, D0)
void BWFMAckRx() ()
void BWFMClearInt() ()
void BWFMEventPost(void * ev, uint32_t len) (A0, D0)
int BWFMScanIE(int idx, void * buf, uint32_t bufsize) (D0, A0, D1)
##end functionlist
