##begin config
version 1.0
basename DWMAC
libbase DWMACBase
libbasetype struct DWMACBase
residentpri -120
beginio_func DWMAC_BeginIO
abortio_func DWMAC_AbortIO
##end config
##begin cdefprivate
#include "dwmac.h"
##end cdefprivate
