##begin config
basename        LinuxFBGfx
libbase         LinuxFBBase
libbasetype     struct LinuxFB_base
version         45.1
residentpri     8
classid         CLID_Hidd_Gfx_LinuxFB
superclass      CLID_Hidd_Gfx
classptr_field  lsd.gfxclass
classdatatype   struct LinuxFB_data
##end config

##begin cdefprivate
#include "linuxfbgfx_intern.h"
#include "linuxfbgfx_bitmap.h"
#include "linuxfbgfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist

##begin class
##begin config
basename LinuxFBBM
type hidd
superclass CLID_Hidd_ChunkyBM
classptr_field lsd.bmclass
classdatatype struct LinuxFBBitMapData
##end config

##begin methodlist
.interface Root
New
.interface Hidd_BitMap
SetColors
##end methodlist
##end class

##begin class
##begin config
basename LinuxFBDisplay
type hidd
classptr_field lsd.displayclass
classid         CLID_Hidd_Display_LinuxFB
superclass CLID_Hidd_Display
classdatatype struct LinuxFBDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
SetGamma
##end methodlist
##end class
