#!/bin/sh
# Short script to check for used tools and generate them if necessary

echo "Welcome for AROS configuration."

### This may go into ./configure ???
echo -n "Do you want to cross-compile [y/N] ?"
read cross
case "$cross" in
  [yY] | [yY]es )
    echo Yes.
### INSERT CROSSCOMPILING STUFF HERE
    ;;
  *)
### INSERT THE STUFF FOR NORMAL COMPILING HERE
    echo No.
    ;;
esac


### This is really needed _before_ anything else, because without mmake
### you can't do anything and the user doesn't know what to do (unless
### he read ./INSTALL ;-)

echo Checking for AROS Tools...
cd tools

echo -n "Checking for Makefile Generation Tool... "
if [ -x "genmf/genmf" ] ; then
  echo "tools/genmf/genmf"
else
  echo "Not found!"
  echo "Trying to generate it..."
  cd genmf
  make
  if [ -x "genmf" ] ; then
    echo "Successfully generated tool."
  else
    echo "Failed to generate tools/genmf/genmf !!!"
    exit -1
  fi
  cd ..
fi

echo -n "Checking for C-Source Packer Tool... "
if [ -x "cpak/cpak" ] ; then
  echo "tools/cpak/cpak"
else
  echo "Not found!"
  echo "Trying to generate it..."
  cd cpak
  make
  if [ -x "cpak" ] ; then
    echo "Successfully generated tool."
  else
    echo "Failed to generate tools/cpak/cpak !!!"
    exit -1
  fi
  cd ..
fi

echo -n "Checking for MetaMake... "
if [ -x "`which mmake`" ] ; then
  echo `which mmake`
else
  if [ -x "MetaMake/mmake" ] ; then
    echo "locally installed in tools/MetaMake/mmake."
  else
    echo "Not found!"
    echo "Trying to generate it..."
    cd MetaMake
    make
    if [ -x "mmake" ] ; then
      echo "Successfully generated tool."
    else
      echo "Failed to generate tools/MetaMake/mmake !!!"
      exit -1
    fi
    cd ..
  fi
fi

cd ..
echo -n "Checking for MetaMake Config File..."
if [ -e "$HOME/.mmake.config" ] ; then
  echo "$HOME/.mmake.config"
else
  if [ -e "mmake.config" ] ; then
    echo "locally installed in mmake.config."
  else
    echo "Not found!"
    echo "Using default."
    cp mmake.config.in mmake.config.tmp
    echo -n "Do you want to edit it now [y/N]?"
    read edit
    case "$edit" in
      [yY] | [yY]es )
        if [ ! -x "$EDITOR" ] ; then
          echo -n "What is your favourite editor?"
          read EDITOR
        fi
        $EDITOR mmake.config.tmp
        echo -n "Do you want to copy it into your Home [y/N]?"
        read tohome
        case "$tohome" in
          [yY] | [yY]es )
            mv mmake.config.tmp $HOME/.mmake.config
            ;;
          *)
            mv mmake.config.tmp mmake.config
            ;;
        esac
        ;;
      *)
        mv mmake.config.tmp mmake.config
        ;;
    esac
  fi
fi

echo "You have installed all necessary tools to compile AROS now."
echo "Type mmake AROS to start building the tree."
echo
echo "If you want to change the configuration, feel free to call $0 again."
echo
