##begin config
version 0.1
residentpri 88
libbase DMABase
libbasetype struct DMABase
##end config
##begin cdef
#include <inttypes.h>
##end cdef
##begin cdefprivate
#include "dma_private.h"
##end cdefprivate
##begin functionlist
int DMAAllocChannel(unsigned int flags) (D0)
void DMAFreeChannel(int channel) (D0)
int DMAWaitChannel(int channel, unsigned int timeout_us) (D0, D1)
##end functionlist
