##begin config
version 50.0
basename Accounts
libbase AccountsBase
libbasetype struct AccountsBase
libbasetypeextern struct Library
residentpri 0
rellib stdc
##end config

##begin cdef
#include <exec/types.h>
#include <envoy/nipc.h>
#include <envoy/accounts.h>
##end cdef

##begin cdefprivate
#include "accounts_intern.h"
##end cdefprivate

##begin functionlist
struct UserInfo *AllocUserInfo() ()
struct GroupInfo *AllocGroupInfo() ()
void FreeUserInfo(struct UserInfo *user) (A0)
void FreeGroupInfo(struct GroupInfo *group) (A0)
ULONG VerifyUser(STRPTR userName, STRPTR password, struct UserInfo *user) (A0, A1, A2)
ULONG MemberOf(struct GroupInfo *group, struct UserInfo *user) (A0, A1)
ULONG NameToUser(STRPTR userName, struct UserInfo *user) (A0, A1)
ULONG NameToGroup(STRPTR groupName, struct GroupInfo *group) (A0, A1)
ULONG IDToUser(UWORD userID, struct UserInfo *user) (D0, A0)
ULONG IDToGroup(UWORD groupID, struct GroupInfo *group) (D0, A0)
ULONG NextUser(struct UserInfo *user) (A0)
ULONG NextGroup(struct GroupInfo *group) (A0)
ULONG NextMember(struct GroupInfo *group, struct UserInfo *user) (A0, A1)
STRPTR ECrypt(STRPTR buffer, STRPTR password, STRPTR username) (A0, A1, A2)
ULONG VerifyUserCrypt(STRPTR userName, STRPTR password, struct UserInfo *user) (A0, A1, A2)
.skip 10
ULONG AccVerifyUser(STRPTR userName, STRPTR password, struct UserInfo *user, struct Entity *server) (A0, A1, A2, A3)
ULONG AccVerifyUserCrypt(STRPTR userName, STRPTR password, struct UserInfo *user, struct Entity *server) (A0, A1, A2, A3)
ULONG AccMemberOf(struct GroupInfo *group, struct UserInfo *user, struct Entity *server) (A0, A1, A2)
ULONG AccNameToUser(STRPTR userName, struct UserInfo *user, struct Entity *server) (A0, A1, A2)
ULONG AccNameToGroup(STRPTR groupName, struct GroupInfo *group, struct Entity *server) (A0, A1, A2)
ULONG AccIDToUser(UWORD userID, struct UserInfo *user, struct Entity *server) (D0, A0, A1)
ULONG AccIDToGroup(UWORD groupID, struct GroupInfo *group, struct Entity *server) (D0, A0, A1)
ULONG AccNextUser(struct UserInfo *user, struct Entity *server) (A0, A1)
ULONG AccNextGroup(struct GroupInfo *group, struct Entity *server) (A0, A1)
ULONG AccNextMember(struct GroupInfo *group, struct UserInfo *user, struct Entity *server) (A0, A1, A2)
.skip 10
ULONG AccModifyUser(struct AuthorityInfo *authority, struct UserInfo *newUser, struct UserInfo *user, struct Entity *server) (A0, A1, A2, A3)
ULONG AccSetPassword(struct AuthorityInfo *authority, struct UserInfo *user, STRPTR password, struct Entity *server) (A0, A1, A2, A3)
ULONG AccModifyGroup(struct AuthorityInfo *authority, struct GroupInfo *newGroup, struct GroupInfo *group, struct Entity *server) (A0, A1, A2, A3)
ULONG AccAddUser(struct AuthorityInfo *authority, struct UserInfo *user, STRPTR password, struct Entity *server) (A0, A1, A2, A3)
ULONG AccDeleteUser(struct AuthorityInfo *authority, struct UserInfo *user, struct Entity *server) (A0, A1, A2)
ULONG AccAddGroup(struct AuthorityInfo *authority, struct GroupInfo *group, struct Entity *server) (A0, A1, A2)
ULONG AccDeleteGroup(struct AuthorityInfo *authority, struct GroupInfo *group, struct Entity *server) (A0, A1, A2)
ULONG AccAddMember(struct AuthorityInfo *authority, struct GroupInfo *group, struct UserInfo *user, struct Entity *server) (A0, A1, A2, A3)
ULONG AccRemoveMember(struct AuthorityInfo *authority, struct GroupInfo *group, struct UserInfo *user, struct Entity *server) (A0, A1, A2, A3)
##end functionlist
