##begin config
basename Bevel
version 44.1
classid "bevel.image"
classdatatype struct BevelData
libbasetype struct BevelBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/imageclass.h>
#include <images/bevel.h>
##end cdef
##begin cdefprivate
#include "bevel_intern.h"
##end cdefprivate
##begin functionlist
Class *BEVEL_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
IM_DRAW
##end methodlist
