#ifndef _LINUX_OBJTOOL_H_
#define _LINUX_OBJTOOL_H_
#define STACK_FRAME_NON_STANDARD(func)
#define STACK_FRAME_NON_STANDARD_FP(func)
#define UNWIND_HINT_SAVE
#define UNWIND_HINT_RESTORE
#define UNWIND_HINT_UNDEFINED
#endif
