.TH FTDUMP 1 "March 2019" "FreeType 2.10.0"
.
.
.SH NAME
.
ftdump \- simple font dumper
.
.
.SH SYNOPSIS
.
.B ftdump
.RI [ options ]
.I fontname
.
.
.SH DESCRIPTION
.
.B ftdump
lists information about a font file that is relevant for FreeType.
.
.PP
This program is part of the FreeType demos package.
.
.
.SH OPTIONS
.
.TP
.B \-c, \-C
Print charmap coverage.
.
.TP
.B \-n
Print SFNT name tables.
.
.TP
.B \-p
Print TrueType programs.
.
.TP
.B \-t
Print SFNT table list.
.
.TP
.B \-u
Emit UTF-8.
.
.TP
.B \-v
Show version.
.
.\" eof
