##begin config
version         26.1
residentpri     90
libbasetype     struct IntHiddLlvmpipeBase
basename        HiddLlvmpipe
classid         CLID_Hidd_Gallium_Llvmpipe
superclass      CLID_Hidd_Gallium
classptr_field  sd.galliumclass
classdatatype   struct HiddGalliumLlvmpipeData
rellib posixc
rellib stdc
##end config

##begin cdefprivate
#include <hidd/gallium.h>
#include "llvmpipe_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gallium
CreatePipeScreen
DisplayResource
##end methodlist
