##begin config
version 50.0
basename Envoy
libbase EnvoyBase
libbasetype struct EnvoyBase
libbasetypeextern struct Library
residentpri 0
rellib stdc
##end config

##begin cdef
#include <exec/types.h>
#include <utility/tagitem.h>
#include <envoy/envoy.h>
##end cdef

##begin cdefprivate
#include "envoy_intern.h"
##end cdefprivate

##begin functionlist
BOOL HostRequestA(struct TagItem *tags) (A0)
BOOL LoginRequestA(struct TagItem *tags) (A0)
BOOL UserRequestA(struct TagItem *tags) (A0)
.skip 11
BOOL PasswordRequestA(struct TagItem *tags) (A0)
.skip 12
##end functionlist
