##begin config
version 0.1
libbase I2CDWBase
libbasetype struct I2CDWBase
classdriver Hidd_I2CDW
superclass CLID_Hidd_I2C
oopbase OOPBase
residentpri 75
##end config
##begin cdef
#include <exec/types.h>
##end cdef
##begin cdefprivate
#include "i2c_dw.h"
##end cdefprivate
##begin methodlist
PutByte
GetByte
WriteRead
##end methodlist
