##begin config
basename Space
version 44.1
classid "space.gadget"
superclass GADGETCLASS
classdatatype struct SpaceData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/space.h>
##end cdef
##begin cdefprivate
#include "space_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
