#ifdef __x86_64__
#define __stdcall
#else
#define __stdcall __attribute__((stdcall))
#endif

#define WSABASEERR		10000
#define WSAEINTR		(WSABASEERR+4)
#define WSAEBADF		(WSABASEERR+9)
#define WSAEACCES		(WSABASEERR+13)
#define WSAEFAULT		(WSABASEERR+14)
#define WSAEINVAL		(WSABASEERR+22)
#define WSAEMFILE		(WSABASEERR+24)
#define WSAEWOULDBLOCK		(WSABASEERR+35)
#define WSAEINPROGRESS		(WSABASEERR+36) /* deprecated on WinSock2 */
#define WSAEALREADY		(WSABASEERR+37)
#define WSAENOTSOCK		(WSABASEERR+38)
#define WSAEDESTADDRREQ		(WSABASEERR+39)
#define WSAEMSGSIZE		(WSABASEERR+40)
#define WSAEPROTOTYPE		(WSABASEERR+41)
#define WSAENOPROTOOPT		(WSABASEERR+42)
#define WSAEPROTONOSUPPORT	(WSABASEERR+43)
#define WSAESOCKTNOSUPPORT	(WSABASEERR+44)
#define WSAEOPNOTSUPP		(WSABASEERR+45)
#define WSAEPFNOSUPPORT		(WSABASEERR+46)
#define WSAEAFNOSUPPORT		(WSABASEERR+47)
#define WSAEADDRINUSE		(WSABASEERR+48)
#define WSAEADDRNOTAVAIL	(WSABASEERR+49)
#define WSAENETDOWN		(WSABASEERR+50)
#define WSAENETUNREACH		(WSABASEERR+51)
#define WSAENETRESET		(WSABASEERR+52)
#define WSAECONNABORTED		(WSABASEERR+53)
#define WSAECONNRESET		(WSABASEERR+54)
#define WSAENOBUFS		(WSABASEERR+55)
#define WSAEISCONN		(WSABASEERR+56)
#define WSAENOTCONN		(WSABASEERR+57)
#define WSAESHUTDOWN		(WSABASEERR+58)
#define WSAETOOMANYREFS		(WSABASEERR+59)
#define WSAETIMEDOUT		(WSABASEERR+60)
#define WSAECONNREFUSED		(WSABASEERR+61)
#define WSAELOOP		(WSABASEERR+62)
#define WSAENAMETOOLONG		(WSABASEERR+63)
#define WSAEHOSTDOWN		(WSABASEERR+64)
#define WSAEHOSTUNREACH		(WSABASEERR+65)
#define WSAENOTEMPTY		(WSABASEERR+66)
#define WSAEPROCLIM		(WSABASEERR+67)
#define WSAEUSERS		(WSABASEERR+68)
#define WSAEDQUOT		(WSABASEERR+69)
#define WSAESTALE		(WSABASEERR+70)
#define WSAEREMOTE		(WSABASEERR+71)
#define WSAEDISCON		(WSABASEERR+101)
#define WSASYSNOTREADY		(WSABASEERR+91)
#define WSAVERNOTSUPPORTED	(WSABASEERR+92)
#define WSANOTINITIALISED	(WSABASEERR+93)
#define WSAHOST_NOT_FOUND	(WSABASEERR+1001)
#define WSATRY_AGAIN		(WSABASEERR+1002)
#define WSANO_RECOVERY		(WSABASEERR+1003)
#define WSANO_DATA		(WSABASEERR+1004)

/* WinSock2 specific error codes */
#define WSAENOMORE		(WSABASEERR+102)
#define WSAECANCELLED		(WSABASEERR+103)
#define WSAEINVALIDPROCTABLE	(WSABASEERR+104)
#define WSAEINVALIDPROVIDER	(WSABASEERR+105)
#define WSAEPROVIDERFAILEDINIT	(WSABASEERR+106)
#define WSASYSCALLFAILURE	(WSABASEERR+107)
#define WSASERVICE_NOT_FOUND	(WSABASEERR+108)
#define WSATYPE_NOT_FOUND	(WSABASEERR+109)
#define WSA_E_NO_MORE		(WSABASEERR+110)
#define WSA_E_CANCELLED		(WSABASEERR+111)
#define WSAEREFUSED		(WSABASEERR+112)

#define WSADESCRIPTION_LEN	256
#define WSASYS_STATUS_LEN	128

typedef struct WSAData
{
    UWORD wVersion;
    UWORD wHighVersion;
    char szDescription[WSADESCRIPTION_LEN+1];
    char szSystemStatus[WSASYS_STATUS_LEN+1];
    unsigned short iMaxSockets;
    unsigned short iMaxUdpDg;
    char *lpVendorInfo;
} WSADATA, *LPWSADATA;

struct PROTOENT
{
    char *p_name;
    char **p_aliases;
    short p_proto;
};
