#include "rtl8169.h"

struct card_def cards[NBR_CARDS] =
{
    { PCI_VENDOR_ID_REALTEK,    0x8129, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_REALTEK,    0x8136, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_2 },
    { PCI_VENDOR_ID_REALTEK,    0x8167, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_REALTEK,    0x8168, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_1 },
    { PCI_VENDOR_ID_REALTEK,    0x8169, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_DLINK,      0x4300, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_AT,         0xc107, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_USROBOTICS, 0x0116, PCI_ANY_ID, PCI_ANY_ID, RTL_CFG_0 },
    { PCI_VENDOR_ID_LINKSYS,    0x1032, PCI_ANY_ID, 0x0024,     RTL_CFG_0 },
    // Who in hell is vendor 0x1 ?
    { 0x0001,                   0x8168, PCI_ANY_ID, 0x2410,     RTL_CFG_2 },
    { 0, 0, 0, 0, 0 }
};

