##begin config
basename	VESAGfx
libbasetype	struct VESAGfxBase
version		45.5
residentpri     9
classptr_field  vsd.vesagfxclass
classdatatype	struct VESAGfxHiddData
classid         CLID_Hidd_Gfx_VESA
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "vesagfx_intern.h"
#include "vesagfx_hidd.h"
#include "vesagfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist


##begin class
##begin config
basename VESAGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_VESA
superclass CLID_Hidd_Display
classdatatype struct VESAGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
Show
##end methodlist
##end class


##begin class
##begin config
basename VESAGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_VESA
superclass CLID_Hidd_ChunkyBM
classdatatype struct VESAGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
UpdateRect
##end methodlist
##end class
