#ifndef PROTO_ALL_H
#define PROTO_ALL_H

#include <proto/alib.h>
#include <proto/amigaguide.h>
#include <proto/asl.h>
#include <proto/battclock.h>
#include <proto/battmem.h>
#include <proto/bullet.h>
#include <proto/cardres.h>
#include <proto/cia.h>
#include <proto/colorwheel.h>
#include <proto/commodities.h>
#include <proto/console.h>
#include <proto/datatypes.h>
#include <proto/disk.h>
#include <proto/diskfont.h>
#include <proto/dos.h>
#include <proto/dtclass.h>
#include <proto/exec.h>
#include <proto/expansion.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/icon.h>
#include <proto/iffparse.h>
#include <proto/input.h>
#include <proto/intuition.h>
#include <proto/keymap.h>
#include <proto/layers.h>
#include <proto/locale.h>
#include <proto/lowlevel.h>
#include <proto/mathieeedoubbas.h>
#include <proto/mathieeedoubtrans.h>
#include <proto/mathieeesingbas.h>
#include <proto/mathieeesingtrans.h>
#include <proto/misc.h>
#include <proto/nonvolatile.h>
#include <proto/potgo.h>
#include <proto/ramdrive.h>
#include <proto/realtime.h>
#include <proto/rexxsyslib.h>
#include <proto/timer.h>
#include <proto/translator.h>
#include <proto/utility.h>
#include <proto/wb.h>

#endif /* PROTO_ALL_H */
