##begin config
version 45.5
libbase nh
libbasetype struct BTHidBase
libbasetypeextern struct Library
residentpri 29
basename bthid
##end config

##begin cdef
#include <libraries/btclass.h>
#include "bthid.h"
##end cdef

##begin functionlist
LONG btcGetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
LONG btcSetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
SIPTR btcDoMethodA(ULONG methodid, IPTR *methoddata) (D0,A1)
##end functionlist
