/* cdcontrol.h */

#define ACTION_USER 2050

enum cdcmd {
  CDCMD_LOWERCASE,
  CDCMD_MACTOISO,
  CDCMD_CONVERTSPACES,
  CDCMD_SHOWVERSION,
  CDCMD_HFSFIRST,
  CDCMD_DATAEXT,
  CDCMD_RESOURCEEXT,
  CDCMD_UNICODETABLE
};
