##begin config
basename GetScreenMode
version 44.1
classid "getscreenmode.gadget"
superclass GADGETCLASS
classdatatype struct GetScreenModeData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/getscreenmode.h>
##end cdef
##begin cdefprivate
#include "getscreenmode_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
