##begin config
basename Window
version 44.1
classid "window.class"
classdatatype struct WindowClassData
libbasetype struct WindowBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <classes/window.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
##end cdef
##begin cdefprivate
#include "window_intern.h"
##end cdefprivate
##begin functionlist
Class *WINDOW_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
WM_OPEN
WM_CLOSE
WM_HANDLEINPUT
WM_ICONIFY
WM_RETHINK
##end methodlist
