##begin config
basename	VCGfx
libbasetype	struct VCGfxBase
version		45.5
residentpri     9
classptr_field  vsd.vcgfxclass
classdatatype	struct VCGfxHiddData
classid         CLID_Hidd_Gfx_VCFB
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "vcgfx_intern.h"
#include "vcgfx_hidd.h"
#include "vcgfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist


##begin class
##begin config
basename VCGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_VCFB
superclass CLID_Hidd_Display
classdatatype struct VCGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
Show
##end methodlist
##end class


##begin class
##begin config
basename VCGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_VCFB
superclass CLID_Hidd_ChunkyBM
classdatatype struct VCGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
UpdateRect
##end methodlist
##end class
