# $Id$
TOP=..
CURDIR=workbench

include $(TOP)/config/make.cfg

SUBDIRS=c demos devs libs locale fonts classes

all: $(SDIR)/Startup-Sequence
	%subdirs_q target=all

clean::
	%subdirs_q Cleaning target=clean

$(SDIR)/Startup-Sequence : s/Startup-Sequence
	$(CP) $^ $@

setup:
	@true

%common
