#! /bin/sh
set -e

# Delete our backward-compatibility symlink.
package=grub
case "$1" in
remove | upgrade)
  if [ -d /usr/doc -a -L /usr/doc/$package ]; then
    rm -f /usr/doc/$package
  fi
  ;;
esac

# Install our info pages.
install-info --quiet --remove /usr/share/info/grub.info.gz
install-info --quiet --remove /usr/share/info/multiboot.info.gz
