#include <exec/types.h>
#include <exec/memory.h>
#include <libraries/mui.h>
#include <libraries/gadtools.h>
#include <libraries/asl.h>
#include <libraries/commodities.h>
#include <libraries/locale.h>
#include <dos/dos.h>
#include <dos/dostags.h>
#include <dos/filehandler.h>
#include <clib/exec_protos.h>
#include <clib/dos_protos.h>
#include <clib/intuition_protos.h>
#include <clib/muimaster_protos.h>
#include <clib/utility_protos.h>
#include <clib/commodities_protos.h>
#include <clib/asl_protos.h>
#include <clib/icon_protos.h>
#include <clib/alib_protos.h>
#include <pragmas/muimaster_pragmas.h>
#include <libraries/mui.h>
#include <stdio.h>
#include <string.h>
