##begin config
basename        DWI2C
libbase         DWI2CBase
libbasetype     struct DWI2CBase
version         1.0
residentpri     88
oopbase_field   psd.OOPBase
classid         CLID_Hidd_I2C_DW
superclass      CLID_Hidd_I2C
classptr_field  psd.i2cDrvClass
classdatatype   struct dwi2c_busdata
options noexpunge
##end config

##begin cdef
#include <exec/types.h>
##end cdef

##begin cdefprivate
#include <hidd/i2c.h>
#include "dwi2c_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Get
.interface Hidd_I2C
Start
Address
Stop
PutByte
GetByte
WriteRead
ProbeAddress
##end methodlist
