##begin config
version 0.1
libbasetype struct NetPrefsBase
libbase NetPrefsBase
residentpri 0
##end config
##begin cdef
#include "netprefs_intern.h"
##end cdef
##begin cdefprivate
##end cdefprivate
##begin functionlist
void RegisterProtoModule(struct NetPrefsModule *Module, APTR ModBase) (A0, A1)
void RegisterBase(CONST_STRPTR BaseID, APTR Base) (A0, A1)
APTR GetBase(CONST_STRPTR BaseID) (A0)
void RegisterProtoHandler(CONST_STRPTR name, ULONG family, struct MUI_CustomClass *winclass, NETPREFS_WRITETOKENS writetokens) (A0, D0, A1, A2)
##end functionlist
