##begin config
version 45.0
libbase base
libbasetype struct BTMidiBase
libbasetypeextern struct Library
residentpri 29
basename btmidi
##end config

##begin cdef
#include <libraries/btclass.h>
#include "btmidi.h"
##end cdef

##begin functionlist
LONG btcGetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
LONG btcSetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
SIPTR btcDoMethodA(ULONG methodid, IPTR *methoddata) (D0,A1)
##end functionlist
