##begin config
version 50.0
basename Echo
libbase EchoBase
libbasetype struct EchoBase
libbasetypeextern struct Library
residentpri 0
rellib stdc
##end config

##begin cdef
#include <exec/types.h>
#include <utility/tagitem.h>
#include <envoy/services.h>
##end cdef

##begin cdefprivate
#include "echo_intern.h"
##end cdefprivate

##begin functionlist
void RexxReserved() ()
ULONG StartServiceA(struct TagItem *tagList) (A0)
void GetServiceAttrsA(struct TagItem *tagList) (A0)
void SetServiceAttrsA(struct TagItem *tagList) (A0)
void AttemptShutdown(CONST_STRPTR desc, ULONG seconds) (A0, D0)
##end functionlist
