##begin config
basename FuelGauge
version 44.1
classid "fuelgauge.gadget"
superclass GADGETCLASS
classdatatype struct FuelGaugeData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/fuelgauge.h>
##end cdef
##begin cdefprivate
#include "fuelgauge_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
