# $Id$
TOP=../../..

include $(TOP)/config/make.cfg

SPECIAL_AFLAGS = -I../
CLIBDIR=$(GENDIR)/compiler/clib

FILES = setjmp longjmp

TESTS =

all: setup $(foreach f,$(FILES),$(CLIBDIR)/$(f).o)

setup :
	%mkdirs_q $(CLIBDIR)
	%add_objects $(foreach f,$(FILES), compiler/clib/$(f))

clean::
	$(RM) $(TESTS)

$(CLIBDIR)/%.o: %.s ../machine.i
	%assemble_q

%common
