# $Id$
TOP=../..

include $(TOP)/config/make.cfg

SUBDIRS= exec dos

all: subdirs

setup:
	%subdirs_q "Setting up" setup

clean::
	%subdirs_q "Cleaning" clean

subdirs:
	%subdirs_q target=all

%common
