blank_issues_enabled: false
contact_links:
  - name: Read the issue submission rules first
    url: https://github.com/aros-development-team/AROS/wiki
    about: Please check the documentation before opening an issue.