#!/bin/sh

if [ "$1" = "-d" ]; then
  rm /home/flavio/src/AROS/bin/linux-i386/gen/#?errors
  rm /home/flavio/src/AROS/bin/linux-i386/gen/include/#?/muimaster#?.h
  rm /home/flavio/src/AROS/bin/linux-i386/gen/workbench/libs/mui/functions.?
  shift
fi

make TOP=/home/flavio/src/AROS CURDIR=workbench/libs/mui -f mmakefile $*
