##begin config
basename SpeedBar
version 44.1
classid "speedbar.gadget"
superclass GADGETCLASS
classdatatype struct SpeedBarData
libbasetype struct SpeedBarBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/speedbar.h>
##end cdef
##begin cdefprivate
#include "speedbar_intern.h"
##end cdefprivate
##begin functionlist
Class *SPEEDBAR_GetClass() ()
struct Node *AllocSpeedButtonNodeA(UWORD number, struct TagItem *tags) (D0, A0)
void FreeSpeedButtonNode(struct Node *node) (A0)
void SetSpeedButtonNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void GetSpeedButtonNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
