#!/bin/sh
#
# $0 new old
#
# Replaces old with new if they differ. old is saved as old.bak
#

if cmp -s "$1" "$2"; then
    echo "$2 is unchanged"
    rm "$1"
else
    echo "Replacing $2 by $1"
    if [ -f "$2" ]; then
	mv "$2" "$2.bak"
    fi
    mv "$1" "$2"
fi
