##begin config
basename ClickTab
version 44.1
classid "clicktab.gadget"
superclass GADGETCLASS
classdatatype struct ClickTabData
libbasetype struct ClickTabBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/clicktab.h>
##end cdef
##begin cdefprivate
#include "clicktab_intern.h"
##end cdefprivate
##begin functionlist
Class *CLICKTAB_GetClass() ()
struct Node *AllocClickTabNodeA(struct TagItem *tags) (A0)
void FreeClickTabNode(struct Node *node) (A0)
void SetClickTabNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void GetClickTabNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
GM_GOINACTIVE
##end methodlist
