##begin config
version 1.0
basename BCMGENET
libbase BCMGENETBase
libbasetype struct BCMGENETBase
residentpri -120
beginio_func BCMGENET_BeginIO
abortio_func BCMGENET_AbortIO
##end config
##begin cdefprivate
#include "bcmgenet.h"
##end cdefprivate
