##begin config
basename Label
version 44.1
classid "label.image"
classdatatype struct LabelData
##end config
##begin cdef
#include <intuition/imageclass.h>
#include <images/label.h>
##end cdef
##begin cdefprivate
#include "label_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
IM_DRAW
##end methodlist
