##begin config
version 1.0
residentpri 45
libbase EntropyBase
libbasetype struct EntropyBase
libbasetypeextern struct Library
options resautoinit
##end config
##begin cdef
#include <resources/entropy.h>
##end cdef
##begin cdefprivate
#include <entropy_intern.h>
##end cdefprivate
##begin functionlist
LONG GetEntropy(APTR buffer, ULONG length) (A0, D0)
void AddEntropy(CONST_APTR data, ULONG length, ULONG bits) (A0, D0, D1)
ULONG GetEntropyInfo() ()
##end functionlist
