#ifndef LIBRARIES_AMISSLMASTER_H
#define LIBRARIES_AMISSLMASTER_H

#define AMISSL_V2           0x01    /* OBSOLETE NAME */
#define AMISSL_V096g        0x01
#define AMISSL_V097g        0x02

#define AMISSL_CURRENT_VERSION   AMISSL_V097g

#define AMISSLMASTER_MIN_VERSION 3

#endif /* !LIBRARIES_AMISSLMASTER_H */
