# $Id$
TOP=../..

include $(TOP)/config/make.cfg

SUBDIRS= clib exec

MACHINE_H = $(INCDIR)/aros/machine.h

all: setup $(MACHINE_H) subdirs

setup: machine.i
	%mkdirs_q $(INCDIR)
	%subdirs_q "Setting up" setup

$(MACHINE_H) : machine.h
	cp $< $@

clean::
	%subdirs_q "Cleaning" clean
	$(RM) $(MACHINE_H) $(TESTS) machine.i geninc

machine.i: geninc.c
	@echo "Creating geninc..."
	@$(CC) $(CFLAGS) -o geninc $<
	./geninc > machine.i

subdirs:
	%subdirs_q target=all

%common
