##begin config
basename Chooser
version 44.1
classid "chooser.gadget"
superclass GADGETCLASS
classdatatype struct ChooserData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/chooser.h>
##end cdef
##begin cdefprivate
#include "chooser_intern.h"
##end cdefprivate
##begin functionlist
struct Node *AllocChooserNodeA(struct TagItem *tags) (A0)
void FreeChooserNode(struct Node *node) (A0)
void SetChooserNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void GetChooserNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
GM_GOINACTIVE
##end methodlist
