##begin config
basename Slider
version 44.1
classid "slider.gadget"
superclass PROPGCLASS
classdatatype struct SliderData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/slider.h>
##end cdef
##begin cdefprivate
#include "slider_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
