#!/bin/zsh

export SP=$(dirname $0)
export CFG_NAME=$1
source $SP/setup initial

printi "Starting nightly build on "$CFG_NAME"..."

setl   update.log
source $SP/update
if [ $? != 0 ]; then
    printe "Updating sources FAILED! Aborting script."
    exit 5
fi
resetl

FAILED=""

for package in $CFG_PACKAGES; do
    zsh $SP/pkg/$package
    if [ $? != 0 ]; then
        printe "Build of package '"$package"' FAILED."
        FAILED="$FAILED $package"
    else
        printi "Build of package '"$package"' completed successfully."
    fi
done

setl cleanup.log
source $SP/cleanup
resetl

printi "Compressing log files..."
for file in $LOG_BASE/*.log; do
    bzip2 $file
done
