# $Id$
# Makefile for c_lib on AROS
TOP=../..

include $(TOP)/config/make.cfg

ifeq ($(FLAVOUR),native)
SUBDIRS=source
else
SUBDIRS=source
#vcpp vbcc
endif

all:
	%subdirs_q target=all

clean::
	%subdirs_q Cleaning clean

setup:
	%subdirs_q "Setting up" setup

%common
