##begin config
basename String
version 44.1
classid "string.gadget"
superclass STRGCLASS
classdatatype struct StringGadData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/string.h>
##end cdef
##begin cdefprivate
#include "string_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
