#pragma libcall GarshnelibBase ScreenModeRequest 1e A9803
#pragma libcall GarshnelibBase setCopperList 24 981004
#pragma libcall GarshnelibBase getTopScreenMode 2a 0
#pragma libcall GarshnelibBase getTopScreenDepth 30 0
#pragma libcall GarshnelibBase cloneTopScreen 36 1002
#pragma libcall GarshnelibBase GetColorTable 3c 801
#pragma libcall GarshnelibBase AvgBitsPerGun 42 001
#pragma libcall GarshnelibBase FadeAndLoadTable 48 190804
#pragma libcall GarshnelibBase BlankMousePointer 4e 801
#pragma libcall GarshnelibBase UnblankMousePointer 54 801
#pragma libcall GarshnelibBase RainbowPalette 5a 109804
#pragma libcall GarshnelibBase clearCopperList 60 801
