##begin config
basename	VideoCoreGfx
libbasetype	struct VideoCoreGfxBase
version		45.1
residentpri     9
classptr_field  vsd.vcsd_VideoCoreGfxClass
classid         CLID_Hidd_Gfx_VideoCore4
superclass      CLID_Hidd_Gfx
options         noexpunge
##end config

##begin cdefprivate
#include "vc4gfx_hidd.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gfx
CopyBox
##end methodlist

##begin class
##begin config
basename VideoCoreGfxDisplay
type hidd
superclass CLID_Hidd_Display
classid CLID_Hidd_Display_VideoCore4
classptr_field vsd.vcsd_VideoCoreGfxDisplayClass
classdatatype struct VideoCoreGfxDisplayData
##end config

##begin methodlist
.interface Root
Get
.interface Hidd_Display
CreateObject
SetCursorShape
SetCursorPos
SetCursorVisible
NominalDimensions
##end methodlist
##end class


##begin class
##begin config
basename VideoCoreGfxOnBM
type hidd
classptr_field vsd.vcsd_VideoCoreGfxOnBMClass
superclass CLID_Hidd_ChunkyBM
classdatatype struct BitmapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
Clear
FillRect
PutImage
GetImage
BlitColorExpansion
PutTemplate
##end methodlist
##end class


##begin class
##begin config
basename VideoCoreGfxOffBM
type hidd
classptr_field vsd.vcsd_VideoCoreGfxOffBMClass
superclass CLID_Hidd_ChunkyBM
classdatatype struct BitmapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_BitMap
SetColors
Clear
FillRect
PutImage
GetImage
BlitColorExpansion
PutTemplate
##end methodlist
##end class
