##begin config
basename      Flexgroup
version       1.0
date          16.09.2026
superclass    MUIC_Group
classdatatype struct Flexgroup_DATA
##end config

##begin cdefprivate
#include <libraries/mui.h>
#include <zune/flexgroup.h>
#include "flexgroup_private.h"
##end cdefprivate

##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
OM_GET
##end methodlist
