##begin config
version 45.0
libbase nh
libbasetype struct BTSdpBase
libbasetypeextern struct Library
residentpri 27
basename btsdp
##end config

##begin cdef
#include <libraries/btclass.h>
#include "btsdp.h"
##end cdef

##begin functionlist
LONG btcGetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
LONG btcSetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
SIPTR btcDoMethodA(ULONG methodid, IPTR *methoddata) (D0,A1)
##end functionlist
