#ifndef LOWLEVEL_CIATIMER_H
#define LOWLEVEL_CIATIMER_H

#define CIASTART_A      CIACRAF_START
#define CIASTOP_A       (CIACRAF_TODIN |CIACRAF_PBON | CIACRAF_OUTMODE | CIACRAF_SPMODE)
#define CIASTART_B      CIACRBF_START
#define CIASTOP_A       (CIACRBF_ALARM | CIACRBF_PBON | CIACRBF_OUTMODE)

#endif /* !LOWLEVEL_CIATIMER_H */

