##begin config
basename LED
version 44.1
classid "led.image"
classdatatype struct LEDData
libbasetype struct LEDBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/imageclass.h>
#include <images/led.h>
##end cdef
##begin cdefprivate
#include "led_intern.h"
##end cdefprivate
##begin functionlist
Class *LED_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
IM_DRAW
##end methodlist
