##begin config
basename      IconVolumeList
version       1.13
date          19.03.2025
superclass    MUIC_IconList
classdatatype struct IconVolumeList_DATA
##end config

##begin cdefprivate
#include <libraries/mui.h>
#include "iconvolumelist_private.h"
##end cdefprivate

##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
OM_GET
MUIM_IconList_Update
MUIM_IconList_UpdateEntry
MUIM_IconList_DestroyEntry
##end methodlist
