# $Id$
# Makefile for c_lib on AROS
TOP=../../..

include $(TOP)/config/make.cfg

ifeq ($(FLAVOUR),native)
SUBDIRS=include lib_source test_prg
else
SUBDIRS=include lib_source test_prg
endif

all:
	%subdirs_q target=all submf=makefile.aros

clean::
	%subdirs_q Cleaning clean submf=makefile.aros

setup:
	%subdirs_q "Setting up" setup submf=makefile.aros

%common
