##begin config
version 45.1
libbase rfw
libbasetype struct RtlFwBase
libbasetypeextern struct Library
residentpri 9
basename rtlbtv2
##end config

##begin cdef
#include <libraries/bluetooth.h>
#include "../rtlfwbase.h"
##end cdef

##begin functionlist
##end functionlist
