##begin config
basename	PCIDT
libbasetype	struct PCIDTBase
version		1.1
residentpri     87
oopbase_field   psd.OOPBase
superclass      CLID_Hidd_PCIDriver
classptr_field  psd.pcidtDriverClass
classdatatype   struct PCIDTBusData
options noincludes, noexpunge
##end config

##begin cdefprivate
#include <hidd/pci.h>
#include "pcidt.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Get
.interface Hidd_PCIDriver
ReadConfigByte
ReadConfigWord
ReadConfigLong
WriteConfigLong
MapPCI
PCItoCPU
CPUtoPCI
AllocPCIMem
FreePCIMem
AddInterrupt
##end methodlist


##begin class
##begin config
basename       PCIDTDev
type           hidd
superclass     CLID_Hidd_PCIDevice
classptr_field psd.pcidtDeviceClass
classdatatype  struct PCIDTDeviceData
##end config

##begin methodlist
.interface Root
New
Set
.interface Hidd_PCIDevice
ObtainVectors
GetVectorAttribs
##end methodlist
##end class
