/*** Automatically generated by genlibdefs.awk. Do not edit ***/
#ifndef _LIBDEFS_H
#define _LIBDEFS_H
#define NAME_STRING      "layers.library"
#define NT_TYPE          NT_LIBRARY
#define NOEXPUNGE
#define ROMBASED
#define LC_UNIQUE_PREFIX Layers
#define LC_BUILDNAME(n)  Layers ## n
#define LIBBASE          LayersBase
#define LIBBASETYPE      LayersBase
#define LIBBASETYPEPTR   LayersBase *
#define VERSION_NUMBER   41
#define REVISION_NUMBER  0
#define BASENAME         Layers
#define BASENAME_STRING  "Layers"
#define VERSION_STRING   "$VER: layers 41.0 (07.12.2000)\r\n"
#define LIBEND           Layers_end
#define LIBFUNCTABLE     Layers_functable
#define COPYRIGHT_STRING ""
#endif /* _LIBDEFS_H */
