##begin config
basename IPMI
libbasetype struct HiddIPMIIntBase
version 50.2
residentpri 90
classid CLID_Hidd_IPMI
superclass CLID_Hidd
classptr_field hbi_csd.ipmiClass
classdatatype struct HIDDIPMIData
oopbase_field  hbi_csd.cs_OOPBase
seglist_field  hbi_csd.cs_SegList
options noexpunge
##end config

##begin cdefprivate
#include "ipmi_intern.h"
##end cdefprivate

##begin interface
##begin config
interfaceid   hidd.ipmi
interfacename Hidd_IPMI
methodstub    HIDD_IPMI
methodbase    HiddIPMIBase
attributebase HiddIPMIAB
##end config

##begin attributelist
ULONG InterfaceType # [I.G]
ULONG SpecVersionMajor # [I.G]
ULONG SpecVersionMinor # [I.G]
ULONG I2CSlaveAddress # [I.G]
ULONG NVStorageAddress # [I.G]
IPTR  BaseAddress # [I.G]
ULONG BaseAddressModifier # [I.G]
ULONG AddressSpace # [I.G]
ULONG RegisterSpacing # [I.G]
ULONG InterruptNumber # [I.G]
##end attributelist

##begin methodlist
BOOL SendCommand(UBYTE netfn, UBYTE command, APTR request, ULONG requestLen, APTR response, ULONG *responseLen)
##end methodlist
##end interface

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_IPMI
SendCommand
##end methodlist
