##begin config
basename        virtio
version         1.0
libbasetype     struct VirtIOBase
residentpri     5
beginio_func    BeginIO
abortio_func    AbortIO
oopbase_field   virtio_OOPBase
options         noexpunge
##end config

##begin cdefprivate
#include <hidd/storage.h>
#include <hidd/virtio.h>
#include "virtio_intern.h"
##end cdefprivate

##begin cdef
##end cdef

##begin functionlist
##end functionlist

##begin interface
##begin config
interfaceid   hw.virtio
interfacename Hidd_VirtIO
methodstub    Hidd_VirtIO
methodbase    HiddVirtIOBase
attributebase HiddVirtIOAttrBase
##end config

##begin attributelist
char * Revision #            [..G] VirtIO Revision
char * Generation #            [..G] VirtIO Gen
ULONG Capabilities #
##end attributelist

##begin methodlist
##end methodlist
##end interface

##begin interface
##begin config
interfaceid   hidd.virtio.bus
interfacename Hidd_VirtIOBus
methodstub    HIDD_VirtIOBus
methodbase    HiddVirtIOBusBase
attributebase HiddVirtIOBusAB
##end config

##begin attributelist
##end attributelist

##begin methodlist
void Shutdown()
##end methodlist
##end interface

##begin interface
##begin config
interfaceid   hidd.virtio.unit
interfacename Hidd_VirtIOUnit
methodstub    HIDD_VirtIOUnit
methodbase    HiddVirtIOUnitBase
attributebase HiddVirtIOUnitAB
##end config

##begin attributelist
ULONG Features #
##end attributelist

##begin methodlist
##end methodlist
##end interface

##begin class
##begin config
basename VirtIO
type hidd
classid CLID_Hidd_VirtIO
classdatatype struct virtio_Controller
superclass CLID_Hidd_StorageController
classptr_field virtioClass
##end config

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_StorageController
RemoveBus
SetUpBus
CleanUpBus
##end methodlist
##end class

##begin class
##begin config
basename VirtIOBus
type hidd
classid CLID_Hidd_VirtIOBus
classdatatype struct virtio_Bus
superclass CLID_Hidd_StorageBus
classptr_field busClass
##end config

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_StorageBus
EnumUnits
.interface Hidd_VirtIOBus
Shutdown
##end methodlist
##end class

##begin class
##begin config
basename VirtIOUnit
type hidd
classdatatype struct virtio_Unit
superclass CLID_Hidd_StorageUnit
classptr_field unitClass
##end config

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist
##end class