##begin config
version 50.1
libbasetype struct SpeechBase
options noexpunge
beginio_func beginio
abortio_func abortio
##end config
##begin cdefprivate
#include <devices/speech.h>
#include "speech_intern.h"
##end cdefprivate
