##begin config
basename	EFIGfx
libbasetype	struct EFIGfxBase
version		45.1
residentpri     9
classptr_field  vsd.efigfxclass
classdatatype	struct EFIGfxHiddData
classid         CLID_Hidd_Gfx_EFI
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "efigfx_intern.h"
#include "efigfx_hidd.h"
#include "efigfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist


##begin class
##begin config
basename EFIGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_EFI
superclass CLID_Hidd_Display
classdatatype struct EFIGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
Show
##end methodlist
##end class


##begin class
##begin config
basename EFIGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_EFI
superclass CLID_Hidd_ChunkyBM
classdatatype struct EFIGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
UpdateRect
##end methodlist
##end class
