##begin config
basename        Amdgpu
libbasetype     struct AmdgpuBase
version         1.0
residentpri     9
classptr_field  vsd.amdgpuclass
classdatatype   struct AmdgpuHiddData
classid         CLID_Hidd_Amdgpu
superclass      CLID_Hidd_Gfx
options         noexpunge
##end config

##begin cdefprivate
#include "amdgpu_intern.h"
#include "amdgpu_hidd.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gfx
CopyBox
##end methodlist

##begin class
##begin config
basename AmdgpuDisplay
type hidd
classptr_field vsd.amdgpudisplayclass
classid         CLID_Hidd_Display_Amdgpu
superclass CLID_Hidd_Display
classdatatype struct AmdgpuDisplayData
##end config

##begin methodlist
.interface Root
Get
.interface Hidd_Display
CreateObject
SetGamma
SetCursorShape
SetCursorPos
SetCursorVisible
NominalDimensions
##end methodlist
##end class

##begin class
##begin config
basename AmdgpuOnBM
type hidd
classptr_field vsd.amdgpuonbmclass
superclass CLID_Hidd_BitMap
classdatatype struct BitmapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
PutPixel
Clear
GetPixel
FillRect
GetImage
PutImage
BlitColorExpansion
PutImageLUT
GetImageLUT
UpdateRect
##end methodlist
##end class


##begin class
##begin config
basename AmdgpuOffBM
type hidd
classptr_field vsd.amdgpuoffbmclass
superclass CLID_Hidd_BitMap
classdatatype struct BitmapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_BitMap
SetColors
PutPixel
GetPixel
FillRect
GetImage
PutImage
BlitColorExpansion
PutImageLUT
GetImageLUT
UpdateRect
##end methodlist
##end class

##begin class
##begin config
basename GalliumAmdgpu
type hidd
classptr_field vsd.galliumclass
classid         CLID_Hidd_Gallium_Amdgpu
superclass CLID_Hidd_Gallium
classdatatype struct HIDDGalliumAmdgpuData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gallium
CreatePipeScreen
DestroyPipeScreen
DisplayResource
##end methodlist
##end class
