### Lists of source files, included by Makefiles

# Linux 6.18.44 drivers/gpu/drm: the core subset, display helpers, TTM and the
# GPU scheduler, with the Linux compatibility layer (drm-compat) and the AROS
# side of the core (drm-aros). The same base the vmwaresvga hidd carries, kept
# as a copy so that neither driver's tree reaches into the other's.
AROS_AMDGPU_DRMCORE_SOURCES = \
            drm/display/drm_dp_helper \
            drm/display/drm_dp_mst_topology \
            drm/display/drm_hdmi_helper \
            drm/display/drm_scdc_helper \
            drm/drm_atomic \
            drm/drm_atomic_helper \
            drm/drm_atomic_state_helper \
            drm/drm_atomic_uapi \
            drm/drm_blend \
            drm/drm_bridge \
            drm/drm_color_mgmt \
            drm/drm_connector \
            drm/drm_crtc \
            drm/drm_crtc_helper \
            drm/drm_damage_helper \
            drm/drm_displayid \
            drm/drm_edid \
            drm/drm_eld \
            drm/drm_encoder \
            drm/drm_fourcc \
            drm/drm_framebuffer \
            drm-aros/drm_mm \
            drm/drm_gem \
            drm/drm_mode_config \
            drm/drm_mode_object \
            drm/drm_modes \
            drm/drm_modeset_helper \
            drm/drm_modeset_lock \
            drm/drm_plane \
            drm/drm_plane_helper \
            drm/drm_print \
            drm/drm_probe_helper \
            drm/drm_property \
            drm/drm_rect \
            drm/drm_self_refresh_helper \
            drm/ttm/ttm_bo \
            drm/ttm/ttm_bo_util \
            drm/ttm/ttm_device \
            drm/ttm/ttm_module \
            drm/ttm/ttm_execbuf_util \
            drm/ttm/ttm_range_manager \
            drm/ttm/ttm_resource \
            drm/ttm/ttm_sys_manager \
            drm/ttm/ttm_tt \
            drm-compat/linux_compat \
            drm-compat/linux_dma \
            drm-compat/linux_dma_fence \
            drm-compat/linux_dma_fence_array \
            drm-compat/linux_dma_resv \
            drm-compat/linux_firmware \
            drm-compat/linux_hdmi \
            drm-compat/linux_i2c \
            drm-compat/linux_idr \
            drm-compat/linux_mmio \
            drm-compat/linux_irq \
            drm-compat/linux_mem \
            drm-compat/linux_pci \
            drm-compat/linux_printk \
            drm-compat/linux_sched \
            drm-compat/linux_string \
            drm-compat/linux_time \
            drm-compat/linux_workqueue \
            drm-aros/drm_drv \
            drm-aros/drm_aros_pci \
            drm-aros/drm_stubs \
            drm-aros/ttm_pool_aros \
            drm-compat/linux_kobject \
            drm-compat/linux_dma_fence_unwrap \
            drm/drm_buddy \
            drm/drm_exec \
            drm/drm_suballoc \
            drm/drm_syncobj \
            drm/drm_dumb_buffers \
            drm/display/drm_dsc_helper \
            drm/display/drm_dp_dual_mode_helper \
            drm/scheduler/sched_main \
            drm/scheduler/sched_entity \
            drm/scheduler/sched_fence \
            gpu/buddy \
            drm-compat/linux_radix \

# Linux 6.18.44 drivers/gpu/drm/amd (amdgpu, display, pm) for the default
# configuration, with the AROS glue that stands in for the PCI/module layers.
AROS_AMDGPU_DRM_SOURCES = \
            drm/amd/display/amdgpu_dm/amdgpu_dm \
            drm/amd/display/amdgpu_dm/amdgpu_dm_color \
            drm/amd/display/amdgpu_dm/amdgpu_dm_crtc \
            drm/amd/display/amdgpu_dm/amdgpu_dm_hdcp \
            drm/amd/display/amdgpu_dm/amdgpu_dm_helpers \
            drm/amd/display/amdgpu_dm/amdgpu_dm_irq \
            drm/amd/display/amdgpu_dm/amdgpu_dm_mst_types \
            drm/amd/display/amdgpu_dm/amdgpu_dm_plane \
            drm/amd/display/amdgpu_dm/amdgpu_dm_pp_smu \
            drm/amd/display/amdgpu_dm/amdgpu_dm_psr \
            drm/amd/display/amdgpu_dm/amdgpu_dm_quirks \
            drm/amd/display/amdgpu_dm/amdgpu_dm_replay \
            drm/amd/display/amdgpu_dm/amdgpu_dm_services \
            drm/amd/display/amdgpu_dm/amdgpu_dm_wb \
            drm/amd/display/amdgpu_dm/dc_fpu \
            drm/amd/display/dc/basics/bw_fixed \
            drm/amd/display/dc/basics/conversion \
            drm/amd/display/dc/basics/custom_float \
            drm/amd/display/dc/basics/dc_common \
            drm/amd/display/dc/basics/dce_calcs \
            drm/amd/display/dc/basics/fixpt31_32 \
            drm/amd/display/dc/basics/vector \
            drm/amd/display/dc/bios/bios_parser \
            drm/amd/display/dc/bios/bios_parser2 \
            drm/amd/display/dc/bios/bios_parser_common \
            drm/amd/display/dc/bios/bios_parser_helper \
            drm/amd/display/dc/bios/bios_parser_interface \
            drm/amd/display/dc/bios/command_table \
            drm/amd/display/dc/bios/command_table2 \
            drm/amd/display/dc/bios/command_table_helper \
            drm/amd/display/dc/bios/command_table_helper2 \
            drm/amd/display/dc/bios/dce110/command_table_helper_dce110 \
            drm/amd/display/dc/bios/dce112/command_table_helper2_dce112 \
            drm/amd/display/dc/bios/dce112/command_table_helper_dce112 \
            drm/amd/display/dc/bios/dce80/command_table_helper_dce80 \
            drm/amd/display/dc/clk_mgr/clk_mgr \
            drm/amd/display/dc/clk_mgr/dce100/dce_clk_mgr \
            drm/amd/display/dc/clk_mgr/dce110/dce110_clk_mgr \
            drm/amd/display/dc/clk_mgr/dce112/dce112_clk_mgr \
            drm/amd/display/dc/clk_mgr/dce120/dce120_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn10/rv1_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn10/rv1_clk_mgr_vbios_smu \
            drm/amd/display/dc/clk_mgr/dcn10/rv2_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn20/dcn20_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn201/dcn201_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn21/rn_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn21/rn_clk_mgr_vbios_smu \
            drm/amd/display/dc/clk_mgr/dcn30/dcn30_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn30/dcn30_clk_mgr_smu_msg \
            drm/amd/display/dc/clk_mgr/dcn30/dcn30m_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn30/dcn30m_clk_mgr_smu_msg \
            drm/amd/display/dc/clk_mgr/dcn301/dcn301_smu \
            drm/amd/display/dc/clk_mgr/dcn301/vg_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn31/dcn31_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn31/dcn31_smu \
            drm/amd/display/dc/clk_mgr/dcn314/dcn314_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn314/dcn314_smu \
            drm/amd/display/dc/clk_mgr/dcn315/dcn315_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn315/dcn315_smu \
            drm/amd/display/dc/clk_mgr/dcn316/dcn316_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn316/dcn316_smu \
            drm/amd/display/dc/clk_mgr/dcn32/dcn32_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn32/dcn32_clk_mgr_smu_msg \
            drm/amd/display/dc/clk_mgr/dcn35/dcn351_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn35/dcn35_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn35/dcn35_smu \
            drm/amd/display/dc/clk_mgr/dcn401/dcn401_clk_mgr \
            drm/amd/display/dc/clk_mgr/dcn401/dcn401_clk_mgr_smu_msg \
            drm/amd/display/dc/core/dc \
            drm/amd/display/dc/core/dc_debug \
            drm/amd/display/dc/core/dc_hw_sequencer \
            drm/amd/display/dc/core/dc_link_enc_cfg \
            drm/amd/display/dc/core/dc_link_exports \
            drm/amd/display/dc/core/dc_resource \
            drm/amd/display/dc/core/dc_sink \
            drm/amd/display/dc/core/dc_stat \
            drm/amd/display/dc/core/dc_state \
            drm/amd/display/dc/core/dc_stream \
            drm/amd/display/dc/core/dc_surface \
            drm/amd/display/dc/core/dc_vm_helper \
            drm/amd/display/dc/dc_dmub_srv \
            drm/amd/display/dc/dc_edid_parser \
            drm/amd/display/dc/dc_fused_io \
            drm/amd/display/dc/dc_helper \
            drm/amd/display/dc/dc_spl_translate \
            drm/amd/display/dc/dccg/dcn20/dcn20_dccg \
            drm/amd/display/dc/dccg/dcn201/dcn201_dccg \
            drm/amd/display/dc/dccg/dcn21/dcn21_dccg \
            drm/amd/display/dc/dccg/dcn30/dcn30_dccg \
            drm/amd/display/dc/dccg/dcn301/dcn301_dccg \
            drm/amd/display/dc/dccg/dcn31/dcn31_dccg \
            drm/amd/display/dc/dccg/dcn314/dcn314_dccg \
            drm/amd/display/dc/dccg/dcn32/dcn32_dccg \
            drm/amd/display/dc/dccg/dcn35/dcn35_dccg \
            drm/amd/display/dc/dccg/dcn401/dcn401_dccg \
            drm/amd/display/dc/dce/dce_abm \
            drm/amd/display/dc/dce/dce_audio \
            drm/amd/display/dc/dce/dce_aux \
            drm/amd/display/dc/dce/dce_clock_source \
            drm/amd/display/dc/dce/dce_dmcu \
            drm/amd/display/dc/dce/dce_i2c \
            drm/amd/display/dc/dce/dce_i2c_hw \
            drm/amd/display/dc/dce/dce_i2c_sw \
            drm/amd/display/dc/dce/dce_ipp \
            drm/amd/display/dc/dce/dce_link_encoder \
            drm/amd/display/dc/dce/dce_mem_input \
            drm/amd/display/dc/dce/dce_opp \
            drm/amd/display/dc/dce/dce_panel_cntl \
            drm/amd/display/dc/dce/dce_scl_filters \
            drm/amd/display/dc/dce/dce_stream_encoder \
            drm/amd/display/dc/dce/dce_transform \
            drm/amd/display/dc/dce/dmub_abm \
            drm/amd/display/dc/dce/dmub_abm_lcd \
            drm/amd/display/dc/dce/dmub_hw_lock_mgr \
            drm/amd/display/dc/dce/dmub_outbox \
            drm/amd/display/dc/dce/dmub_psr \
            drm/amd/display/dc/dce/dmub_replay \
            drm/amd/display/dc/dce110/dce110_compressor \
            drm/amd/display/dc/dce110/dce110_mem_input_v \
            drm/amd/display/dc/dce110/dce110_opp_csc_v \
            drm/amd/display/dc/dce110/dce110_opp_regamma_v \
            drm/amd/display/dc/dce110/dce110_opp_v \
            drm/amd/display/dc/dce110/dce110_timing_generator \
            drm/amd/display/dc/dce110/dce110_timing_generator_v \
            drm/amd/display/dc/dce110/dce110_transform_v \
            drm/amd/display/dc/dce112/dce112_compressor \
            drm/amd/display/dc/dce120/dce120_timing_generator \
            drm/amd/display/dc/dce80/dce80_timing_generator \
            drm/amd/display/dc/dcn10/dcn10_cm_common \
            drm/amd/display/dc/dcn10/dcn10_hw_sequencer_debug \
            drm/amd/display/dc/dcn10/dcn10_ipp \
            drm/amd/display/dc/dcn20/dcn20_dwb \
            drm/amd/display/dc/dcn20/dcn20_dwb_scl \
            drm/amd/display/dc/dcn20/dcn20_vmid \
            drm/amd/display/dc/dcn201/dcn201_link_encoder \
            drm/amd/display/dc/dcn201/dcn201_mpc \
            drm/amd/display/dc/dcn201/dcn201_opp \
            drm/amd/display/dc/dcn21/dcn21_link_encoder \
            drm/amd/display/dc/dcn30/dcn30_afmt \
            drm/amd/display/dc/dcn30/dcn30_cm_common \
            drm/amd/display/dc/dcn30/dcn30_mmhubbub \
            drm/amd/display/dc/dcn30/dcn30_vpg \
            drm/amd/display/dc/dcn301/dcn301_panel_cntl \
            drm/amd/display/dc/dcn31/dcn31_afmt \
            drm/amd/display/dc/dcn31/dcn31_apg \
            drm/amd/display/dc/dcn31/dcn31_panel_cntl \
            drm/amd/display/dc/dcn31/dcn31_vpg \
            drm/amd/display/dc/dio/dcn10/dcn10_link_encoder \
            drm/amd/display/dc/dio/dcn10/dcn10_stream_encoder \
            drm/amd/display/dc/dio/dcn20/dcn20_link_encoder \
            drm/amd/display/dc/dio/dcn20/dcn20_stream_encoder \
            drm/amd/display/dc/dio/dcn30/dcn30_dio_link_encoder \
            drm/amd/display/dc/dio/dcn30/dcn30_dio_stream_encoder \
            drm/amd/display/dc/dio/dcn301/dcn301_dio_link_encoder \
            drm/amd/display/dc/dio/dcn31/dcn31_dio_link_encoder \
            drm/amd/display/dc/dio/dcn314/dcn314_dio_stream_encoder \
            drm/amd/display/dc/dio/dcn32/dcn32_dio_link_encoder \
            drm/amd/display/dc/dio/dcn32/dcn32_dio_stream_encoder \
            drm/amd/display/dc/dio/dcn321/dcn321_dio_link_encoder \
            drm/amd/display/dc/dio/dcn35/dcn35_dio_link_encoder \
            drm/amd/display/dc/dio/dcn35/dcn35_dio_stream_encoder \
            drm/amd/display/dc/dio/dcn401/dcn401_dio_link_encoder \
            drm/amd/display/dc/dio/dcn401/dcn401_dio_stream_encoder \
            drm/amd/display/dc/dml/calcs/dcn_calc_auto \
            drm/amd/display/dc/dml/calcs/dcn_calc_math \
            drm/amd/display/dc/dml/calcs/dcn_calcs \
            drm/amd/display/dc/dml/dcn10/dcn10_fpu \
            drm/amd/display/dc/dml/dcn20/dcn20_fpu \
            drm/amd/display/dc/dml/dcn20/display_mode_vba_20 \
            drm/amd/display/dc/dml/dcn20/display_mode_vba_20v2 \
            drm/amd/display/dc/dml/dcn20/display_rq_dlg_calc_20 \
            drm/amd/display/dc/dml/dcn20/display_rq_dlg_calc_20v2 \
            drm/amd/display/dc/dml/dcn21/display_mode_vba_21 \
            drm/amd/display/dc/dml/dcn21/display_rq_dlg_calc_21 \
            drm/amd/display/dc/dml/dcn30/dcn30_fpu \
            drm/amd/display/dc/dml/dcn30/display_mode_vba_30 \
            drm/amd/display/dc/dml/dcn30/display_rq_dlg_calc_30 \
            drm/amd/display/dc/dml/dcn301/dcn301_fpu \
            drm/amd/display/dc/dml/dcn302/dcn302_fpu \
            drm/amd/display/dc/dml/dcn303/dcn303_fpu \
            drm/amd/display/dc/dml/dcn31/dcn31_fpu \
            drm/amd/display/dc/dml/dcn31/display_mode_vba_31 \
            drm/amd/display/dc/dml/dcn31/display_rq_dlg_calc_31 \
            drm/amd/display/dc/dml/dcn314/dcn314_fpu \
            drm/amd/display/dc/dml/dcn314/display_mode_vba_314 \
            drm/amd/display/dc/dml/dcn314/display_rq_dlg_calc_314 \
            drm/amd/display/dc/dml/dcn32/dcn32_fpu \
            drm/amd/display/dc/dml/dcn32/display_mode_vba_32 \
            drm/amd/display/dc/dml/dcn32/display_mode_vba_util_32 \
            drm/amd/display/dc/dml/dcn32/display_rq_dlg_calc_32 \
            drm/amd/display/dc/dml/dcn321/dcn321_fpu \
            drm/amd/display/dc/dml/dcn35/dcn35_fpu \
            drm/amd/display/dc/dml/dcn351/dcn351_fpu \
            drm/amd/display/dc/dml/display_mode_lib \
            drm/amd/display/dc/dml/display_mode_vba \
            drm/amd/display/dc/dml/display_rq_dlg_helpers \
            drm/amd/display/dc/dml/dml1_display_rq_dlg_calc \
            drm/amd/display/dc/dml/dsc/rc_calc_fpu \
            drm/amd/display/dc/dml2/display_mode_core \
            drm/amd/display/dc/dml2/display_mode_util \
            drm/amd/display/dc/dml2/dml21/dml21_translation_helper \
            drm/amd/display/dc/dml2/dml21/dml21_utils \
            drm/amd/display/dc/dml2/dml21/dml21_wrapper \
            drm/amd/display/dc/dml2/dml21/src/dml2_core/dml2_core_dcn4 \
            drm/amd/display/dc/dml2/dml21/src/dml2_core/dml2_core_dcn4_calcs \
            drm/amd/display/dc/dml2/dml21/src/dml2_core/dml2_core_factory \
            drm/amd/display/dc/dml2/dml21/src/dml2_core/dml2_core_utils \
            drm/amd/display/dc/dml2/dml21/src/dml2_dpmm/dml2_dpmm_dcn4 \
            drm/amd/display/dc/dml2/dml21/src/dml2_dpmm/dml2_dpmm_factory \
            drm/amd/display/dc/dml2/dml21/src/dml2_mcg/dml2_mcg_dcn4 \
            drm/amd/display/dc/dml2/dml21/src/dml2_mcg/dml2_mcg_factory \
            drm/amd/display/dc/dml2/dml21/src/dml2_pmo/dml2_pmo_dcn3 \
            drm/amd/display/dc/dml2/dml21/src/dml2_pmo/dml2_pmo_dcn4_fams2 \
            drm/amd/display/dc/dml2/dml21/src/dml2_pmo/dml2_pmo_factory \
            drm/amd/display/dc/dml2/dml21/src/dml2_standalone_libraries/lib_float_math \
            drm/amd/display/dc/dml2/dml21/src/dml2_top/dml2_top_interfaces \
            drm/amd/display/dc/dml2/dml21/src/dml2_top/dml2_top_soc15 \
            drm/amd/display/dc/dml2/dml2_dc_resource_mgmt \
            drm/amd/display/dc/dml2/dml2_mall_phantom \
            drm/amd/display/dc/dml2/dml2_policy \
            drm/amd/display/dc/dml2/dml2_translation_helper \
            drm/amd/display/dc/dml2/dml2_utils \
            drm/amd/display/dc/dml2/dml2_wrapper \
            drm/amd/display/dc/dml2/dml_display_rq_dlg_calc \
            drm/amd/display/dc/dpp/dcn10/dcn10_dpp \
            drm/amd/display/dc/dpp/dcn10/dcn10_dpp_cm \
            drm/amd/display/dc/dpp/dcn10/dcn10_dpp_dscl \
            drm/amd/display/dc/dpp/dcn20/dcn20_dpp \
            drm/amd/display/dc/dpp/dcn20/dcn20_dpp_cm \
            drm/amd/display/dc/dpp/dcn201/dcn201_dpp \
            drm/amd/display/dc/dpp/dcn30/dcn30_dpp \
            drm/amd/display/dc/dpp/dcn30/dcn30_dpp_cm \
            drm/amd/display/dc/dpp/dcn32/dcn32_dpp \
            drm/amd/display/dc/dpp/dcn35/dcn35_dpp \
            drm/amd/display/dc/dpp/dcn401/dcn401_dpp \
            drm/amd/display/dc/dpp/dcn401/dcn401_dpp_cm \
            drm/amd/display/dc/dpp/dcn401/dcn401_dpp_dscl \
            drm/amd/display/dc/dsc/dc_dsc \
            drm/amd/display/dc/dsc/dcn20/dcn20_dsc \
            drm/amd/display/dc/dsc/dcn35/dcn35_dsc \
            drm/amd/display/dc/dsc/dcn401/dcn401_dsc \
            drm/amd/display/dc/dsc/rc_calc \
            drm/amd/display/dc/dsc/rc_calc_dpi \
            drm/amd/display/dc/dwb/dcn30/dcn30_dwb \
            drm/amd/display/dc/dwb/dcn30/dcn30_dwb_cm \
            drm/amd/display/dc/dwb/dcn35/dcn35_dwb \
            drm/amd/display/dc/gpio/dce110/hw_factory_dce110 \
            drm/amd/display/dc/gpio/dce110/hw_translate_dce110 \
            drm/amd/display/dc/gpio/dce120/hw_factory_dce120 \
            drm/amd/display/dc/gpio/dce120/hw_translate_dce120 \
            drm/amd/display/dc/gpio/dce80/hw_factory_dce80 \
            drm/amd/display/dc/gpio/dce80/hw_translate_dce80 \
            drm/amd/display/dc/gpio/dcn10/hw_factory_dcn10 \
            drm/amd/display/dc/gpio/dcn10/hw_translate_dcn10 \
            drm/amd/display/dc/gpio/dcn20/hw_factory_dcn20 \
            drm/amd/display/dc/gpio/dcn20/hw_translate_dcn20 \
            drm/amd/display/dc/gpio/dcn21/hw_factory_dcn21 \
            drm/amd/display/dc/gpio/dcn21/hw_translate_dcn21 \
            drm/amd/display/dc/gpio/dcn30/hw_factory_dcn30 \
            drm/amd/display/dc/gpio/dcn30/hw_translate_dcn30 \
            drm/amd/display/dc/gpio/dcn315/hw_factory_dcn315 \
            drm/amd/display/dc/gpio/dcn315/hw_translate_dcn315 \
            drm/amd/display/dc/gpio/dcn32/hw_factory_dcn32 \
            drm/amd/display/dc/gpio/dcn32/hw_translate_dcn32 \
            drm/amd/display/dc/gpio/dcn401/hw_factory_dcn401 \
            drm/amd/display/dc/gpio/dcn401/hw_translate_dcn401 \
            drm/amd/display/dc/gpio/gpio_base \
            drm/amd/display/dc/gpio/gpio_service \
            drm/amd/display/dc/gpio/hw_ddc \
            drm/amd/display/dc/gpio/hw_factory \
            drm/amd/display/dc/gpio/hw_generic \
            drm/amd/display/dc/gpio/hw_gpio \
            drm/amd/display/dc/gpio/hw_hpd \
            drm/amd/display/dc/gpio/hw_translate \
            drm/amd/display/dc/hdcp/hdcp_msg \
            drm/amd/display/dc/hpo/dcn31/dcn31_hpo_dp_link_encoder \
            drm/amd/display/dc/hpo/dcn31/dcn31_hpo_dp_stream_encoder \
            drm/amd/display/dc/hpo/dcn32/dcn32_hpo_dp_link_encoder \
            drm/amd/display/dc/hubbub/dcn10/dcn10_hubbub \
            drm/amd/display/dc/hubbub/dcn20/dcn20_hubbub \
            drm/amd/display/dc/hubbub/dcn201/dcn201_hubbub \
            drm/amd/display/dc/hubbub/dcn21/dcn21_hubbub \
            drm/amd/display/dc/hubbub/dcn30/dcn30_hubbub \
            drm/amd/display/dc/hubbub/dcn301/dcn301_hubbub \
            drm/amd/display/dc/hubbub/dcn31/dcn31_hubbub \
            drm/amd/display/dc/hubbub/dcn32/dcn32_hubbub \
            drm/amd/display/dc/hubbub/dcn35/dcn35_hubbub \
            drm/amd/display/dc/hubbub/dcn401/dcn401_hubbub \
            drm/amd/display/dc/hubp/dcn10/dcn10_hubp \
            drm/amd/display/dc/hubp/dcn20/dcn20_hubp \
            drm/amd/display/dc/hubp/dcn201/dcn201_hubp \
            drm/amd/display/dc/hubp/dcn21/dcn21_hubp \
            drm/amd/display/dc/hubp/dcn30/dcn30_hubp \
            drm/amd/display/dc/hubp/dcn31/dcn31_hubp \
            drm/amd/display/dc/hubp/dcn32/dcn32_hubp \
            drm/amd/display/dc/hubp/dcn35/dcn35_hubp \
            drm/amd/display/dc/hubp/dcn401/dcn401_hubp \
            drm/amd/display/dc/hwss/dce/dce_hwseq \
            drm/amd/display/dc/hwss/dce100/dce100_hwseq \
            drm/amd/display/dc/hwss/dce110/dce110_hwseq \
            drm/amd/display/dc/hwss/dce112/dce112_hwseq \
            drm/amd/display/dc/hwss/dce120/dce120_hwseq \
            drm/amd/display/dc/hwss/dce80/dce80_hwseq \
            drm/amd/display/dc/hwss/dcn10/dcn10_hwseq \
            drm/amd/display/dc/hwss/dcn10/dcn10_init \
            drm/amd/display/dc/hwss/dcn20/dcn20_hwseq \
            drm/amd/display/dc/hwss/dcn20/dcn20_init \
            drm/amd/display/dc/hwss/dcn201/dcn201_hwseq \
            drm/amd/display/dc/hwss/dcn201/dcn201_init \
            drm/amd/display/dc/hwss/dcn21/dcn21_hwseq \
            drm/amd/display/dc/hwss/dcn21/dcn21_init \
            drm/amd/display/dc/hwss/dcn30/dcn30_hwseq \
            drm/amd/display/dc/hwss/dcn30/dcn30_init \
            drm/amd/display/dc/hwss/dcn301/dcn301_hwseq \
            drm/amd/display/dc/hwss/dcn301/dcn301_init \
            drm/amd/display/dc/hwss/dcn302/dcn302_hwseq \
            drm/amd/display/dc/hwss/dcn302/dcn302_init \
            drm/amd/display/dc/hwss/dcn303/dcn303_hwseq \
            drm/amd/display/dc/hwss/dcn303/dcn303_init \
            drm/amd/display/dc/hwss/dcn31/dcn31_hwseq \
            drm/amd/display/dc/hwss/dcn31/dcn31_init \
            drm/amd/display/dc/hwss/dcn314/dcn314_hwseq \
            drm/amd/display/dc/hwss/dcn314/dcn314_init \
            drm/amd/display/dc/hwss/dcn32/dcn32_hwseq \
            drm/amd/display/dc/hwss/dcn32/dcn32_init \
            drm/amd/display/dc/hwss/dcn35/dcn35_hwseq \
            drm/amd/display/dc/hwss/dcn35/dcn35_init \
            drm/amd/display/dc/hwss/dcn351/dcn351_hwseq \
            drm/amd/display/dc/hwss/dcn351/dcn351_init \
            drm/amd/display/dc/hwss/dcn401/dcn401_hwseq \
            drm/amd/display/dc/hwss/dcn401/dcn401_init \
            drm/amd/display/dc/irq/dce110/irq_service_dce110 \
            drm/amd/display/dc/irq/dce120/irq_service_dce120 \
            drm/amd/display/dc/irq/dce80/irq_service_dce80 \
            drm/amd/display/dc/irq/dcn10/irq_service_dcn10 \
            drm/amd/display/dc/irq/dcn20/irq_service_dcn20 \
            drm/amd/display/dc/irq/dcn201/irq_service_dcn201 \
            drm/amd/display/dc/irq/dcn21/irq_service_dcn21 \
            drm/amd/display/dc/irq/dcn30/irq_service_dcn30 \
            drm/amd/display/dc/irq/dcn302/irq_service_dcn302 \
            drm/amd/display/dc/irq/dcn303/irq_service_dcn303 \
            drm/amd/display/dc/irq/dcn31/irq_service_dcn31 \
            drm/amd/display/dc/irq/dcn314/irq_service_dcn314 \
            drm/amd/display/dc/irq/dcn315/irq_service_dcn315 \
            drm/amd/display/dc/irq/dcn32/irq_service_dcn32 \
            drm/amd/display/dc/irq/dcn35/irq_service_dcn35 \
            drm/amd/display/dc/irq/dcn351/irq_service_dcn351 \
            drm/amd/display/dc/irq/dcn36/irq_service_dcn36 \
            drm/amd/display/dc/irq/dcn401/irq_service_dcn401 \
            drm/amd/display/dc/irq/irq_service \
            drm/amd/display/dc/link/accessories/link_dp_cts \
            drm/amd/display/dc/link/accessories/link_dp_trace \
            drm/amd/display/dc/link/hwss/link_hwss_dio \
            drm/amd/display/dc/link/hwss/link_hwss_dio_fixed_vs_pe_retimer \
            drm/amd/display/dc/link/hwss/link_hwss_dpia \
            drm/amd/display/dc/link/hwss/link_hwss_hpo_dp \
            drm/amd/display/dc/link/hwss/link_hwss_hpo_fixed_vs_pe_retimer_dp \
            drm/amd/display/dc/link/link_detection \
            drm/amd/display/dc/link/link_dpms \
            drm/amd/display/dc/link/link_factory \
            drm/amd/display/dc/link/link_resource \
            drm/amd/display/dc/link/link_validation \
            drm/amd/display/dc/link/protocols/link_ddc \
            drm/amd/display/dc/link/protocols/link_dp_capability \
            drm/amd/display/dc/link/protocols/link_dp_dpia \
            drm/amd/display/dc/link/protocols/link_dp_dpia_bw \
            drm/amd/display/dc/link/protocols/link_dp_irq_handler \
            drm/amd/display/dc/link/protocols/link_dp_phy \
            drm/amd/display/dc/link/protocols/link_dp_training \
            drm/amd/display/dc/link/protocols/link_dp_training_128b_132b \
            drm/amd/display/dc/link/protocols/link_dp_training_8b_10b \
            drm/amd/display/dc/link/protocols/link_dp_training_auxless \
            drm/amd/display/dc/link/protocols/link_dp_training_dpia \
            drm/amd/display/dc/link/protocols/link_dp_training_fixed_vs_pe_retimer \
            drm/amd/display/dc/link/protocols/link_dpcd \
            drm/amd/display/dc/link/protocols/link_edp_panel_control \
            drm/amd/display/dc/link/protocols/link_hpd \
            drm/amd/display/dc/mmhubbub/dcn20/dcn20_mmhubbub \
            drm/amd/display/dc/mmhubbub/dcn32/dcn32_mmhubbub \
            drm/amd/display/dc/mmhubbub/dcn35/dcn35_mmhubbub \
            drm/amd/display/dc/mpc/dcn10/dcn10_mpc \
            drm/amd/display/dc/mpc/dcn20/dcn20_mpc \
            drm/amd/display/dc/mpc/dcn30/dcn30_mpc \
            drm/amd/display/dc/mpc/dcn32/dcn32_mpc \
            drm/amd/display/dc/mpc/dcn401/dcn401_mpc \
            drm/amd/display/dc/opp/dcn10/dcn10_opp \
            drm/amd/display/dc/opp/dcn20/dcn20_opp \
            drm/amd/display/dc/opp/dcn35/dcn35_opp \
            drm/amd/display/dc/optc/dcn10/dcn10_optc \
            drm/amd/display/dc/optc/dcn20/dcn20_optc \
            drm/amd/display/dc/optc/dcn201/dcn201_optc \
            drm/amd/display/dc/optc/dcn30/dcn30_optc \
            drm/amd/display/dc/optc/dcn301/dcn301_optc \
            drm/amd/display/dc/optc/dcn31/dcn31_optc \
            drm/amd/display/dc/optc/dcn314/dcn314_optc \
            drm/amd/display/dc/optc/dcn32/dcn32_optc \
            drm/amd/display/dc/optc/dcn35/dcn35_optc \
            drm/amd/display/dc/optc/dcn401/dcn401_optc \
            drm/amd/display/dc/pg/dcn35/dcn35_pg_cntl \
            drm/amd/display/dc/resource/dce100/dce100_resource \
            drm/amd/display/dc/resource/dce110/dce110_resource \
            drm/amd/display/dc/resource/dce112/dce112_resource \
            drm/amd/display/dc/resource/dce120/dce120_resource \
            drm/amd/display/dc/resource/dce80/dce80_resource \
            drm/amd/display/dc/resource/dcn10/dcn10_resource \
            drm/amd/display/dc/resource/dcn20/dcn20_resource \
            drm/amd/display/dc/resource/dcn201/dcn201_resource \
            drm/amd/display/dc/resource/dcn21/dcn21_resource \
            drm/amd/display/dc/resource/dcn30/dcn30_resource \
            drm/amd/display/dc/resource/dcn301/dcn301_resource \
            drm/amd/display/dc/resource/dcn302/dcn302_resource \
            drm/amd/display/dc/resource/dcn303/dcn303_resource \
            drm/amd/display/dc/resource/dcn31/dcn31_resource \
            drm/amd/display/dc/resource/dcn314/dcn314_resource \
            drm/amd/display/dc/resource/dcn315/dcn315_resource \
            drm/amd/display/dc/resource/dcn316/dcn316_resource \
            drm/amd/display/dc/resource/dcn32/dcn32_resource \
            drm/amd/display/dc/resource/dcn32/dcn32_resource_helpers \
            drm/amd/display/dc/resource/dcn321/dcn321_resource \
            drm/amd/display/dc/resource/dcn35/dcn35_resource \
            drm/amd/display/dc/resource/dcn351/dcn351_resource \
            drm/amd/display/dc/resource/dcn36/dcn36_resource \
            drm/amd/display/dc/resource/dcn401/dcn401_resource \
            drm/amd/display/dc/soc_and_ip_translator/dcn401/dcn401_soc_and_ip_translator \
            drm/amd/display/dc/soc_and_ip_translator/soc_and_ip_translator \
            drm/amd/display/dc/sspl/dc_spl \
            drm/amd/display/dc/sspl/dc_spl_filters \
            drm/amd/display/dc/sspl/dc_spl_isharp_filters \
            drm/amd/display/dc/sspl/dc_spl_scl_easf_filters \
            drm/amd/display/dc/sspl/dc_spl_scl_filters \
            drm/amd/display/dc/sspl/spl_custom_float \
            drm/amd/display/dc/sspl/spl_fixpt31_32 \
            drm/amd/display/dc/virtual/virtual_link_encoder \
            drm/amd/display/dc/virtual/virtual_link_hwss \
            drm/amd/display/dc/virtual/virtual_stream_encoder \
            drm/amd/display/dmub/src/dmub_dcn20 \
            drm/amd/display/dmub/src/dmub_dcn21 \
            drm/amd/display/dmub/src/dmub_dcn30 \
            drm/amd/display/dmub/src/dmub_dcn301 \
            drm/amd/display/dmub/src/dmub_dcn302 \
            drm/amd/display/dmub/src/dmub_dcn303 \
            drm/amd/display/dmub/src/dmub_dcn31 \
            drm/amd/display/dmub/src/dmub_dcn314 \
            drm/amd/display/dmub/src/dmub_dcn315 \
            drm/amd/display/dmub/src/dmub_dcn316 \
            drm/amd/display/dmub/src/dmub_dcn32 \
            drm/amd/display/dmub/src/dmub_dcn35 \
            drm/amd/display/dmub/src/dmub_dcn351 \
            drm/amd/display/dmub/src/dmub_dcn36 \
            drm/amd/display/dmub/src/dmub_dcn401 \
            drm/amd/display/dmub/src/dmub_reg \
            drm/amd/display/dmub/src/dmub_srv \
            drm/amd/display/dmub/src/dmub_srv_stat \
            drm/amd/display/modules/color/color_gamma \
            drm/amd/display/modules/color/color_table \
            drm/amd/display/modules/freesync/freesync \
            drm/amd/display/modules/hdcp/hdcp \
            drm/amd/display/modules/hdcp/hdcp1_execution \
            drm/amd/display/modules/hdcp/hdcp1_transition \
            drm/amd/display/modules/hdcp/hdcp2_execution \
            drm/amd/display/modules/hdcp/hdcp2_transition \
            drm/amd/display/modules/hdcp/hdcp_ddc \
            drm/amd/display/modules/hdcp/hdcp_log \
            drm/amd/display/modules/hdcp/hdcp_psp \
            drm/amd/display/modules/info_packet/info_packet \
            drm/amd/display/modules/power/power_helpers \
            drm/amd/pm/amdgpu_dpm \
            drm/amd/pm/amdgpu_dpm_internal \
            drm/amd/pm/amdgpu_pm \
            drm/amd/pm/legacy-dpm/legacy_dpm \
            drm/amd/pm/powerplay/amd_powerplay \
            drm/amd/pm/powerplay/hwmgr/ci_baco \
            drm/amd/pm/powerplay/hwmgr/common_baco \
            drm/amd/pm/powerplay/hwmgr/fiji_baco \
            drm/amd/pm/powerplay/hwmgr/hardwaremanager \
            drm/amd/pm/powerplay/hwmgr/hwmgr \
            drm/amd/pm/powerplay/hwmgr/polaris_baco \
            drm/amd/pm/powerplay/hwmgr/pp_overdriver \
            drm/amd/pm/powerplay/hwmgr/pp_psm \
            drm/amd/pm/powerplay/hwmgr/ppatomctrl \
            drm/amd/pm/powerplay/hwmgr/ppatomfwctrl \
            drm/amd/pm/powerplay/hwmgr/pppcielanes \
            drm/amd/pm/powerplay/hwmgr/process_pptables_v1_0 \
            drm/amd/pm/powerplay/hwmgr/processpptables \
            drm/amd/pm/powerplay/hwmgr/smu10_hwmgr \
            drm/amd/pm/powerplay/hwmgr/smu7_baco \
            drm/amd/pm/powerplay/hwmgr/smu7_clockpowergating \
            drm/amd/pm/powerplay/hwmgr/smu7_hwmgr \
            drm/amd/pm/powerplay/hwmgr/smu7_powertune \
            drm/amd/pm/powerplay/hwmgr/smu7_thermal \
            drm/amd/pm/powerplay/hwmgr/smu8_hwmgr \
            drm/amd/pm/powerplay/hwmgr/smu9_baco \
            drm/amd/pm/powerplay/hwmgr/smu_helper \
            drm/amd/pm/powerplay/hwmgr/tonga_baco \
            drm/amd/pm/powerplay/hwmgr/vega10_baco \
            drm/amd/pm/powerplay/hwmgr/vega10_hwmgr \
            drm/amd/pm/powerplay/hwmgr/vega10_powertune \
            drm/amd/pm/powerplay/hwmgr/vega10_processpptables \
            drm/amd/pm/powerplay/hwmgr/vega10_thermal \
            drm/amd/pm/powerplay/hwmgr/vega12_baco \
            drm/amd/pm/powerplay/hwmgr/vega12_hwmgr \
            drm/amd/pm/powerplay/hwmgr/vega12_processpptables \
            drm/amd/pm/powerplay/hwmgr/vega12_thermal \
            drm/amd/pm/powerplay/hwmgr/vega20_baco \
            drm/amd/pm/powerplay/hwmgr/vega20_hwmgr \
            drm/amd/pm/powerplay/hwmgr/vega20_powertune \
            drm/amd/pm/powerplay/hwmgr/vega20_processpptables \
            drm/amd/pm/powerplay/hwmgr/vega20_thermal \
            drm/amd/pm/powerplay/smumgr/ci_smumgr \
            drm/amd/pm/powerplay/smumgr/fiji_smumgr \
            drm/amd/pm/powerplay/smumgr/iceland_smumgr \
            drm/amd/pm/powerplay/smumgr/polaris10_smumgr \
            drm/amd/pm/powerplay/smumgr/smu10_smumgr \
            drm/amd/pm/powerplay/smumgr/smu7_smumgr \
            drm/amd/pm/powerplay/smumgr/smu8_smumgr \
            drm/amd/pm/powerplay/smumgr/smu9_smumgr \
            drm/amd/pm/powerplay/smumgr/smumgr \
            drm/amd/pm/powerplay/smumgr/tonga_smumgr \
            drm/amd/pm/powerplay/smumgr/vega10_smumgr \
            drm/amd/pm/powerplay/smumgr/vega12_smumgr \
            drm/amd/pm/powerplay/smumgr/vega20_smumgr \
            drm/amd/pm/powerplay/smumgr/vegam_smumgr \
            drm/amd/pm/swsmu/amdgpu_smu \
            drm/amd/pm/swsmu/smu11/arcturus_ppt \
            drm/amd/pm/swsmu/smu11/cyan_skillfish_ppt \
            drm/amd/pm/swsmu/smu11/navi10_ppt \
            drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt \
            drm/amd/pm/swsmu/smu11/smu_v11_0 \
            drm/amd/pm/swsmu/smu11/vangogh_ppt \
            drm/amd/pm/swsmu/smu12/renoir_ppt \
            drm/amd/pm/swsmu/smu12/smu_v12_0 \
            drm/amd/pm/swsmu/smu13/aldebaran_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0 \
            drm/amd/pm/swsmu/smu13/smu_v13_0_0_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0_12_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0_4_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0_5_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0_6_ppt \
            drm/amd/pm/swsmu/smu13/smu_v13_0_7_ppt \
            drm/amd/pm/swsmu/smu13/yellow_carp_ppt \
            drm/amd/pm/swsmu/smu14/smu_v14_0 \
            drm/amd/pm/swsmu/smu14/smu_v14_0_0_ppt \
            drm/amd/pm/swsmu/smu14/smu_v14_0_2_ppt \
            drm/amd/pm/swsmu/smu_cmn \
            drm/amd/amdgpu/aldebaran \
            drm/amd/amdgpu/aldebaran_reg_init \
            drm/amd/amdgpu/amdgpu_aca \
            drm/amd/amdgpu/amdgpu_afmt \
            drm/amd/amdgpu/amdgpu_amdkfd \
            drm/amd/amdgpu/amdgpu_atombios \
            drm/amd/amdgpu/amdgpu_atomfirmware \
            drm/amd/amdgpu/amdgpu_benchmark \
            drm/amd/amdgpu/amdgpu_bios \
            drm/amd/amdgpu/amdgpu_bo_list \
            drm/amd/amdgpu/amdgpu_cgs \
            drm/amd/amdgpu/amdgpu_connectors \
            drm/amd/amdgpu/amdgpu_cper \
            drm/amd/amdgpu/amdgpu_cs \
            drm/amd/amdgpu/amdgpu_csa \
            drm/amd/amdgpu/amdgpu_ctx \
            drm/amd/amdgpu/amdgpu_debugfs \
            drm/amd/amdgpu/amdgpu_dev_coredump \
            drm/amd/amdgpu/amdgpu_device \
            drm/amd/amdgpu/amdgpu_discovery \
            drm/amd/amdgpu/amdgpu_display \
            drm/amd/amdgpu/amdgpu_dma_buf \
            drm/amd/amdgpu/amdgpu_doorbell_mgr \
            drm/amd/amdgpu/amdgpu_drv \
            drm/amd/amdgpu/amdgpu_eeprom \
            drm/amd/amdgpu/amdgpu_encoders \
            drm/amd/amdgpu/amdgpu_eviction_fence \
            drm/amd/amdgpu/amdgpu_fence \
            drm/amd/amdgpu/amdgpu_fru_eeprom \
            drm/amd/amdgpu/amdgpu_fw_attestation \
            drm/amd/amdgpu/amdgpu_gart \
            drm/amd/amdgpu/amdgpu_gem \
            drm/amd/amdgpu/amdgpu_gfx \
            drm/amd/amdgpu/amdgpu_gmc \
            drm/amd/amdgpu/amdgpu_gtt_mgr \
            drm/amd/amdgpu/amdgpu_hdp \
            drm/amd/amdgpu/amdgpu_i2c \
            drm/amd/amdgpu/amdgpu_ib \
            drm/amd/amdgpu/amdgpu_ids \
            drm/amd/amdgpu/amdgpu_ih \
            drm/amd/amdgpu/amdgpu_ip \
            drm/amd/amdgpu/amdgpu_irq \
            drm/amd/amdgpu/amdgpu_job \
            drm/amd/amdgpu/amdgpu_jpeg \
            drm/amd/amdgpu/amdgpu_kms \
            drm/amd/amdgpu/amdgpu_lsdma \
            drm/amd/amdgpu/amdgpu_mca \
            drm/amd/amdgpu/amdgpu_mes \
            drm/amd/amdgpu/amdgpu_mmhub \
            drm/amd/amdgpu/amdgpu_nbio \
            drm/amd/amdgpu/amdgpu_object \
            drm/amd/amdgpu/amdgpu_pll \
            drm/amd/amdgpu/amdgpu_preempt_mgr \
            drm/amd/amdgpu/amdgpu_psp \
            drm/amd/amdgpu/amdgpu_psp_ta \
            drm/amd/amdgpu/amdgpu_rap \
            drm/amd/amdgpu/amdgpu_ras \
            drm/amd/amdgpu/amdgpu_ras_eeprom \
            drm/amd/amdgpu/amdgpu_reset \
            drm/amd/amdgpu/amdgpu_ring \
            drm/amd/amdgpu/amdgpu_ring_mux \
            drm/amd/amdgpu/amdgpu_rlc \
            drm/amd/amdgpu/amdgpu_sa \
            drm/amd/amdgpu/amdgpu_sched \
            drm/amd/amdgpu/amdgpu_sdma \
            drm/amd/amdgpu/amdgpu_securedisplay \
            drm/amd/amdgpu/amdgpu_seq64 \
            drm/amd/amdgpu/amdgpu_sync \
            drm/amd/amdgpu/amdgpu_trace_points \
            drm/amd/amdgpu/amdgpu_ttm \
            drm/amd/amdgpu/amdgpu_ucode \
            drm/amd/amdgpu/amdgpu_umc \
            drm/amd/amdgpu/amdgpu_umsch_mm \
            drm/amd/amdgpu/amdgpu_userq \
            drm/amd/amdgpu/amdgpu_userq_fence \
            drm/amd/amdgpu/amdgpu_uvd \
            drm/amd/amdgpu/amdgpu_vce \
            drm/amd/amdgpu/amdgpu_vcn \
            drm/amd/amdgpu/amdgpu_vf_error \
            drm/amd/amdgpu/amdgpu_virt \
            drm/amd/amdgpu/amdgpu_vm \
            drm/amd/amdgpu/amdgpu_vm_cpu \
            drm/amd/amdgpu/amdgpu_vm_pt \
            drm/amd/amdgpu/amdgpu_vm_sdma \
            drm/amd/amdgpu/amdgpu_vm_tlb_fence \
            drm/amd/amdgpu/amdgpu_vpe \
            drm/amd/amdgpu/amdgpu_vram_mgr \
            drm/amd/amdgpu/amdgpu_xcp \
            drm/amd/amdgpu/amdgpu_xgmi \
            drm/amd/amdgpu/aqua_vanjaram \
            drm/amd/amdgpu/arct_reg_init \
            drm/amd/amdgpu/athub_v1_0 \
            drm/amd/amdgpu/athub_v2_0 \
            drm/amd/amdgpu/athub_v2_1 \
            drm/amd/amdgpu/athub_v3_0 \
            drm/amd/amdgpu/athub_v4_1_0 \
            drm/amd/amdgpu/atom \
            drm/amd/amdgpu/atombios_crtc \
            drm/amd/amdgpu/atombios_dp \
            drm/amd/amdgpu/atombios_encoders \
            drm/amd/amdgpu/atombios_i2c \
            drm/amd/amdgpu/cyan_skillfish_reg_init \
            drm/amd/amdgpu/cz_ih \
            drm/amd/amdgpu/dce_v10_0 \
            drm/amd/amdgpu/df_v1_7 \
            drm/amd/amdgpu/df_v3_6 \
            drm/amd/amdgpu/df_v4_15 \
            drm/amd/amdgpu/df_v4_3 \
            drm/amd/amdgpu/df_v4_6_2 \
            drm/amd/amdgpu/emu_soc \
            drm/amd/amdgpu/gfx_v10_0 \
            drm/amd/amdgpu/gfx_v11_0 \
            drm/amd/amdgpu/gfx_v11_0_3 \
            drm/amd/amdgpu/gfx_v12_0 \
            drm/amd/amdgpu/gfx_v8_0 \
            drm/amd/amdgpu/gfx_v9_0 \
            drm/amd/amdgpu/gfx_v9_4 \
            drm/amd/amdgpu/gfx_v9_4_2 \
            drm/amd/amdgpu/gfx_v9_4_3 \
            drm/amd/amdgpu/gfxhub_v11_5_0 \
            drm/amd/amdgpu/gfxhub_v12_0 \
            drm/amd/amdgpu/gfxhub_v1_0 \
            drm/amd/amdgpu/gfxhub_v1_1 \
            drm/amd/amdgpu/gfxhub_v1_2 \
            drm/amd/amdgpu/gfxhub_v2_0 \
            drm/amd/amdgpu/gfxhub_v2_1 \
            drm/amd/amdgpu/gfxhub_v3_0 \
            drm/amd/amdgpu/gfxhub_v3_0_3 \
            drm/amd/amdgpu/gmc_v10_0 \
            drm/amd/amdgpu/gmc_v11_0 \
            drm/amd/amdgpu/gmc_v12_0 \
            drm/amd/amdgpu/gmc_v7_0 \
            drm/amd/amdgpu/gmc_v8_0 \
            drm/amd/amdgpu/gmc_v9_0 \
            drm/amd/amdgpu/hdp_v4_0 \
            drm/amd/amdgpu/hdp_v5_0 \
            drm/amd/amdgpu/hdp_v5_2 \
            drm/amd/amdgpu/hdp_v6_0 \
            drm/amd/amdgpu/hdp_v7_0 \
            drm/amd/amdgpu/iceland_ih \
            drm/amd/amdgpu/ih_v6_0 \
            drm/amd/amdgpu/ih_v6_1 \
            drm/amd/amdgpu/ih_v7_0 \
            drm/amd/amdgpu/imu_v11_0 \
            drm/amd/amdgpu/imu_v11_0_3 \
            drm/amd/amdgpu/imu_v12_0 \
            drm/amd/amdgpu/jpeg_v1_0 \
            drm/amd/amdgpu/jpeg_v2_0 \
            drm/amd/amdgpu/jpeg_v2_5 \
            drm/amd/amdgpu/jpeg_v3_0 \
            drm/amd/amdgpu/jpeg_v4_0 \
            drm/amd/amdgpu/jpeg_v4_0_3 \
            drm/amd/amdgpu/jpeg_v4_0_5 \
            drm/amd/amdgpu/jpeg_v5_0_0 \
            drm/amd/amdgpu/jpeg_v5_0_1 \
            drm/amd/amdgpu/lsdma_v6_0 \
            drm/amd/amdgpu/lsdma_v7_0 \
            drm/amd/amdgpu/mca_v3_0 \
            drm/amd/amdgpu/mes_userqueue \
            drm/amd/amdgpu/mes_v11_0 \
            drm/amd/amdgpu/mes_v12_0 \
            drm/amd/amdgpu/mmhub_v1_0 \
            drm/amd/amdgpu/mmhub_v1_7 \
            drm/amd/amdgpu/mmhub_v1_8 \
            drm/amd/amdgpu/mmhub_v2_0 \
            drm/amd/amdgpu/mmhub_v2_3 \
            drm/amd/amdgpu/mmhub_v3_0 \
            drm/amd/amdgpu/mmhub_v3_0_1 \
            drm/amd/amdgpu/mmhub_v3_0_2 \
            drm/amd/amdgpu/mmhub_v3_3 \
            drm/amd/amdgpu/mmhub_v4_1_0 \
            drm/amd/amdgpu/mmhub_v9_4 \
            drm/amd/amdgpu/mxgpu_ai \
            drm/amd/amdgpu/mxgpu_nv \
            drm/amd/amdgpu/mxgpu_vi \
            drm/amd/amdgpu/navi10_ih \
            drm/amd/amdgpu/nbif_v6_3_1 \
            drm/amd/amdgpu/nbio_v2_3 \
            drm/amd/amdgpu/nbio_v4_3 \
            drm/amd/amdgpu/nbio_v6_1 \
            drm/amd/amdgpu/nbio_v7_0 \
            drm/amd/amdgpu/nbio_v7_11 \
            drm/amd/amdgpu/nbio_v7_2 \
            drm/amd/amdgpu/nbio_v7_4 \
            drm/amd/amdgpu/nbio_v7_7 \
            drm/amd/amdgpu/nbio_v7_9 \
            drm/amd/amdgpu/nv \
            drm/amd/amdgpu/psp_v10_0 \
            drm/amd/amdgpu/psp_v11_0 \
            drm/amd/amdgpu/psp_v11_0_8 \
            drm/amd/amdgpu/psp_v12_0 \
            drm/amd/amdgpu/psp_v13_0 \
            drm/amd/amdgpu/psp_v13_0_4 \
            drm/amd/amdgpu/psp_v14_0 \
            drm/amd/amdgpu/psp_v3_1 \
            drm/amd/amdgpu/sdma_v2_4 \
            drm/amd/amdgpu/sdma_v3_0 \
            drm/amd/amdgpu/sdma_v4_0 \
            drm/amd/amdgpu/sdma_v4_4 \
            drm/amd/amdgpu/sdma_v4_4_2 \
            drm/amd/amdgpu/sdma_v5_0 \
            drm/amd/amdgpu/sdma_v5_2 \
            drm/amd/amdgpu/sdma_v6_0 \
            drm/amd/amdgpu/sdma_v7_0 \
            drm/amd/amdgpu/sienna_cichlid \
            drm/amd/amdgpu/smu_v11_0_i2c \
            drm/amd/amdgpu/smu_v13_0_10 \
            drm/amd/amdgpu/smuio_v11_0 \
            drm/amd/amdgpu/smuio_v11_0_6 \
            drm/amd/amdgpu/smuio_v13_0 \
            drm/amd/amdgpu/smuio_v13_0_3 \
            drm/amd/amdgpu/smuio_v13_0_6 \
            drm/amd/amdgpu/smuio_v14_0_2 \
            drm/amd/amdgpu/smuio_v9_0 \
            drm/amd/amdgpu/soc15 \
            drm/amd/amdgpu/soc21 \
            drm/amd/amdgpu/soc24 \
            drm/amd/amdgpu/tonga_ih \
            drm/amd/amdgpu/umc_v12_0 \
            drm/amd/amdgpu/umc_v6_0 \
            drm/amd/amdgpu/umc_v6_1 \
            drm/amd/amdgpu/umc_v6_7 \
            drm/amd/amdgpu/umc_v8_10 \
            drm/amd/amdgpu/umc_v8_14 \
            drm/amd/amdgpu/umc_v8_7 \
            drm/amd/amdgpu/umsch_mm_v4_0 \
            drm/amd/amdgpu/uvd_v5_0 \
            drm/amd/amdgpu/uvd_v6_0 \
            drm/amd/amdgpu/uvd_v7_0 \
            drm/amd/amdgpu/vce_v3_0 \
            drm/amd/amdgpu/vce_v4_0 \
            drm/amd/amdgpu/vcn_sw_ring \
            drm/amd/amdgpu/vcn_v1_0 \
            drm/amd/amdgpu/vcn_v2_0 \
            drm/amd/amdgpu/vcn_v2_5 \
            drm/amd/amdgpu/vcn_v3_0 \
            drm/amd/amdgpu/vcn_v4_0 \
            drm/amd/amdgpu/vcn_v4_0_3 \
            drm/amd/amdgpu/vcn_v4_0_5 \
            drm/amd/amdgpu/vcn_v5_0_0 \
            drm/amd/amdgpu/vcn_v5_0_1 \
            drm/amd/amdgpu/vega10_ih \
            drm/amd/amdgpu/vega10_reg_init \
            drm/amd/amdgpu/vega20_ih \
            drm/amd/amdgpu/vega20_reg_init \
            drm/amd/amdgpu/vi \
            drm/amd/amdgpu/vpe_v6_1 \
            drm-aros/amdgpu_vkms_aros \
            drm-aros/amdgpu_aros \

# The in-process libdrm: the ioctl shim and the KMS wrappers.
AROS_AMDGPU_LIBDRM_SOURCES = \
            libdrm/arosdrm \
            libdrm/arosdrmmode \

