##begin config
basename        HiddVC4Gallium
version         1.0
residentpri     -1
libbasetype     struct HiddVC4GalliumBase
libbasetypeextern struct HiddVC4GalliumBase
classid         CLID_Hidd_Gallium_VC4
superclass      CLID_Hidd_Gallium
classptr_field  sd.galliumclass
classdatatype   struct HiddGalliumVC4Data
##end config

##begin cdefprivate
#include "vc4gallium_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gallium
CreatePipeScreen
DestroyPipeScreen
DisplayResourceRP
##end methodlist
