/* Auto-generated: subdev/therm */
#include "base.c"
#include "fan.c"
#include "fannil.c"
#include "fanpwm.c"
#include "fantog.c"
#include "g84.c"
#include "gf100.c"
#include "gk104.c"
#include "gm107.c"
#include "gm200.c"
#include "gp100.c"
#include "gt215.c"
#include "ic.c"
#include "nv40.c"
#include "nv50.c"
#include "temp.c"
