CC	= gcc
CFLAGS	= -O2 -fstrength-reduce -fomit-frame-pointer -msmall-code -fbaserel -c -I../include
LDFLAGS = -noixemul -nostartfiles -fbaserel -s
LDLIBS	=

OBJS	= LibInit.o SampleFuncs.o

example.library: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

LibInit.o: LibInit.c
	$(CC) $(CFLAGS) LibInit.c

SampleFuncs.o: SampleFuncs.c
	$(CC) $(CFLAGS) SampleFuncs.c
