# $Id$
TOP=..
CURDIR=compiler

include $(TOP)/config/make.cfg

ifeq ($(FLAVOUR),native)
SUBDIRS=arossupport alib clib
else
SUBDIRS=arossupport alib clib c_lib
#vcpp vbcc
endif

all:
	%subdirs_q target=all

clean::
	%subdirs_q Cleaning clean

setup:
	%subdirs_q "Setting up" setup

%common
