##begin config
basename RadioButton
version 44.1
classid "radiobutton.gadget"
superclass GADGETCLASS
classdatatype struct RadioButtonData
libbasetype struct RadioButtonBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/radiobutton.h>
##end cdef
##begin cdefprivate
#include "radiobutton_intern.h"
##end cdefprivate
##begin functionlist
Class *RADIOBUTTON_GetClass() ()
struct Node *AllocRadioButtonNodeA(UWORD columns, struct TagItem *tags) (D0, A0)
void FreeRadioButtonNode(struct Node *node) (A0)
void SetRadioButtonNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void GetRadioButtonNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
