##begin config
basename RadioButton
version 44.1
classid "radiobutton.gadget"
superclass GADGETCLASS
classdatatype struct RadioButtonData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/radiobutton.h>
##end cdef
##begin cdefprivate
#include "radiobutton_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
