# SConscript file for SCons for ScreenGrabber

# Get the exported variables
Import('*')

# Object files will be stored there
VariantDir(gendir + '/tools/screengrabber', '.')

# Build ScreenGrabber
targetEnv.Program(arosdir + '/Tools/ScreenGrabber',
    ['main.c', 'locale.c'], LIBS = 'mui')

# Create strings.h
targetEnv.Locale_H('strings.h', 'catalogs/screengrabber.cd')
