##begin config
version 45.0
libbase nh
libbasetype struct BTGattBase
libbasetypeextern struct Library
residentpri 28
basename btgatt
##end config

##begin cdef
#include <libraries/btclass.h>
#include "btgatt.h"
##end cdef

##begin functionlist
LONG btcGetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
LONG btcSetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
SIPTR btcDoMethodA(ULONG methodid, IPTR *methoddata) (D0,A1)
##end functionlist
