##begin config
version         7.1
residentpri     90
libbasetype     struct IntHiddVulkanBase
basename        HiddVulkan
classid         CLID_Hidd_Vulkan
superclass      CLID_Hidd
classptr_field  sd.vulkanclass
classdatatype   struct HiddVulkanData
##end config

##begin cdef
#include <hidd/vulkan_hidd.h>
##end cdef

##begin cdefprivate
#include <hidd/vulkan_hidd.h>
#include "vulkan_intern.h"
##end cdefprivate

##begin functionlist
int32_t VulkanHidd_RegisterGPU(const char *class_id, OOP_Object *pci_device, uint32_t vendor_id, uint32_t device_id, uint32_t flags, uint64_t vram_size, const char *name, int32_t priority, const struct VulkanDriverCallbacks *callbacks, APTR driver_data, uint8_t pci_bus, uint8_t pci_dev_num, uint8_t pci_func) (A0, A1, D0, D1, D2, D3, A2, D4, A3, A4, D5, D6, D7)
BOOL VulkanHidd_SetGPUPSPLoaded(uint8_t pci_bus, uint8_t pci_dev_num, uint8_t pci_func, uint32_t vendor_id, uint32_t device_id, BOOL loaded) (D0, D1, D2, D3, D4, D5)
BOOL VulkanHidd_IsGPUPSPLoaded(uint8_t pci_bus, uint8_t pci_dev_num, uint8_t pci_func, uint32_t vendor_id, uint32_t device_id) (D0, D1, D2, D3, D4)
##end functionlist

##begin methodlist
.interface Root
New
Get
.interface Hidd_Vulkan
CreateInstance
DestroyInstance
EnumeratePhysicalDevices
GetPhysicalDeviceProperties
GetPhysicalDeviceProperties2
GetPhysicalDeviceFeatures
GetPhysicalDeviceFeatures2
GetPhysicalDeviceMemoryProperties
GetPhysicalDeviceQueueFamilyProperties
EnumerateDeviceExtensionProperties
CreateDevice
DestroyDevice
GetDeviceQueue
DeviceWaitIdle
DisplayResource
AllocateMemory
FreeMemory
MapMemory
UnmapMemory
GetMemoryHostPointerPropertiesEXT
CreateBuffer
DestroyBuffer
BindBufferMemory
GetBufferMemoryRequirements
GetBufferDeviceAddress
CreateDescriptorSetLayout
DestroyDescriptorSetLayout
CreateDescriptorPool
DestroyDescriptorPool
AllocateDescriptorSets
UpdateDescriptorSets
CreateCommandPool
DestroyCommandPool
ResetCommandPool
AllocateCommandBuffers
FreeCommandBuffers
BeginCommandBuffer
EndCommandBuffer
QueueSubmit
QueueWaitIdle
CreateFence
DestroyFence
WaitForFences
ResetFences
GetFenceStatus
CreateSemaphore
DestroySemaphore
CreateEvent
DestroyEvent
SetEvent
ResetEvent
CreateShaderModule
DestroyShaderModule
CreatePipelineLayout
DestroyPipelineLayout
CreateComputePipelines
DestroyPipeline
CreateQueryPool
DestroyQueryPool
GetQueryPoolResults
ResetQueryPool
CmdBindPipeline
CmdBindDescriptorSets
CmdPushConstants
CmdDispatch
CmdCopyBuffer
CmdFillBuffer
CmdPipelineBarrier
CmdSetEvent
CmdResetEvent
CmdWaitEvents
CmdWriteTimestamp
CmdResetQueryPool
EnumerateGPUs
SetGPUPriority
GetInstanceProcAddr
GetDeviceProcAddr
EnumerateInstanceVersion
EnumerateInstanceExtensionProperties
##end methodlist
