#define WANDERERVERS    0
#define WANDERERREV     92
#define WANDERERSTR     "Wanderer 0.92 (17.12.2011)"
#define WANDERERAUTH    "The AROS Dev Team"
#define WANDERERCOPY    "© " WANDERERAUTH
#define VERSION "$VER:  " WANDERERSTR " " WANDERERCOPY
