#define WANDERERNAME    "Wanderer"
#define WANDERERVERS    1
#define WANDERERREV     0
#define WANDERERSTR     WANDERERNAME" 1.0 (31.12.2011)"
#define WANDERERAUTH    "The AROS Dev Team"
#define WANDERERCOPY    "© " WANDERERAUTH
#define VERSION "$VER:  " WANDERERSTR " " WANDERERCOPY
