#define WANDERERVERS    0
#define WANDERERREV     81
#define WANDERERSTR     "Wanderer 0.81 (18.03.2009)"
#define WANDERERAUTH    "The AROS Dev Team"
#define WANDERERCOPY    "© " WANDERERAUTH
#define VERSION "$VER:  " WANDERERSTR " " WANDERERCOPY
