##begin config
version         1.0
residentpri     90
libbasetype     struct IntHiddV3DBase
basename        HiddV3D
classid         "hidd.gallium.v3d"
superclass      CLID_Hidd_Gallium
classptr_field  sd.galliumclass
classdatatype   struct V3DData
##end config

##begin cdefprivate
#include <hidd/gallium.h>
#include "v3d_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
.interface Hidd_Gallium
CreatePipeScreen
DisplayResource
##end methodlist
