#!/bin/sh

for file in "$@" ; do
    tmp="`basename $file .c`.tmp"
    html="`basename $file .c`.html"

    echo "<include file=tohtml.inc>" > "$tmp"
    echo "<doc title=\"$file\">" >> "$tmp"
    echo "<code type=c>" >> "$tmp"
    cat "$file" >> "$tmp"
    echo "</code>" >> "$tmp"
    echo "</doc>" >> "$tmp"

    hpp "$tmp" > "$html"
    rm "$tmp"
done
