#!/bin/sh

for file in "$@" ; do
    tmp="`basename $file .c`.tmp"
    tex="`basename $file .c`.tex"

    echo "<include file=tolatex.inc>" > "$tmp"
    echo "<doc title=\"$file\">" >> "$tmp"
    echo "<code type=c>" >> "$tmp"
    #echo "<include file=\"$file\">" >> "$tmp"
    cat "$file" >> "$tmp"
    echo "</code>" >> "$tmp"
    echo "</doc>" >> "$tmp"

    hpp -set format=./format "$tmp" | sed -f ctolatex.filter > "$tex"
    rm "$tmp"
done
