##begin config
basename        H4BTHCI
version         45.1
libbasetype     struct H4BTHCIBase
beginio_func    BeginIO
abortio_func    AbortIO
##end config

##begin cdefprivate
#include "h4bthci_intern.h"
##end cdefprivate
