##begin config
version 50.1
basename Dos64
libbase DOS64Base
libbasetype struct Dos64Base
libbasetypeextern struct Library
residentpri -121
options noexpunge
##end config

##begin cdef
#include <dos/dos.h>
#include <dos/dosextens.h>
#include <dos/record.h>
#include <dos/dos64.h>
#include <utility/tagitem.h>
##end cdef

##begin cdefprivate
#include "dos64_intern.h"
##end cdefprivate

##begin functionlist
QUAD Seek64(BPTR file, LONG mode, QUAD position) (D1, D2, D3/D4)
QUAD SetFileSize64(BPTR file, LONG mode, QUAD offset) (D1, D2, D3/D4)
QUAD GetFilePosition64(BPTR file) (D1)
QUAD GetFileSize64(BPTR file) (D1)
LONG ChangeFilePosition64(BPTR file, LONG mode, QUAD position) (D1, D2, D3/D4)
LONG ChangeFileSize64(BPTR file, LONG mode, QUAD size) (D1, D2, D3/D4)
QUAD Read64(BPTR file, APTR buffer, QUAD length) (D1, D2, D3/D4)
QUAD Write64(BPTR file, CONST_APTR buffer, QUAD length) (D1, D2, D3/D4)
LONG Examine64(BPTR lock, struct FileInfoBlock64 *fib, struct TagItem *tags) (D1, D2, D3)
LONG ExNext64(BPTR lock, struct FileInfoBlock64 *fib, struct TagItem *tags) (D1, D2, D3)
LONG ExamineFH64(BPTR fh, struct FileInfoBlock64 *fib, struct TagItem *tags) (D1, D2, D3)
LONG Info64(BPTR lock, struct InfoData64 *parameterBlock) (D1, D2)
BOOL LockRecord64(struct RecordLock64 *rec, ULONG timeout) (D1, D2)
BOOL LockRecords64(struct RecordLock64 *recArray, ULONG timeout) (D1, D2)
BOOL UnLockRecord64(struct RecordLock64 *rec) (D1)
BOOL UnLockRecords64(struct RecordLock64 *recArray) (D1)
APTR AllocDosObject64(ULONG type, const struct TagItem *tags) (D1, D2)
void FreeDosObject64(ULONG type, APTR ptr) (D1, D2)
##end functionlist
