TOP = ../../../..

include $(TOP)/config/make.cfg

USER_INCLUDES = -D_AROS -I../include

STARTUP = $(LIBDIR)/startup.o
LIBS = -L$(LIBDIR) -lamiga -larossupport -larosc
DEPLIBS = $(LIBDIR)/libamiga.a $(LIBDIR)/libarossupport.a \
	$(LIBDIR)/libarosc.a $(STARTUP)

OBJS = TestExampleLib.o
EXE = $(EXEDIR)/TestExampleLib

all : $(EXE)

clean :
	$(RM) *.o $(EXE)

$(EXE) : $(OBJS) $(DEPLIBS)
	$(CC) $(ILDFLAGS) -o $@ $(STARTUP) $(OBJS) $(LIBS)

TestExampleLib.o : TestExampleLib.c
	$(CC) $(CFLAGS) -c $<

