#ifndef EGL_MANGLE_H
#define EGL_MANGLE_H
#define eglGetError meglGetError
#define eglGetDisplay meglGetDisplay
#define eglInitialize meglInitialize
#define eglTerminate meglTerminate
#define eglQueryString meglQueryString
#define eglGetConfigs meglGetConfigs
#define eglChooseConfig meglChooseConfig
#define eglGetConfigAttrib meglGetConfigAttrib
#define eglCreateWindowSurface meglCreateWindowSurface
#define eglCreatePbufferSurface meglCreatePbufferSurface
#define eglCreatePixmapSurface meglCreatePixmapSurface
#define eglDestroySurface meglDestroySurface
#define eglQuerySurface meglQuerySurface
#define eglBindAPI meglBindAPI
#define eglQueryAPI meglQueryAPI
#define eglWaitClient meglWaitClient
#define eglReleaseThread meglReleaseThread
#define eglCreatePbufferFromClientBuffer meglCreatePbufferFromClientBuffer
#define eglSurfaceAttrib meglSurfaceAttrib
#define eglBindTexImage meglBindTexImage
#define eglReleaseTexImage meglReleaseTexImage
#define eglSwapInterval meglSwapInterval
#define eglCreateContext meglCreateContext
#define eglDestroyContext meglDestroyContext
#define eglMakeCurrent meglMakeCurrent
#define eglGetCurrentContext meglGetCurrentContext
#define eglGetCurrentSurface meglGetCurrentSurface
#define eglGetCurrentDisplay meglGetCurrentDisplay
#define eglQueryContext meglQueryContext
#define eglWaitGL meglWaitGL
#define eglWaitNative meglWaitNative
#define eglSwapBuffers meglSwapBuffers
#define eglCopyBuffers meglCopyBuffers
#endif
