##begin config
basename        bwfm_device
version         0.1
libbasetype     struct bwfm_base
beginio_func    begin_io
abortio_func    abort_io
##end config

##begin cdefprivate
#include "bwfm.h"
##end cdefprivate
