# $Id$
TOP=../../..

include $(TOP)/config/make.cfg

SPECIAL_AFLAGS = -I../
CLIBDIR=$(GENDIR)/clib
OBJDIR=$(OSGENDIR)/utility

FILES = sdivmod32 smult32 smult64 udivmod32 umult32 umult64

TESTS =

all: setup $(foreach f,$(FILES),$(OBJDIR)/$(f).o) 

setup :
	%mkdirs_q $(OBJDIR) $(OSGENDIR)
	%add_objects $(foreach f,$(FILES), rom/utility/$(f))
	%exclude_files $(foreach f,$(FILES), rom/utility/$(f))

clean::
	$(RM) $(TESTS)

$(OBJDIR)/%.o: %.s ../machine.i
	%assemble_q

%common
