#include <errno.h>

const char * _errstrings[MAX_ERRNO + 1] =
{
    /* 0	       */	"No error",
    /* EPERM	       */	"Operation not permitted",
    /* ENOENT	       */	"No such file or directory",
    /* ESRCH	       */	"No such process",
    /* EINTR	       */	"Interrupted system call",
    /* EIO	       */	"I/O error",
    /* ENXIO	       */	"No such device or address",
    /* E2BIG	       */	"Arg list too long",
    /* ENOEXEC	       */	"Exec format error",
    /* EBADF	       */	"Bad file number",
    /* ECHILD	       */	"No child processes",
    /* EDEADLK	       */	"Resource deadlock would occur",
    /* ENOMEM	       */	"Out of memory",
    /* EACCES	       */	"Permission denied",
    /* EFAULT	       */	"Bad address",
    /* ENOTBLK	       */	"Block device required",
    /* EBUSY	       */	"Device or resource busy",
    /* EEXIST	       */	"File exists",
    /* EXDEV	       */	"Cross-device link",
    /* ENODEV	       */	"No such device",
    /* ENOTDIR	       */	"Not a directory",
    /* EISDIR	       */	"Is a directory",
    /* EINVAL	       */	"Invalid argument",
    /* ENFILE	       */	"File table overflow",
    /* EMFILE	       */	"Too many open files",
    /* ENOTTY	       */	"Not a typewriter",
    /* ETXTBSY	       */	"Text file busy",
    /* EFBIG	       */	"File too large",
    /* ENOSPC	       */	"No space left on device",
    /* ESPIPE	       */	"Illegal seek",
    /* EROFS	       */	"Read-only file system",
    /* EMLINK	       */	"Too many links",
    /* EPIPE	       */	"Broken pipe",
    /* EDOM	       */	"Math argument out of domain of func",
    /* ERANGE	       */	"Math result not representable",
    /* EAGAIN	       */	"Try again",
    /* EINPROGRESS     */	"Operation now in progress",
    /* EALREADY        */	"Operation already in progress",
    /* ENOTSOCK        */	"Socket operation on non-socket",
    /* EDESTADDRREQ    */	"Destination address required",
    /* EMSGSIZE        */	"Message too long",
    /* EPROTOTYPE      */	"Protocol wrong type for socket",
    /* ENOPROTOOPT     */	"Protocol not available",
    /* EPROTONOSUPPORT */	"Protocol not supported",
    /* ESOCKTNOSUPPORT */	"Socket type not supported",
    /* EOPNOTSUPP      */	"Operation not supported on transport endpoint",
    /* EPFNOSUPPORT    */	"Protocol family not supported",
    /* EAFNOSUPPORT    */	"Address family not supported by protocol",
    /* EADDRINUSE      */	"Address already in use",
    /* EADDRNOTAVAIL   */	"Cannot assign requested address",
    /* ENETDOWN        */	"Network is down",
    /* ENETUNREACH     */	"Network is unreachable",
    /* ENETRESET       */	"Network dropped connection because of reset",
    /* ECONNABORTED    */	"Software caused connection abort",
    /* ECONNRESET      */	"Connection reset by peer",
    /* ENOBUFS	       */	"No buffer space available",
    /* EISCONN	       */	"Transport endpoint is already connected",
    /* ENOTCONN        */	"Transport endpoint is not connected",
    /* ESHUTDOWN       */	"Cannot send after transport endpoint shutdown",
    /* ETOOMANYREFS    */	"Too many references: cannot splice",
    /* ETIMEDOUT       */	"Connection timed out",
    /* ECONNREFUSED    */	"Connection refused",
    /* ELOOP	       */	"Too many symbolic links encountered",
    /* ENAMETOOLONG    */	"File name too long",
    /* EHOSTDOWN       */	"Host is down",
    /* EHOSTUNREACH    */	"No route to host",
    /* ENOTEMPTY       */	"Directory not empty",
    /* EPROCLIM	       */	"Too many processes",
    /* EUSERS	       */	"Too many users",
    /* EDQUOT	       */	"Quota exceeded",
    /* ESTALE	       */	"Stale NFS file handle",
    /* EREMOTE	       */	"Object is remote",
    /* EBADRPC	       */	"Bad RPC structure",
    /* ERPCMISMATCH    */	"Wrong RPC version",
    /* EPROGUNAVAIL    */	"RPC program not available",
    /* EPROGMISMATCH   */	"Wrong RPC program version",
    /* EPROCUNAVAIL    */	"Bad procedure for program",
    /* ENOLCK	       */	"No record locks available",
    /* ENOSYS	       */	"Function not implemented",
    /* EFTYPE          */	"Bad file type or format",
    /* EAUTH	       */	"Authentication error",
    /* ENEEDAUTH       */	"Authentication needed",
    /* EIDRM	       */	"Identifier removed",
    /* ENOMSG	       */	"No message of desired type",
    /* EOVERFLOW       */	"Value too large for defined data type",
    /* ECANCELED       */	"Operation canceled",
    /* EILSEQ	       */	"Illegal byte sequence"
};
