##begin config
basename BitMap
version 44.1
classid "bitmap.image"
classdatatype struct BitmapData
libbasetype struct BitMapBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/imageclass.h>
#include <images/bitmap.h>
##end cdef
##begin cdefprivate
#include "bitmap_intern.h"
##end cdefprivate
##begin functionlist
Class *BITMAP_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
IM_DRAW
##end methodlist
