##begin config
basename Scroller
version 44.1
classid "scroller.gadget"
superclass PROPGCLASS
classdatatype struct ScrollerData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/scroller.h>
##end cdef
##begin cdefprivate
#include "scroller_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
