/*
    Copyright © 1995-2001, The AROS Development Team. All rights reserved.
    *** Automatically generated by genfunctable.awk. Do not edit ***
    Desc: Function table for Kernel
    Lang: english
*/
#include <aros/libcall.h>
#ifndef NULL
#define NULL ((void *)0)
#endif

#include "kernel.h"

#include "libdefs.h"
extern void AROS_SLIB_ENTRY(BusToPhys,BASENAME,5) (void);
extern void AROS_SLIB_ENTRY(PhysToBus,BASENAME,6) (void);
extern void AROS_SLIB_ENTRY(OutB,BASENAME,7) (void);
extern void AROS_SLIB_ENTRY(OutW,BASENAME,8) (void);
extern void AROS_SLIB_ENTRY(OutL,BASENAME,9) (void);
extern void AROS_SLIB_ENTRY(InB,BASENAME,10) (void);
extern void AROS_SLIB_ENTRY(InW,BASENAME,11) (void);
extern void AROS_SLIB_ENTRY(InL,BASENAME,12) (void);

void *const LIBFUNCTABLE[VECTOR_COUNT+1]=
{
    AROS_SLIB_ENTRY(BusToPhys,BASENAME,5),
    AROS_SLIB_ENTRY(PhysToBus,BASENAME,6),
    AROS_SLIB_ENTRY(OutB,BASENAME,7),
    AROS_SLIB_ENTRY(OutW,BASENAME,8),
    AROS_SLIB_ENTRY(OutL,BASENAME,9),
    AROS_SLIB_ENTRY(InB,BASENAME,10),
    AROS_SLIB_ENTRY(InW,BASENAME,11),
    AROS_SLIB_ENTRY(InL,BASENAME,12),
    (void *)-1L
};
