##begin config
basename	FBGfx
libbasetype	struct FBGfxBase
version		45.5
residentpri     9
classptr_field  vsd.fbgfxclass
classdatatype	struct FBGfxHiddData
classid         CLID_Hidd_Gfx_FB
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "fbgfx_intern.h"
#include "fbgfx_hidd.h"
#include "fbgfx_display.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist


##begin class
##begin config
basename FBGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_FB
superclass CLID_Hidd_Display
classdatatype struct FBGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
Show
##end methodlist
##end class


##begin class
##begin config
basename FBGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_FB
superclass CLID_Hidd_ChunkyBM
classdatatype struct FBGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Get
Set
.interface Hidd_BitMap
SetColors
UpdateRect
##end methodlist
##end class
