##begin config
basename	PCIVMD
libbasetype	struct PCIVMDBase
version		45.0
residentpri     86
oopbase_field   psd.OOPBase
superclass      CLID_Hidd_PCIDriver
classptr_field  psd.vmdDriverClass
classdatatype struct VMDBusData
options noincludes, noexpunge
##end config

##begin cdefprivate
#include <hidd/pci.h>
#include "pcivmd.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Get
.interface Hidd_PCIDriver
ReadConfigByte
ReadConfigWord
ReadConfigLong
WriteConfigByte
WriteConfigWord
WriteConfigLong
MapPCI
AddInterrupt
##end methodlist


##begin class
##begin config
basename       PCIVMDDev
type           hidd
superclass     CLID_Hidd_PCIDevice
classptr_field psd.vmdDeviceClass
classdatatype  struct VMDDeviceData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_PCIDevice
GetVectorAttribs
ObtainVectors
ReleaseVectors
##end methodlist
##end class
