#!/bin/sh
#

Lib="$1"
lib="`echo $Lib | gawk ' { print tolower($0); }'`"
TOP="$2"
mic="$TOP/scripts/moveifchanged"

echo "Generating prototypes for $Lib..."

incdir="$TOP/compiler/include"
basedir="$TOP/rom/$lib"
clibdir="$incdir/clib"
defdir="$incdir/defines"

shift ; shift

pubclib="$clibdir/${lib}_protos.h"
pubdef="$defdir/$lib.h"

case "$Lib" in
    "Console" ) basedir="$TOP/rom/devs" ;;
    "Icon" ) basedir="$TOP/workbench/libs/icon" ;;
    "IFFParse" ) basedir="$TOP/workbench/libs/iffparse" ;;
esac

privclib="$basedir/${lib}_private.h"
privdef="$basedir/${lib}_pdefs.h"

gawk -f $TOP/scripts/genprotos.h \
    --assign lib="$Lib" \
    --assign TOP="$TOP" \
    --assign pubclib="$pubclib" \
    --assign privclib="$privclib" \
    --assign pubdef="$pubdef" \
    --assign privdef="$privdef" \
    $*

for file in "$pubclib" "$privclib" "$pubdef" "$privdef" ; do
    if [ ! -s "$file".new ]; then
	rm "$file".new
    else
	$mic "$file".new "$file"
    fi
done

