#!/bin/sh
#
# $0 new old
#
# Replaces old with new if they differ. old is saved as old.bak
#

if cmp -s "$1" "$2"; then
    true
else
    echo "Replacing $2 by $1"
    mv "$2" "$2.bak"
    mv "$1" "$2"
fi
