#!/bin/bash

##############################################################################
# Moves nightly build files from the uploads directory to the download
# directory. Checks the integrity of files before moving, so incomplete or
# broken files are not available for download.

#-- Configuration & Setup ----------------------------------------------------
ROOT=/home/groups/a/ar/aros
SRC=$ROOT/uploads/nightly
DST=$ROOT/htdocs/downloads/nightly
LOCK=$SRC.lock

umask 0002 

#-- Support Functions --------------------------------------------------------
function md5check()
{
    # Description:
    # Checks the MD5 sum of the given file. Will return failure if the MD5 sum
    # is incorrect, the file is missing, or the MD5 sum file is missing. 
    #
    # The MD5 sum must be stored in a separate file with the same name as the 
    # file to be tested, with ".md5" appended. Eg., if the file is "foo.txt",
    # then the MD5 sum must be stored in "foo.txt.md5". The format of the file
    # is that of the output from the GNU md5sum command.
    #
    # Inputs:
    # $1 - path of file to check.
    # 
    # Outputs:
    # $? - 0 if file is OK, !0 if FAILED.
    
    local oldpwd="$PWD"
    cd "$(dirname $1)"
    md5sum -c "$(basename $1).md5" >/dev/null 2>&1; rc=$?
    cd "$oldpwd"
    
    return $rc
}

#-- Acquire Lock -------------------------------------------------------------
lockfile -r 0 "$LOCK"
if [[ $? != 0 ]]; then
    echo Could not acquire lock. Aborting...
    exit 1
fi

#-- Process Pending Files ----------------------------------------------------
cd "$SRC"

OLDIFS=$IFS; IFS=";"
for file in $(find . -type f -not -name "*.md5" -printf "%p;"); do
    if [ ! -z "$file" ]; then
        md5check "$file"
        if [ $? = 0 ]; then
            echo "> $file"
            
            dst="$DST/$(dirname $file)"
            mkdir -p "$dst"

            if [ "${file:${#file}-4:4}" = ".xml" ]; then
                cl="$(basename ${file:0:${#file}-4})"
                xsltproc -o $dst/$cl.php --stringparam date ${cl:5:8} --stringparam module ${cl:24} $ROOT/scripts/cl2html.xslt "$file"

                if [ $? = 0 ]; then
                    rm "$file"
                    rm "$file.md5"
                fi
            else
                mv -f "$file" $dst
                mv -f "$file.md5" $dst
            fi
        else
            echo "! $file"
        fi
    fi
done
IFS=$OLDIFS

#-- Prune Downloads Directory ------------------------------------------------
cd "$DST"

count=$(($(ls -1 | wc -l) - 1))
for directory in *; do
    if [[ $count -gt 0 ]]; then
        rm -rf "$directory"
        count=$((count - 1))
    fi
done

#-- Release Lock -------------------------------------------------------------
rm -f "$LOCK"
