#!/bin/sh

#cvsserver=cvs.aros.org
cvsserver=sbb.hepe.com
rootpath="/home/cvs/aros"
rep=AROS

user=$LOGNAME
if [ -z "$user" ]; then
    echo "Can't figure out username"
    exit 1
fi

for dir in `find . -name CVS -type d` ; do
    path=`dirname "$dir" | cut -c2-`
    root=":pserver:$user@$cvsserver:$rootpath"
    repository="$rootpath/$rep$path"
    echo "$root" > $dir/Root
    echo "$repository" > $dir/Repository
    echo $dir
done
