#!/usr/bin/python

# Script for translating trac.aros.org's RSS feed to html for including
# in www.aros.org's commits section.
# The result will be stored in htdocs

import urllib2
#import ssl # not needed on Sourceforge with Python 2.6
import re
import HTMLParser

# We must set the encoding or HTMLParser().unescape() fails with error
# "UnicodeDecodeError: 'ascii' codec can't decode byte..."
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')

# regex for parsing a RSS item
rssre = re.compile(r'''<item>.*?
<title>.*?\[(?P<commit>.*?)\].*?</title>.*?
<dc:creator>(?P<creator>.*?)</dc:creator>.*?
<pubDate>(?P<pubDate>.*?)</pubDate>.*?
<link>(?P<link>.*?)</link>.*?
<description>(?P<description>.*?)</description>.*?
</item>''',
re.DOTALL | re.VERBOSE)

count = 14 # number of entries
rsspath='https://trac.aros.org/trac/timeline?changeset=on&wiki=on&max=%d&authors=&daysback=90&format=rss' % (count)
#ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
#rssfile = urllib2.urlopen(rsspath, context=ctx)
rssfile = urllib2.urlopen(rsspath)
content = rssfile.read()
rssfile.close()

targetpath='/home/project-web/aros/htdocs/commits.php'
targetfile = open(targetpath, 'w')

# output of the content in html format

targetfile.write('''
<!DOCTYPE html>
<html>
<head>
<title>AROS commits</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="/aros.css">
</head>
<body>
<!--This file is created by script /home/project-web/aros/scripts/updatecommits as cron job -->\n
''')

for entry in rssre.finditer(content):
    targetfile.write('''
<h2><a href="%s" target="_top">%s | %s | %s </a></h2>
%s\n''' % (
    entry.group('link'),
    HTMLParser.HTMLParser().unescape(entry.group('commit')),
    HTMLParser.HTMLParser().unescape(entry.group('creator')),
    HTMLParser.HTMLParser().unescape(entry.group('pubDate')),
    HTMLParser.HTMLParser().unescape(entry.group('description'))))

targetfile.write('</body>\n</html>\n')

targetfile.close()
