#! /bin/sh
set -e

# Provide a backward-compatibility symlink to the doc directory.
package=grub
case "$1" in
configure)
  if [ -d /usr/doc ]; then
    if [ ! -e /usr/doc/$package -a -d /usr/share/doc/$package ]; then
      ln -sf ../share/doc/$package /usr/doc/$package
    fi
  fi
  ;;
esac

# Install our info pages.
install-info --quiet --section Kernel Kernel \
            /usr/share/info/grub.info.gz
install-info --quiet --section Kernel Kernel \
            /usr/share/info/multiboot.info.gz
