# $Id$
TOP=../..
CURDIR=workbench/classes

include $(TOP)/config/make.cfg

SUBDIRS=gadgets
CLASSESDIR=$(BINDIR)/Classes

all:
	%subdirs_q target=all

clean::
	%subdirs_q Cleaning target=clean

setup:
	%mkdirs_q $(CLASSESDIR)

%common

