##begin config
version 50.0
basename Services
libbase ServicesBase
libbasetype struct ServicesBase
libbasetypeextern struct Library
residentpri 0
rellib stdc
##end config

##begin cdef
#include <exec/types.h>
#include <utility/tagitem.h>
#include <envoy/nipc.h>
#include <envoy/services.h>

struct ServiceNode;
##end cdef

##begin cdefprivate
#include "services_intern.h"
##end cdefprivate

##begin functionlist
struct Entity *FindServiceA(CONST_STRPTR remoteHost, CONST_STRPTR serviceName, struct Entity *srcEntity, struct TagItem *tagList) (A0, A1, A2, A3)
void LoseService(struct Entity *entity) (A0)
struct ServiceNode *LockServiceList() ()
void UnlockServiceList() ()
struct ServiceNode *NextService(struct ServiceNode *node) (A0)
void GetServiceAttrsA(struct ServiceNode *node, struct TagItem *tagList) (A0, A1)
void SetServiceAttrsA(struct ServiceNode *node, struct TagItem *tagList) (A0, A1)
BOOL AddService(CONST_STRPTR name, CONST_STRPTR path, struct TagItem *tagList) (A0, A1, A2)
struct ServiceNode *FindServiceByName(CONST_STRPTR name) (A0)
void MarkServiceTemp(struct ServiceNode *node) (A0)
.skip 5
##end functionlist
