#ifndef MEMCHECK_H
#define MEMCHECK_H
#define VALGRIND_MAKE_MEM_DEFINED(a,b)
#define VALGRIND_MAKE_MEM_UNDEFINED(a,b)
#define VALGRIND_MALLOCLIKE_BLOCK(a,b,c,d)
#define VALGRIND_FREELIKE_BLOCK(a,b)
#endif
