##begin config
version 50.1
libbasetype struct NarratorBase
options noexpunge
beginio_func beginio
abortio_func abortio
##end config
##begin cdef
#include <devices/narrator.h>
##end cdef
##begin cdefprivate
#include "narrator_intern.h"
##end cdefprivate
