##begin config
version 50.1
libbasetype struct NarratorBase
options noexpunge
beginio_func beginio
abortio_func abortio
##end config
##begin cdefprivate
#include <devices/narrator.h>
#include "narrator_intern.h"
##end cdefprivate
