#ifndef PROTO_MATHIEEESINGTRANS_H
#define PROTO_MATHIEEESINGTRANS_H

#ifndef INLINE_MACROS_H
#include <inline/macros.h>
#endif

#ifndef MATHIEEESINGTRANS_BASE_NAME
#define MATHIEEESINGTRANS_BASE_NAME MathIeeeSingTransBase
#endif

#define IEEESPAcos(parm) \
	LP1(0x50, FLOAT, IEEESPAcos, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPAsin(parm) \
	LP1(0x4c, FLOAT, IEEESPAsin, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPAtan(parm) \
	LP1(0x14, FLOAT, IEEESPAtan, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPCos(parm) \
	LP1(0x1c, FLOAT, IEEESPCos, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPCosh(parm) \
	LP1(0x2c, FLOAT, IEEESPCosh, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPExp(parm) \
	LP1(0x34, FLOAT, IEEESPExp, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPFieee(parm) \
	LP1(0x48, FLOAT, IEEESPFieee, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPLog(parm) \
	LP1(0x38, FLOAT, IEEESPLog, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPLog10(parm) \
	LP1(0x54, FLOAT, IEEESPLog10, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPPow(exp, arg) \
	LP2(0x3c, FLOAT, IEEESPPow, FLOAT, exp, FLOAT, arg, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPSin(parm) \
	LP1(0x18, FLOAT, IEEESPSin, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPSincos(cosptr, parm) \
	LP2(0x24, FLOAT, IEEESPSincos, FLOAT *, cosptr, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPSinh(parm) \
	LP1(0x28, FLOAT, IEEESPSinh, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPSqrt(parm) \
	LP1(0x40, FLOAT, IEEESPSqrt, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPTan(parm) \
	LP1(0x20, FLOAT, IEEESPTan, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPTanh(parm) \
	LP1(0x30, FLOAT, IEEESPTanh, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#define IEEESPTieee(parm) \
	LP1(0x44, FLOAT, IEEESPTieee, FLOAT, parm, \
	, MATHIEEESINGTRANS_BASE_NAME)

#endif /* PROTO_MATHIEEESINGTRANS_H */
