##begin config
basename	VGAGfx
libbasetype	struct VGAGfxBase
version		45.1
residentpri     8
classptr_field  vsd.vgaclass
classdatatype	struct VGAGfxDriverData
classid         CLID_Hidd_Gfx_VGA
superclass      CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include <hidd/gfx.h>

#include "vgagfx_hidd.h"
#include "vgagfx_bitmap.h"
#include "vgagfx_display.h"
#include "vgagfx_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_Gfx
CopyBox
##end methodlist

##begin class
##begin config
basename VGAGfxDisplay
type hidd
classptr_field vsd.displayclass
classid         CLID_Hidd_Display_VGA
superclass CLID_Hidd_Display
classdatatype struct VGAGfxDisplayData
##end config

##begin methodlist
.interface Root
New
Get
.interface Hidd_Display
CreateObject
SetCursorShape
SetCursorPos
SetCursorVisible
Show
##end methodlist
##end class

##begin class
##begin config
basename VGAGfxBM
type hidd
classptr_field vsd.bmclass
classid         CLID_Hidd_BitMap_VGA
superclass CLID_Hidd_ChunkyBM
classdatatype struct VGAGfxBitMapData
##end config

##begin methodlist
.interface Root
New
Dispose
Set
Get
.interface Hidd_BitMap
SetColors
PutPixel
UpdateRect
##end methodlist
##end class
