### Lists of source files, included by Makefiles

AROS_LIBDRM_CORE_SOURCES = \
            libdrm/arosdrm \
            libdrm/arosdrmmode \

AROS_LIBDRM_NVIDIA_SOURCES = \
            libdrm/nouveau/nouveau \
            libdrm/nouveau/pushbuf \
            libdrm/nouveau/bufctx \
            libdrm/nouveau/abi16 \

AROS_DRM_CORE_SOURCES = \
            drm/display/drm_dp_helper \
            drm/display/drm_dp_mst_topology \
            drm/display/drm_hdmi_helper \
            drm/display/drm_scdc_helper \
            drm/drm_atomic \
            drm/drm_atomic_helper \
            drm/drm_atomic_state_helper \
            drm/drm_atomic_uapi \
            drm/drm_blend \
            drm/drm_bridge \
            drm/drm_color_mgmt \
            drm/drm_connector \
            drm/drm_crtc \
            drm/drm_crtc_helper \
            drm/drm_damage_helper \
            drm/drm_displayid \
            drm/drm_edid \
            drm/drm_eld \
            drm/drm_encoder \
            drm/drm_fourcc \
            drm/drm_framebuffer \
            drm/drm_gem \
            drm/drm_mode_config \
            drm/drm_mode_object \
            drm/drm_modes \
            drm/drm_modeset_helper \
            drm/drm_modeset_lock \
            drm/drm_plane \
            drm/drm_plane_helper \
            drm/drm_print \
            drm/drm_probe_helper \
            drm/drm_property \
            drm/drm_rect \
            drm/drm_self_refresh_helper \
            drm/ttm/ttm_bo \
            drm/ttm/ttm_bo_util \
            drm/ttm/ttm_device \
            drm/ttm/ttm_module \
            drm/ttm/ttm_execbuf_util \
            drm/ttm/ttm_resource \
            drm/ttm/ttm_sys_manager \
            drm/ttm/ttm_tt \
            drm-compat/linux_agp \
            drm-compat/linux_compat \
            drm-compat/linux_dma \
            drm-compat/linux_dma_fence \
            drm-compat/linux_dma_fence_array \
            drm-compat/linux_dma_resv \
            drm-compat/linux_firmware \
            drm-compat/linux_hdmi \
            drm-compat/linux_i2c \
            drm-compat/linux_idr \
            drm-compat/linux_mmio \
            drm-compat/linux_irq \
            drm-compat/linux_mem \
            drm-compat/linux_pci \
            drm-compat/linux_printk \
            drm-compat/linux_sched \
            drm-compat/linux_string \
            drm-compat/linux_time \
            drm-compat/linux_workqueue \
            drm-aros/drm_drv \
            drm-aros/drm_aros_pci \
            drm-aros/drm_stubs \
            drm-aros/ttm_pool_aros \
            drm-aros/nouveau/nouveau_aros_drm \
            drm-aros/nouveau/nouveau_aros_stubs \

AROS_DRM_NVIDIA_SOURCES = \
            drm/nouveau/dispnv04/arb \
            drm/nouveau/dispnv04/crtc \
            drm/nouveau/dispnv04/cursor \
            drm/nouveau/dispnv04/dac \
            drm/nouveau/dispnv04/dfp \
            drm/nouveau/dispnv04/disp \
            drm/nouveau/dispnv04/hw \
            drm/nouveau/dispnv04/nouveau_i2c_encoder \
            drm/nouveau/dispnv04/overlay \
            drm/nouveau/dispnv04/tvmodesnv17 \
            drm/nouveau/dispnv04/tvnv04 \
            drm/nouveau/dispnv04/tvnv17 \
            drm/nouveau/dispnv50/base \
            drm/nouveau/dispnv50/base507c \
            drm/nouveau/dispnv50/base827c \
            drm/nouveau/dispnv50/base907c \
            drm/nouveau/dispnv50/base917c \
            drm/nouveau/dispnv50/core \
            drm/nouveau/dispnv50/core507d \
            drm/nouveau/dispnv50/core827d \
            drm/nouveau/dispnv50/core907d \
            drm/nouveau/dispnv50/core917d \
            drm/nouveau/dispnv50/corec37d \
            drm/nouveau/dispnv50/corec57d \
            drm/nouveau/dispnv50/coreca7d \
            drm/nouveau/dispnv50/curs \
            drm/nouveau/dispnv50/curs507a \
            drm/nouveau/dispnv50/curs907a \
            drm/nouveau/dispnv50/cursc37a \
            drm/nouveau/dispnv50/dac507d \
            drm/nouveau/dispnv50/dac907d \
            drm/nouveau/dispnv50/disp \
            drm/nouveau/dispnv50/head \
            drm/nouveau/dispnv50/head507d \
            drm/nouveau/dispnv50/head827d \
            drm/nouveau/dispnv50/head907d \
            drm/nouveau/dispnv50/head917d \
            drm/nouveau/dispnv50/headc37d \
            drm/nouveau/dispnv50/headc57d \
            drm/nouveau/dispnv50/headca7d \
            drm/nouveau/dispnv50/lut \
            drm/nouveau/dispnv50/oimm \
            drm/nouveau/dispnv50/oimm507b \
            drm/nouveau/dispnv50/ovly \
            drm/nouveau/dispnv50/ovly507e \
            drm/nouveau/dispnv50/ovly827e \
            drm/nouveau/dispnv50/ovly907e \
            drm/nouveau/dispnv50/ovly917e \
            drm/nouveau/dispnv50/pior507d \
            drm/nouveau/dispnv50/sor507d \
            drm/nouveau/dispnv50/sor907d \
            drm/nouveau/dispnv50/sorc37d \
            drm/nouveau/dispnv50/wimm \
            drm/nouveau/dispnv50/wimmc37b \
            drm/nouveau/dispnv50/wndw \
            drm/nouveau/dispnv50/wndwc37e \
            drm/nouveau/dispnv50/wndwc57e \
            drm/nouveau/dispnv50/wndwc67e \
            drm/nouveau/dispnv50/wndwca7e \
            drm/nouveau/gv100_fence \
            drm/nouveau/nouveau_abi16 \
            drm/nouveau/nouveau_bios \
            drm/nouveau/nouveau_bo \
            drm/nouveau/nouveau_bo0039 \
            drm/nouveau/nouveau_bo5039 \
            drm/nouveau/nouveau_bo74c1 \
            drm/nouveau/nouveau_bo85b5 \
            drm/nouveau/nouveau_bo9039 \
            drm/nouveau/nouveau_bo90b5 \
            drm/nouveau/nouveau_boa0b5 \
            drm/nouveau/nouveau_chan \
            drm/nouveau/nouveau_connector \
            drm/nouveau/nouveau_display \
            drm/nouveau/nouveau_dma \
            drm/nouveau/nouveau_dp \
            drm/nouveau/nouveau_drm \
            drm/nouveau/nouveau_fence \
            drm/nouveau/nouveau_gem \
            drm/nouveau/nouveau_mem \
            drm/nouveau/nouveau_nvif \
            drm/nouveau/nouveau_sgdma \
            drm/nouveau/nouveau_ttm \
            drm/nouveau/nouveau_vga \
            drm/nouveau/nouveau_vmm \
            drm/nouveau/nv04_fence \
            drm/nouveau/nv10_fence \
            drm/nouveau/nv17_fence \
            drm/nouveau/nv50_fence \
            drm/nouveau/nv84_fence \
            drm/nouveau/nvc0_fence \
            drm/nouveau/nvif/chan \
            drm/nouveau/nvif/chan506f \
            drm/nouveau/nvif/chan906f \
            drm/nouveau/nvif/chanc36f \
            drm/nouveau/nvif/client \
            drm/nouveau/nvif/conn \
            drm/nouveau/nvif/device \
            drm/nouveau/nvif/disp \
            drm/nouveau/nvif/driver \
            drm/nouveau/nvif/event \
            drm/nouveau/nvif/fifo \
            drm/nouveau/nvif/head \
            drm/nouveau/nvif/mem \
            drm/nouveau/nvif/mmu \
            drm/nouveau/nvif/object \
            drm/nouveau/nvif/outp \
            drm/nouveau/nvif/timer \
            drm/nouveau/nvif/user \
            drm/nouveau/nvif/userc361 \
            drm/nouveau/nvif/vmm \
            drm/nouveau/nvkm/core/client \
            drm/nouveau/nvkm/core/engine \
            drm/nouveau/nvkm/core/enum \
            drm/nouveau/nvkm/core/event \
            drm/nouveau/nvkm/core/firmware \
            drm/nouveau/nvkm/core/gpuobj \
            drm/nouveau/nvkm/core/intr \
            drm/nouveau/nvkm/core/ioctl \
            drm/nouveau/nvkm/core/memory \
            drm/nouveau/nvkm/core/mm \
            drm/nouveau/nvkm/core/object \
            drm/nouveau/nvkm/core/oproxy \
            drm/nouveau/nvkm/core/option \
            drm/nouveau/nvkm/core/ramht \
            drm/nouveau/nvkm/core/subdev \
            drm/nouveau/nvkm/core/uevent \
            drm/nouveau/nvkm/engine/bsp/g84 \
            drm/nouveau/nvkm/engine/ce/ga100 \
            drm/nouveau/nvkm/engine/ce/ga102 \
            drm/nouveau/nvkm/engine/ce/gb202 \
            drm/nouveau/nvkm/engine/ce/gf100 \
            drm/nouveau/nvkm/engine/ce/gk104 \
            drm/nouveau/nvkm/engine/ce/gm107 \
            drm/nouveau/nvkm/engine/ce/gm200 \
            drm/nouveau/nvkm/engine/ce/gp100 \
            drm/nouveau/nvkm/engine/ce/gp102 \
            drm/nouveau/nvkm/engine/ce/gt215 \
            drm/nouveau/nvkm/engine/ce/gv100 \
            drm/nouveau/nvkm/engine/ce/tu102 \
            drm/nouveau/nvkm/engine/cipher/g84 \
            drm/nouveau/nvkm/engine/device/base \
            drm/nouveau/nvkm/engine/device/ctrl \
            drm/nouveau/nvkm/engine/device/pci \
            drm/nouveau/nvkm/engine/device/user \
            drm/nouveau/nvkm/engine/disp/base \
            drm/nouveau/nvkm/engine/disp/chan \
            drm/nouveau/nvkm/engine/disp/conn \
            drm/nouveau/nvkm/engine/disp/dp \
            drm/nouveau/nvkm/engine/disp/g84 \
            drm/nouveau/nvkm/engine/disp/g94 \
            drm/nouveau/nvkm/engine/disp/ga102 \
            drm/nouveau/nvkm/engine/disp/gf119 \
            drm/nouveau/nvkm/engine/disp/gk104 \
            drm/nouveau/nvkm/engine/disp/gk110 \
            drm/nouveau/nvkm/engine/disp/gm107 \
            drm/nouveau/nvkm/engine/disp/gm200 \
            drm/nouveau/nvkm/engine/disp/gp100 \
            drm/nouveau/nvkm/engine/disp/gp102 \
            drm/nouveau/nvkm/engine/disp/gt200 \
            drm/nouveau/nvkm/engine/disp/gt215 \
            drm/nouveau/nvkm/engine/disp/gv100 \
            drm/nouveau/nvkm/engine/disp/hdmi \
            drm/nouveau/nvkm/engine/disp/head \
            drm/nouveau/nvkm/engine/disp/ior \
            drm/nouveau/nvkm/engine/disp/mcp77 \
            drm/nouveau/nvkm/engine/disp/mcp89 \
            drm/nouveau/nvkm/engine/disp/nv04 \
            drm/nouveau/nvkm/engine/disp/nv50 \
            drm/nouveau/nvkm/engine/disp/outp \
            drm/nouveau/nvkm/engine/disp/tu102 \
            drm/nouveau/nvkm/engine/disp/uconn \
            drm/nouveau/nvkm/engine/disp/udisp \
            drm/nouveau/nvkm/engine/disp/uhead \
            drm/nouveau/nvkm/engine/disp/uoutp \
            drm/nouveau/nvkm/engine/disp/vga \
            drm/nouveau/nvkm/engine/dma/base \
            drm/nouveau/nvkm/engine/dma/gf100 \
            drm/nouveau/nvkm/engine/dma/gf119 \
            drm/nouveau/nvkm/engine/dma/gv100 \
            drm/nouveau/nvkm/engine/dma/nv04 \
            drm/nouveau/nvkm/engine/dma/nv50 \
            drm/nouveau/nvkm/engine/dma/user \
            drm/nouveau/nvkm/engine/dma/usergf100 \
            drm/nouveau/nvkm/engine/dma/usergf119 \
            drm/nouveau/nvkm/engine/dma/usergv100 \
            drm/nouveau/nvkm/engine/dma/usernv04 \
            drm/nouveau/nvkm/engine/dma/usernv50 \
            drm/nouveau/nvkm/engine/falcon \
            drm/nouveau/nvkm/engine/fifo/base \
            drm/nouveau/nvkm/engine/fifo/cgrp \
            drm/nouveau/nvkm/engine/fifo/chan \
            drm/nouveau/nvkm/engine/fifo/chid \
            drm/nouveau/nvkm/engine/fifo/g84 \
            drm/nouveau/nvkm/engine/fifo/g98 \
            drm/nouveau/nvkm/engine/fifo/ga100 \
            drm/nouveau/nvkm/engine/fifo/ga102 \
            drm/nouveau/nvkm/engine/fifo/gb202 \
            drm/nouveau/nvkm/engine/fifo/gf100 \
            drm/nouveau/nvkm/engine/fifo/gk104 \
            drm/nouveau/nvkm/engine/fifo/gk110 \
            drm/nouveau/nvkm/engine/fifo/gk208 \
            drm/nouveau/nvkm/engine/fifo/gk20a \
            drm/nouveau/nvkm/engine/fifo/gm107 \
            drm/nouveau/nvkm/engine/fifo/gm200 \
            drm/nouveau/nvkm/engine/fifo/gp100 \
            drm/nouveau/nvkm/engine/fifo/gv100 \
            drm/nouveau/nvkm/engine/fifo/nv04 \
            drm/nouveau/nvkm/engine/fifo/nv10 \
            drm/nouveau/nvkm/engine/fifo/nv17 \
            drm/nouveau/nvkm/engine/fifo/nv40 \
            drm/nouveau/nvkm/engine/fifo/nv50 \
            drm/nouveau/nvkm/engine/fifo/runl \
            drm/nouveau/nvkm/engine/fifo/runq \
            drm/nouveau/nvkm/engine/fifo/tu102 \
            drm/nouveau/nvkm/engine/fifo/ucgrp \
            drm/nouveau/nvkm/engine/fifo/uchan \
            drm/nouveau/nvkm/engine/gr/base \
            drm/nouveau/nvkm/engine/gr/ctxga102 \
            drm/nouveau/nvkm/engine/gr/ctxgf100 \
            drm/nouveau/nvkm/engine/gr/ctxgf104 \
            drm/nouveau/nvkm/engine/gr/ctxgf108 \
            drm/nouveau/nvkm/engine/gr/ctxgf110 \
            drm/nouveau/nvkm/engine/gr/ctxgf117 \
            drm/nouveau/nvkm/engine/gr/ctxgf119 \
            drm/nouveau/nvkm/engine/gr/ctxgk104 \
            drm/nouveau/nvkm/engine/gr/ctxgk110 \
            drm/nouveau/nvkm/engine/gr/ctxgk110b \
            drm/nouveau/nvkm/engine/gr/ctxgk208 \
            drm/nouveau/nvkm/engine/gr/ctxgk20a \
            drm/nouveau/nvkm/engine/gr/ctxgm107 \
            drm/nouveau/nvkm/engine/gr/ctxgm200 \
            drm/nouveau/nvkm/engine/gr/ctxgm20b \
            drm/nouveau/nvkm/engine/gr/ctxgp100 \
            drm/nouveau/nvkm/engine/gr/ctxgp102 \
            drm/nouveau/nvkm/engine/gr/ctxgp104 \
            drm/nouveau/nvkm/engine/gr/ctxgp107 \
            drm/nouveau/nvkm/engine/gr/ctxgv100 \
            drm/nouveau/nvkm/engine/gr/ctxnv40 \
            drm/nouveau/nvkm/engine/gr/ctxnv50 \
            drm/nouveau/nvkm/engine/gr/ctxtu102 \
            drm/nouveau/nvkm/engine/gr/g84 \
            drm/nouveau/nvkm/engine/gr/ga102 \
            drm/nouveau/nvkm/engine/gr/gf100 \
            drm/nouveau/nvkm/engine/gr/gf104 \
            drm/nouveau/nvkm/engine/gr/gf108 \
            drm/nouveau/nvkm/engine/gr/gf110 \
            drm/nouveau/nvkm/engine/gr/gf117 \
            drm/nouveau/nvkm/engine/gr/gf119 \
            drm/nouveau/nvkm/engine/gr/gk104 \
            drm/nouveau/nvkm/engine/gr/gk110 \
            drm/nouveau/nvkm/engine/gr/gk110b \
            drm/nouveau/nvkm/engine/gr/gk208 \
            drm/nouveau/nvkm/engine/gr/gk20a \
            drm/nouveau/nvkm/engine/gr/gm107 \
            drm/nouveau/nvkm/engine/gr/gm200 \
            drm/nouveau/nvkm/engine/gr/gm20b \
            drm/nouveau/nvkm/engine/gr/gp100 \
            drm/nouveau/nvkm/engine/gr/gp102 \
            drm/nouveau/nvkm/engine/gr/gp104 \
            drm/nouveau/nvkm/engine/gr/gp107 \
            drm/nouveau/nvkm/engine/gr/gp108 \
            drm/nouveau/nvkm/engine/gr/gp10b \
            drm/nouveau/nvkm/engine/gr/gt200 \
            drm/nouveau/nvkm/engine/gr/gt215 \
            drm/nouveau/nvkm/engine/gr/gv100 \
            drm/nouveau/nvkm/engine/gr/mcp79 \
            drm/nouveau/nvkm/engine/gr/mcp89 \
            drm/nouveau/nvkm/engine/gr/nv04 \
            drm/nouveau/nvkm/engine/gr/nv10 \
            drm/nouveau/nvkm/engine/gr/nv15 \
            drm/nouveau/nvkm/engine/gr/nv17 \
            drm/nouveau/nvkm/engine/gr/nv20 \
            drm/nouveau/nvkm/engine/gr/nv25 \
            drm/nouveau/nvkm/engine/gr/nv2a \
            drm/nouveau/nvkm/engine/gr/nv30 \
            drm/nouveau/nvkm/engine/gr/nv34 \
            drm/nouveau/nvkm/engine/gr/nv35 \
            drm/nouveau/nvkm/engine/gr/nv40 \
            drm/nouveau/nvkm/engine/gr/nv44 \
            drm/nouveau/nvkm/engine/gr/nv50 \
            drm/nouveau/nvkm/engine/gr/tu102 \
            drm/nouveau/nvkm/engine/mpeg/g84 \
            drm/nouveau/nvkm/engine/mpeg/nv31 \
            drm/nouveau/nvkm/engine/mpeg/nv40 \
            drm/nouveau/nvkm/engine/mpeg/nv44 \
            drm/nouveau/nvkm/engine/mpeg/nv50 \
            drm/nouveau/nvkm/engine/mspdec/base \
            drm/nouveau/nvkm/engine/mspdec/g98 \
            drm/nouveau/nvkm/engine/mspdec/gf100 \
            drm/nouveau/nvkm/engine/mspdec/gk104 \
            drm/nouveau/nvkm/engine/mspdec/gt215 \
            drm/nouveau/nvkm/engine/msppp/base \
            drm/nouveau/nvkm/engine/msppp/g98 \
            drm/nouveau/nvkm/engine/msppp/gf100 \
            drm/nouveau/nvkm/engine/msppp/gt215 \
            drm/nouveau/nvkm/engine/msvld/base \
            drm/nouveau/nvkm/engine/msvld/g98 \
            drm/nouveau/nvkm/engine/msvld/gf100 \
            drm/nouveau/nvkm/engine/msvld/gk104 \
            drm/nouveau/nvkm/engine/msvld/gt215 \
            drm/nouveau/nvkm/engine/msvld/mcp89 \
            drm/nouveau/nvkm/engine/nvdec/base \
            drm/nouveau/nvkm/engine/nvdec/ga102 \
            drm/nouveau/nvkm/engine/nvdec/gm107 \
            drm/nouveau/nvkm/engine/nvdec/tu102 \
            drm/nouveau/nvkm/engine/nvenc/base \
            drm/nouveau/nvkm/engine/nvenc/gm107 \
            drm/nouveau/nvkm/engine/nvenc/tu102 \
            drm/nouveau/nvkm/engine/sec/g98 \
            drm/nouveau/nvkm/engine/sec2/base \
            drm/nouveau/nvkm/engine/sec2/ga102 \
            drm/nouveau/nvkm/engine/sec2/gp102 \
            drm/nouveau/nvkm/engine/sec2/gp108 \
            drm/nouveau/nvkm/engine/sec2/r535 \
            drm/nouveau/nvkm/engine/sec2/tu102 \
            drm/nouveau/nvkm/engine/sw/base \
            drm/nouveau/nvkm/engine/sw/chan \
            drm/nouveau/nvkm/engine/sw/gf100 \
            drm/nouveau/nvkm/engine/sw/nv04 \
            drm/nouveau/nvkm/engine/sw/nv10 \
            drm/nouveau/nvkm/engine/sw/nv50 \
            drm/nouveau/nvkm/engine/sw/nvsw \
            drm/nouveau/nvkm/engine/vp/g84 \
            drm/nouveau/nvkm/engine/xtensa \
            drm/nouveau/nvkm/falcon/base \
            drm/nouveau/nvkm/falcon/cmdq \
            drm/nouveau/nvkm/falcon/fw \
            drm/nouveau/nvkm/falcon/ga100 \
            drm/nouveau/nvkm/falcon/ga102 \
            drm/nouveau/nvkm/falcon/gm200 \
            drm/nouveau/nvkm/falcon/gp102 \
            drm/nouveau/nvkm/falcon/msgq \
            drm/nouveau/nvkm/falcon/qmgr \
            drm/nouveau/nvkm/falcon/tu102 \
            drm/nouveau/nvkm/falcon/v1 \
            drm/nouveau/nvkm/nvfw/acr \
            drm/nouveau/nvkm/nvfw/flcn \
            drm/nouveau/nvkm/nvfw/fw \
            drm/nouveau/nvkm/nvfw/hs \
            drm/nouveau/nvkm/nvfw/ls \
            drm/nouveau/nvkm/subdev/acr/base \
            drm/nouveau/nvkm/subdev/acr/ga100 \
            drm/nouveau/nvkm/subdev/acr/ga102 \
            drm/nouveau/nvkm/subdev/acr/gm200 \
            drm/nouveau/nvkm/subdev/acr/gm20b \
            drm/nouveau/nvkm/subdev/acr/gp102 \
            drm/nouveau/nvkm/subdev/acr/gp108 \
            drm/nouveau/nvkm/subdev/acr/gp10b \
            drm/nouveau/nvkm/subdev/acr/gv100 \
            drm/nouveau/nvkm/subdev/acr/lsfw \
            drm/nouveau/nvkm/subdev/acr/tu102 \
            drm/nouveau/nvkm/subdev/bar/base \
            drm/nouveau/nvkm/subdev/bar/g84 \
            drm/nouveau/nvkm/subdev/bar/gf100 \
            drm/nouveau/nvkm/subdev/bar/gk20a \
            drm/nouveau/nvkm/subdev/bar/gm107 \
            drm/nouveau/nvkm/subdev/bar/gm20b \
            drm/nouveau/nvkm/subdev/bar/nv50 \
            drm/nouveau/nvkm/subdev/bar/tu102 \
            drm/nouveau/nvkm/subdev/bios/M0203 \
            drm/nouveau/nvkm/subdev/bios/M0205 \
            drm/nouveau/nvkm/subdev/bios/M0209 \
            drm/nouveau/nvkm/subdev/bios/P0260 \
            drm/nouveau/nvkm/subdev/bios/base \
            drm/nouveau/nvkm/subdev/bios/bit \
            drm/nouveau/nvkm/subdev/bios/boost \
            drm/nouveau/nvkm/subdev/bios/conn \
            drm/nouveau/nvkm/subdev/bios/cstep \
            drm/nouveau/nvkm/subdev/bios/dcb \
            drm/nouveau/nvkm/subdev/bios/disp \
            drm/nouveau/nvkm/subdev/bios/dp \
            drm/nouveau/nvkm/subdev/bios/extdev \
            drm/nouveau/nvkm/subdev/bios/fan \
            drm/nouveau/nvkm/subdev/bios/gpio \
            drm/nouveau/nvkm/subdev/bios/i2c \
            drm/nouveau/nvkm/subdev/bios/iccsense \
            drm/nouveau/nvkm/subdev/bios/image \
            drm/nouveau/nvkm/subdev/bios/init \
            drm/nouveau/nvkm/subdev/bios/mxm \
            drm/nouveau/nvkm/subdev/bios/npde \
            drm/nouveau/nvkm/subdev/bios/pcir \
            drm/nouveau/nvkm/subdev/bios/perf \
            drm/nouveau/nvkm/subdev/bios/pll \
            drm/nouveau/nvkm/subdev/bios/pmu \
            drm/nouveau/nvkm/subdev/bios/power_budget \
            drm/nouveau/nvkm/subdev/bios/ramcfg \
            drm/nouveau/nvkm/subdev/bios/rammap \
            drm/nouveau/nvkm/subdev/bios/shadow \
            drm/nouveau/nvkm/subdev/bios/shadowacpi \
            drm/nouveau/nvkm/subdev/bios/shadowof \
            drm/nouveau/nvkm/subdev/bios/shadowpci \
            drm/nouveau/nvkm/subdev/bios/shadowramin \
            drm/nouveau/nvkm/subdev/bios/shadowrom \
            drm/nouveau/nvkm/subdev/bios/therm \
            drm/nouveau/nvkm/subdev/bios/timing \
            drm/nouveau/nvkm/subdev/bios/vmap \
            drm/nouveau/nvkm/subdev/bios/volt \
            drm/nouveau/nvkm/subdev/bios/vpstate \
            drm/nouveau/nvkm/subdev/bios/xpio \
            drm/nouveau/nvkm/subdev/bus/base \
            drm/nouveau/nvkm/subdev/bus/g94 \
            drm/nouveau/nvkm/subdev/bus/gf100 \
            drm/nouveau/nvkm/subdev/bus/hwsq \
            drm/nouveau/nvkm/subdev/bus/nv04 \
            drm/nouveau/nvkm/subdev/bus/nv31 \
            drm/nouveau/nvkm/subdev/bus/nv50 \
            drm/nouveau/nvkm/subdev/clk/base \
            drm/nouveau/nvkm/subdev/clk/g84 \
            drm/nouveau/nvkm/subdev/clk/gf100 \
            drm/nouveau/nvkm/subdev/clk/gk104 \
            drm/nouveau/nvkm/subdev/clk/gk20a \
            drm/nouveau/nvkm/subdev/clk/gm20b \
            drm/nouveau/nvkm/subdev/clk/gt215 \
            drm/nouveau/nvkm/subdev/clk/mcp77 \
            drm/nouveau/nvkm/subdev/clk/nv04 \
            drm/nouveau/nvkm/subdev/clk/nv40 \
            drm/nouveau/nvkm/subdev/clk/nv50 \
            drm/nouveau/nvkm/subdev/clk/pllgt215 \
            drm/nouveau/nvkm/subdev/clk/pllnv04 \
            drm/nouveau/nvkm/subdev/devinit/base \
            drm/nouveau/nvkm/subdev/devinit/g84 \
            drm/nouveau/nvkm/subdev/devinit/g98 \
            drm/nouveau/nvkm/subdev/devinit/ga100 \
            drm/nouveau/nvkm/subdev/devinit/gf100 \
            drm/nouveau/nvkm/subdev/devinit/gm107 \
            drm/nouveau/nvkm/subdev/devinit/gm200 \
            drm/nouveau/nvkm/subdev/devinit/gt215 \
            drm/nouveau/nvkm/subdev/devinit/gv100 \
            drm/nouveau/nvkm/subdev/devinit/mcp89 \
            drm/nouveau/nvkm/subdev/devinit/nv04 \
            drm/nouveau/nvkm/subdev/devinit/nv05 \
            drm/nouveau/nvkm/subdev/devinit/nv10 \
            drm/nouveau/nvkm/subdev/devinit/nv1a \
            drm/nouveau/nvkm/subdev/devinit/nv20 \
            drm/nouveau/nvkm/subdev/devinit/nv50 \
            drm/nouveau/nvkm/subdev/devinit/r535 \
            drm/nouveau/nvkm/subdev/devinit/tu102 \
            drm/nouveau/nvkm/subdev/fault/base \
            drm/nouveau/nvkm/subdev/fault/gp100 \
            drm/nouveau/nvkm/subdev/fault/gp10b \
            drm/nouveau/nvkm/subdev/fault/gv100 \
            drm/nouveau/nvkm/subdev/fault/tu102 \
            drm/nouveau/nvkm/subdev/fault/user \
            drm/nouveau/nvkm/subdev/fb/base \
            drm/nouveau/nvkm/subdev/fb/g84 \
            drm/nouveau/nvkm/subdev/fb/ga100 \
            drm/nouveau/nvkm/subdev/fb/ga102 \
            drm/nouveau/nvkm/subdev/fb/gb100 \
            drm/nouveau/nvkm/subdev/fb/gb202 \
            drm/nouveau/nvkm/subdev/fb/gddr3 \
            drm/nouveau/nvkm/subdev/fb/gddr5 \
            drm/nouveau/nvkm/subdev/fb/gf100 \
            drm/nouveau/nvkm/subdev/fb/gf108 \
            drm/nouveau/nvkm/subdev/fb/gh100 \
            drm/nouveau/nvkm/subdev/fb/gk104 \
            drm/nouveau/nvkm/subdev/fb/gk110 \
            drm/nouveau/nvkm/subdev/fb/gk20a \
            drm/nouveau/nvkm/subdev/fb/gm107 \
            drm/nouveau/nvkm/subdev/fb/gm200 \
            drm/nouveau/nvkm/subdev/fb/gm20b \
            drm/nouveau/nvkm/subdev/fb/gp100 \
            drm/nouveau/nvkm/subdev/fb/gp102 \
            drm/nouveau/nvkm/subdev/fb/gp10b \
            drm/nouveau/nvkm/subdev/fb/gt215 \
            drm/nouveau/nvkm/subdev/fb/gv100 \
            drm/nouveau/nvkm/subdev/fb/mcp77 \
            drm/nouveau/nvkm/subdev/fb/mcp89 \
            drm/nouveau/nvkm/subdev/fb/nv04 \
            drm/nouveau/nvkm/subdev/fb/nv10 \
            drm/nouveau/nvkm/subdev/fb/nv1a \
            drm/nouveau/nvkm/subdev/fb/nv20 \
            drm/nouveau/nvkm/subdev/fb/nv25 \
            drm/nouveau/nvkm/subdev/fb/nv30 \
            drm/nouveau/nvkm/subdev/fb/nv35 \
            drm/nouveau/nvkm/subdev/fb/nv36 \
            drm/nouveau/nvkm/subdev/fb/nv40 \
            drm/nouveau/nvkm/subdev/fb/nv41 \
            drm/nouveau/nvkm/subdev/fb/nv44 \
            drm/nouveau/nvkm/subdev/fb/nv46 \
            drm/nouveau/nvkm/subdev/fb/nv47 \
            drm/nouveau/nvkm/subdev/fb/nv49 \
            drm/nouveau/nvkm/subdev/fb/nv4e \
            drm/nouveau/nvkm/subdev/fb/nv50 \
            drm/nouveau/nvkm/subdev/fb/r535 \
            drm/nouveau/nvkm/subdev/fb/ram \
            drm/nouveau/nvkm/subdev/fb/ramgf100 \
            drm/nouveau/nvkm/subdev/fb/ramgf108 \
            drm/nouveau/nvkm/subdev/fb/ramgk104 \
            drm/nouveau/nvkm/subdev/fb/ramgm107 \
            drm/nouveau/nvkm/subdev/fb/ramgm200 \
            drm/nouveau/nvkm/subdev/fb/ramgp100 \
            drm/nouveau/nvkm/subdev/fb/ramgp102 \
            drm/nouveau/nvkm/subdev/fb/ramgt215 \
            drm/nouveau/nvkm/subdev/fb/rammcp77 \
            drm/nouveau/nvkm/subdev/fb/ramnv04 \
            drm/nouveau/nvkm/subdev/fb/ramnv10 \
            drm/nouveau/nvkm/subdev/fb/ramnv1a \
            drm/nouveau/nvkm/subdev/fb/ramnv20 \
            drm/nouveau/nvkm/subdev/fb/ramnv40 \
            drm/nouveau/nvkm/subdev/fb/ramnv41 \
            drm/nouveau/nvkm/subdev/fb/ramnv44 \
            drm/nouveau/nvkm/subdev/fb/ramnv49 \
            drm/nouveau/nvkm/subdev/fb/ramnv4e \
            drm/nouveau/nvkm/subdev/fb/ramnv50 \
            drm/nouveau/nvkm/subdev/fb/sddr2 \
            drm/nouveau/nvkm/subdev/fb/sddr3 \
            drm/nouveau/nvkm/subdev/fb/tu102 \
            drm/nouveau/nvkm/subdev/fsp/base \
            drm/nouveau/nvkm/subdev/fsp/gb100 \
            drm/nouveau/nvkm/subdev/fsp/gb202 \
            drm/nouveau/nvkm/subdev/fsp/gh100 \
            drm/nouveau/nvkm/subdev/fuse/base \
            drm/nouveau/nvkm/subdev/fuse/gf100 \
            drm/nouveau/nvkm/subdev/fuse/gm107 \
            drm/nouveau/nvkm/subdev/fuse/nv50 \
            drm/nouveau/nvkm/subdev/gpio/base \
            drm/nouveau/nvkm/subdev/gpio/g94 \
            drm/nouveau/nvkm/subdev/gpio/ga102 \
            drm/nouveau/nvkm/subdev/gpio/gf119 \
            drm/nouveau/nvkm/subdev/gpio/gk104 \
            drm/nouveau/nvkm/subdev/gpio/nv10 \
            drm/nouveau/nvkm/subdev/gpio/nv50 \
            drm/nouveau/nvkm/subdev/gsp/ad102 \
            drm/nouveau/nvkm/subdev/gsp/base \
            drm/nouveau/nvkm/subdev/gsp/fwsec \
            drm/nouveau/nvkm/subdev/gsp/ga100 \
            drm/nouveau/nvkm/subdev/gsp/ga102 \
            drm/nouveau/nvkm/subdev/gsp/gb100 \
            drm/nouveau/nvkm/subdev/gsp/gb202 \
            drm/nouveau/nvkm/subdev/gsp/gh100 \
            drm/nouveau/nvkm/subdev/gsp/gv100 \
            drm/nouveau/nvkm/subdev/gsp/rm/ad10x \
            drm/nouveau/nvkm/subdev/gsp/rm/client \
            drm/nouveau/nvkm/subdev/gsp/rm/engine \
            drm/nouveau/nvkm/subdev/gsp/rm/ga100 \
            drm/nouveau/nvkm/subdev/gsp/rm/ga1xx \
            drm/nouveau/nvkm/subdev/gsp/rm/gb10x \
            drm/nouveau/nvkm/subdev/gsp/rm/gb20x \
            drm/nouveau/nvkm/subdev/gsp/rm/gh100 \
            drm/nouveau/nvkm/subdev/gsp/rm/gr \
            drm/nouveau/nvkm/subdev/gsp/rm/nvdec \
            drm/nouveau/nvkm/subdev/gsp/rm/nvenc \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/alloc \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/bar \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/ce \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/client \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/ctrl \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/device \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/disp \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/fbsr \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/fifo \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/gr \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/gsp \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/nvdec \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/nvenc \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/nvjpg \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/ofa \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/rm \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/rpc \
            drm/nouveau/nvkm/subdev/gsp/rm/r535/vmm \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/client \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/disp \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/fbsr \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/fifo \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/gr \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/gsp \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/ofa \
            drm/nouveau/nvkm/subdev/gsp/rm/r570/rm \
            drm/nouveau/nvkm/subdev/gsp/rm/tu1xx \
            drm/nouveau/nvkm/subdev/gsp/tu102 \
            drm/nouveau/nvkm/subdev/gsp/tu116 \
            drm/nouveau/nvkm/subdev/i2c/anx9805 \
            drm/nouveau/nvkm/subdev/i2c/auxch \
            drm/nouveau/nvkm/subdev/i2c/auxg94 \
            drm/nouveau/nvkm/subdev/i2c/auxgf119 \
            drm/nouveau/nvkm/subdev/i2c/auxgm200 \
            drm/nouveau/nvkm/subdev/i2c/base \
            drm/nouveau/nvkm/subdev/i2c/bit \
            drm/nouveau/nvkm/subdev/i2c/bus \
            drm/nouveau/nvkm/subdev/i2c/busgf119 \
            drm/nouveau/nvkm/subdev/i2c/busnv04 \
            drm/nouveau/nvkm/subdev/i2c/busnv4e \
            drm/nouveau/nvkm/subdev/i2c/busnv50 \
            drm/nouveau/nvkm/subdev/i2c/g94 \
            drm/nouveau/nvkm/subdev/i2c/gf117 \
            drm/nouveau/nvkm/subdev/i2c/gf119 \
            drm/nouveau/nvkm/subdev/i2c/gk104 \
            drm/nouveau/nvkm/subdev/i2c/gk110 \
            drm/nouveau/nvkm/subdev/i2c/gm200 \
            drm/nouveau/nvkm/subdev/i2c/nv04 \
            drm/nouveau/nvkm/subdev/i2c/nv4e \
            drm/nouveau/nvkm/subdev/i2c/nv50 \
            drm/nouveau/nvkm/subdev/i2c/pad \
            drm/nouveau/nvkm/subdev/i2c/padg94 \
            drm/nouveau/nvkm/subdev/i2c/padgf119 \
            drm/nouveau/nvkm/subdev/i2c/padgm200 \
            drm/nouveau/nvkm/subdev/i2c/padnv04 \
            drm/nouveau/nvkm/subdev/i2c/padnv4e \
            drm/nouveau/nvkm/subdev/i2c/padnv50 \
            drm/nouveau/nvkm/subdev/iccsense/base \
            drm/nouveau/nvkm/subdev/iccsense/gf100 \
            drm/nouveau/nvkm/subdev/instmem/base \
            drm/nouveau/nvkm/subdev/instmem/gh100 \
            drm/nouveau/nvkm/subdev/instmem/gk20a \
            drm/nouveau/nvkm/subdev/instmem/nv04 \
            drm/nouveau/nvkm/subdev/instmem/nv40 \
            drm/nouveau/nvkm/subdev/instmem/nv50 \
            drm/nouveau/nvkm/subdev/ltc/base \
            drm/nouveau/nvkm/subdev/ltc/ga102 \
            drm/nouveau/nvkm/subdev/ltc/gf100 \
            drm/nouveau/nvkm/subdev/ltc/gk104 \
            drm/nouveau/nvkm/subdev/ltc/gm107 \
            drm/nouveau/nvkm/subdev/ltc/gm200 \
            drm/nouveau/nvkm/subdev/ltc/gp100 \
            drm/nouveau/nvkm/subdev/ltc/gp102 \
            drm/nouveau/nvkm/subdev/ltc/gp10b \
            drm/nouveau/nvkm/subdev/mc/base \
            drm/nouveau/nvkm/subdev/mc/g84 \
            drm/nouveau/nvkm/subdev/mc/g98 \
            drm/nouveau/nvkm/subdev/mc/ga100 \
            drm/nouveau/nvkm/subdev/mc/gf100 \
            drm/nouveau/nvkm/subdev/mc/gk104 \
            drm/nouveau/nvkm/subdev/mc/gk20a \
            drm/nouveau/nvkm/subdev/mc/gp100 \
            drm/nouveau/nvkm/subdev/mc/gp10b \
            drm/nouveau/nvkm/subdev/mc/gt215 \
            drm/nouveau/nvkm/subdev/mc/nv04 \
            drm/nouveau/nvkm/subdev/mc/nv11 \
            drm/nouveau/nvkm/subdev/mc/nv17 \
            drm/nouveau/nvkm/subdev/mc/nv44 \
            drm/nouveau/nvkm/subdev/mc/nv50 \
            drm/nouveau/nvkm/subdev/mmu/base \
            drm/nouveau/nvkm/subdev/mmu/g84 \
            drm/nouveau/nvkm/subdev/mmu/gf100 \
            drm/nouveau/nvkm/subdev/mmu/gh100 \
            drm/nouveau/nvkm/subdev/mmu/gk104 \
            drm/nouveau/nvkm/subdev/mmu/gk20a \
            drm/nouveau/nvkm/subdev/mmu/gm200 \
            drm/nouveau/nvkm/subdev/mmu/gm20b \
            drm/nouveau/nvkm/subdev/mmu/gp100 \
            drm/nouveau/nvkm/subdev/mmu/gp10b \
            drm/nouveau/nvkm/subdev/mmu/gv100 \
            drm/nouveau/nvkm/subdev/mmu/mcp77 \
            drm/nouveau/nvkm/subdev/mmu/mem \
            drm/nouveau/nvkm/subdev/mmu/memgf100 \
            drm/nouveau/nvkm/subdev/mmu/memnv04 \
            drm/nouveau/nvkm/subdev/mmu/memnv50 \
            drm/nouveau/nvkm/subdev/mmu/nv04 \
            drm/nouveau/nvkm/subdev/mmu/nv41 \
            drm/nouveau/nvkm/subdev/mmu/nv44 \
            drm/nouveau/nvkm/subdev/mmu/nv50 \
            drm/nouveau/nvkm/subdev/mmu/tu102 \
            drm/nouveau/nvkm/subdev/mmu/umem \
            drm/nouveau/nvkm/subdev/mmu/ummu \
            drm/nouveau/nvkm/subdev/mmu/uvmm \
            drm/nouveau/nvkm/subdev/mmu/vmm \
            drm/nouveau/nvkm/subdev/mmu/vmmgf100 \
            drm/nouveau/nvkm/subdev/mmu/vmmgh100 \
            drm/nouveau/nvkm/subdev/mmu/vmmgk104 \
            drm/nouveau/nvkm/subdev/mmu/vmmgk20a \
            drm/nouveau/nvkm/subdev/mmu/vmmgm200 \
            drm/nouveau/nvkm/subdev/mmu/vmmgm20b \
            drm/nouveau/nvkm/subdev/mmu/vmmgp100 \
            drm/nouveau/nvkm/subdev/mmu/vmmgp10b \
            drm/nouveau/nvkm/subdev/mmu/vmmgv100 \
            drm/nouveau/nvkm/subdev/mmu/vmmmcp77 \
            drm/nouveau/nvkm/subdev/mmu/vmmnv04 \
            drm/nouveau/nvkm/subdev/mmu/vmmnv41 \
            drm/nouveau/nvkm/subdev/mmu/vmmnv44 \
            drm/nouveau/nvkm/subdev/mmu/vmmnv50 \
            drm/nouveau/nvkm/subdev/mmu/vmmtu102 \
            drm/nouveau/nvkm/subdev/mxm/base \
            drm/nouveau/nvkm/subdev/mxm/mxms \
            drm/nouveau/nvkm/subdev/mxm/nv50 \
            drm/nouveau/nvkm/subdev/pci/agp \
            drm/nouveau/nvkm/subdev/pci/base \
            drm/nouveau/nvkm/subdev/pci/g84 \
            drm/nouveau/nvkm/subdev/pci/g92 \
            drm/nouveau/nvkm/subdev/pci/g94 \
            drm/nouveau/nvkm/subdev/pci/gf100 \
            drm/nouveau/nvkm/subdev/pci/gf106 \
            drm/nouveau/nvkm/subdev/pci/gh100 \
            drm/nouveau/nvkm/subdev/pci/gk104 \
            drm/nouveau/nvkm/subdev/pci/gp100 \
            drm/nouveau/nvkm/subdev/pci/nv04 \
            drm/nouveau/nvkm/subdev/pci/nv40 \
            drm/nouveau/nvkm/subdev/pci/nv46 \
            drm/nouveau/nvkm/subdev/pci/nv4c \
            drm/nouveau/nvkm/subdev/pci/pcie \
            drm/nouveau/nvkm/subdev/pmu/base \
            drm/nouveau/nvkm/subdev/pmu/gf100 \
            drm/nouveau/nvkm/subdev/pmu/gf119 \
            drm/nouveau/nvkm/subdev/pmu/gk104 \
            drm/nouveau/nvkm/subdev/pmu/gk110 \
            drm/nouveau/nvkm/subdev/pmu/gk208 \
            drm/nouveau/nvkm/subdev/pmu/gk20a \
            drm/nouveau/nvkm/subdev/pmu/gm107 \
            drm/nouveau/nvkm/subdev/pmu/gm200 \
            drm/nouveau/nvkm/subdev/pmu/gm20b \
            drm/nouveau/nvkm/subdev/pmu/gp102 \
            drm/nouveau/nvkm/subdev/pmu/gp10b \
            drm/nouveau/nvkm/subdev/pmu/gt215 \
            drm/nouveau/nvkm/subdev/pmu/memx \
            drm/nouveau/nvkm/subdev/privring/gf100 \
            drm/nouveau/nvkm/subdev/privring/gf117 \
            drm/nouveau/nvkm/subdev/privring/gk104 \
            drm/nouveau/nvkm/subdev/privring/gk20a \
            drm/nouveau/nvkm/subdev/privring/gm200 \
            drm/nouveau/nvkm/subdev/privring/gp10b \
            drm/nouveau/nvkm/subdev/therm/base \
            drm/nouveau/nvkm/subdev/therm/fan \
            drm/nouveau/nvkm/subdev/therm/fannil \
            drm/nouveau/nvkm/subdev/therm/fanpwm \
            drm/nouveau/nvkm/subdev/therm/fantog \
            drm/nouveau/nvkm/subdev/therm/g84 \
            drm/nouveau/nvkm/subdev/therm/gf100 \
            drm/nouveau/nvkm/subdev/therm/gf119 \
            drm/nouveau/nvkm/subdev/therm/gk104 \
            drm/nouveau/nvkm/subdev/therm/gm107 \
            drm/nouveau/nvkm/subdev/therm/gm200 \
            drm/nouveau/nvkm/subdev/therm/gp100 \
            drm/nouveau/nvkm/subdev/therm/gt215 \
            drm/nouveau/nvkm/subdev/therm/ic \
            drm/nouveau/nvkm/subdev/therm/nv40 \
            drm/nouveau/nvkm/subdev/therm/nv50 \
            drm/nouveau/nvkm/subdev/therm/temp \
            drm/nouveau/nvkm/subdev/timer/base \
            drm/nouveau/nvkm/subdev/timer/gk20a \
            drm/nouveau/nvkm/subdev/timer/nv04 \
            drm/nouveau/nvkm/subdev/timer/nv40 \
            drm/nouveau/nvkm/subdev/timer/nv41 \
            drm/nouveau/nvkm/subdev/top/base \
            drm/nouveau/nvkm/subdev/top/ga100 \
            drm/nouveau/nvkm/subdev/top/gk104 \
            drm/nouveau/nvkm/subdev/vfn/base \
            drm/nouveau/nvkm/subdev/vfn/ga100 \
            drm/nouveau/nvkm/subdev/vfn/gv100 \
            drm/nouveau/nvkm/subdev/vfn/r535 \
            drm/nouveau/nvkm/subdev/vfn/tu102 \
            drm/nouveau/nvkm/subdev/vfn/uvfn \
            drm/nouveau/nvkm/subdev/volt/base \
            drm/nouveau/nvkm/subdev/volt/gf100 \
            drm/nouveau/nvkm/subdev/volt/gf117 \
            drm/nouveau/nvkm/subdev/volt/gk104 \
            drm/nouveau/nvkm/subdev/volt/gk20a \
            drm/nouveau/nvkm/subdev/volt/gm20b \
            drm/nouveau/nvkm/subdev/volt/gpio \
            drm/nouveau/nvkm/subdev/volt/nv40 \

