#!/usr/bin/env python3
# Copyright (C) 2026, The AROS Development Team. All rights reserved.
# Author: Fabian Schmieder
"""Generate m68kemu_shadow_layouts.h from compiler-produced offset files.

Usage: gen_shadow_layouts.py m68k.txt aros.txt > m68kemu_shadow_layouts.h

Input lines:  OFF|Struct|field|offset|size|   SIZ|Struct|size|
"""
import sys

def parse(path):
    structs = {}
    sizes = {}
    for line in open(path):
        line = line.strip().rstrip('|')
        parts = line.split('|')
        if parts[0] == 'OFF':
            _, sname, fname, off, sz = parts
            structs.setdefault(sname, []).append((fname, int(off), int(sz)))
        elif parts[0] == 'SIZ':
            _, sname, sz = parts
            sizes[sname] = int(sz)
    return structs, sizes

def sf_type(fname, m_sz, a_sz):
    if m_sz == 1: return "SF_BYTE"
    if m_sz == 2: return "SF_WORD"
    if m_sz == 4 and a_sz == 8: return "SF_PTR"
    if m_sz == 4: return "SF_LONG"
    return None

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} m68k.txt aros.txt", file=sys.stderr)
        sys.exit(1)

    m68k_structs, m68k_sizes = parse(sys.argv[1])
    aros_structs, aros_sizes = parse(sys.argv[2])

    print("/* AUTO-GENERATED by gen_shadow_layouts.py — do not edit */")
    print("#ifndef M68KEMU_SHADOW_LAYOUTS_H")
    print("#define M68KEMU_SHADOW_LAYOUTS_H\n")

    emitted = []
    shadow_type = 20  # start numbering after manual types (0-19 reserved)

    for sname in sorted(m68k_structs.keys()):
        if sname not in aros_structs:
            continue
        a_map = {f: (o, s) for f, o, s in aros_structs[sname]}
        entries = []
        for fname, m_off, m_sz in m68k_structs[sname]:
            if fname not in a_map:
                continue
            a_off, a_sz = a_map[fname]
            ft = sf_type(fname, m_sz, a_sz)
            if ft is None:
                continue
            entries.append((m_off, a_off, ft, fname))
        if not entries:
            continue

        print(f"/* {sname}: m68k={m68k_sizes.get(sname,'?')}B, "
              f"aros={aros_sizes.get(sname,'?')}B, {len(entries)} fields */")
        print(f"static const struct M68KFieldMap shadow_fields_{sname}[] = {{")
        for m_off, a_off, ft, fname in entries:
            print(f"    {{ {m_off:4d}, {a_off:4d}, {ft:8s}, 0, 0, NULL }},  /* {fname} */")
        print(f"    {{    0,    0, SF_END  , 0, 0, NULL }}")
        print(f"}};\n")

        emitted.append((sname, shadow_type, m68k_sizes.get(sname, 0)))
        shadow_type += 1

    # Lookup table
    print("/* Lookup table: find layout by struct name */")
    print("static const struct M68KStructLayout shadow_gen_layouts[] = {")
    for sname, stype, m68k_sz in emitted:
        print(f"    {{ \"{sname}\", {m68k_sz}, {stype}, shadow_fields_{sname} }},")
    print(f"    {{ NULL, 0, 0, NULL }}")
    print(f"}};\n")
    print(f"#define SHADOW_GEN_LAYOUT_COUNT {len(emitted)}")

    print("\n#endif /* M68KEMU_SHADOW_LAYOUTS_H */")

if __name__ == '__main__':
    main()
