##begin config
version 1.0
libbase M68KEmuBase
libbasetype struct M68KEmuLibBase
options noexpunge
##end config
##begin cdef
#include <dos/bptr.h>
##end cdef
##begin cdefprivate
#include "m68kemu_intern.h"
##end cdefprivate
##begin functionlist
LONG RunHunk(BPTR segList, ULONG stackSize, CONST_STRPTR argPtr, ULONG argSize) (D1, D2, D3, D4)
LONG RunFile(CONST_STRPTR fileName, ULONG stackSize, CONST_STRPTR argPtr, ULONG argSize) (D1, D2, D3, D4)
##end functionlist
