/*
    Copyright (C) 2026, The AROS Development Team. All rights reserved.
    Author: Fabian Schmieder
*/
/*
    Copyright (C) 2026, The AROS Development Team. All rights reserved.
    Author: Fabian Schmieder

    m68kemu.library — thunk dispatch table
*/

#ifndef M68KEMU_THUNKS_H
#define M68KEMU_THUNKS_H

#include <exec/types.h>

struct M68KEmuContext;

#ifdef __cplusplus
extern "C" {
#endif

/* Moira register access wrappers (defined in m68kemu_moira.cpp) */
ULONG M68KEmu_GetD(void *cpu, int n);
ULONG M68KEmu_GetA(void *cpu, int n);
void  M68KEmu_SetD(void *cpu, int n, ULONG val);
void  M68KEmu_SetA(void *cpu, int n, ULONG val);
UWORD M68KEmu_GetSR(void *cpu);
void  M68KEmu_SetSR(void *cpu, UWORD val);
void  M68KEmu_SetPC(void *cpu, ULONG val);

struct M68KThunkEntry
{
    ULONG lvo;
    IPTR (*thunk)(struct M68KEmuContext *ctx, void *cpu);
};

/* Convenience macros for thunk implementations */
#define THUNK_D(n)       M68KEmu_GetD(cpu, n)
#define THUNK_A(n)       M68KEmu_GetA(cpu, n)
#define THUNK_PTR(n)     m68k_to_host_or_shadow(ctx, M68KEmu_GetA(cpu, n))
#define THUNK_DPTR(n)    m68k_to_host_or_shadow(ctx, M68KEmu_GetD(cpu, n))
#define THUNK_SET_D(n,v) M68KEmu_SetD(cpu, n, v)
#define THUNK_SET_A(n,v) M68KEmu_SetA(cpu, n, v)

/* Per-library thunk tables (generated by m68kthunkgen) */
extern const struct M68KThunkEntry m68kemu_thunks_exec[];
extern const ULONG m68kemu_thunks_exec_count;
extern const struct M68KThunkEntry m68kemu_thunks_dos[];
extern const ULONG m68kemu_thunks_dos_count;

struct M68KLibThunkSet {
    const char *name;
    const struct M68KThunkEntry *thunks;
    ULONG count;
};

extern const struct M68KLibThunkSet m68kemu_all_gen_libs[];
extern const ULONG m68kemu_all_gen_libs_count;

extern const struct M68KThunkEntry m68kemu_thunks_exec_gen[];
extern const ULONG m68kemu_thunks_exec_gen_count;
extern const struct M68KThunkEntry m68kemu_thunks_dos_gen[];
extern const ULONG m68kemu_thunks_dos_gen_count;

#ifdef __cplusplus
}
#endif

#endif /* M68KEMU_THUNKS_H */
