##begin config
basename Palette
version 44.1
classid "palette.gadget"
superclass GADGETCLASS
classdatatype struct PaletteGadData
libbasetype struct PaletteBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/palette.h>
##end cdef
##begin cdefprivate
#include "palette_intern.h"
##end cdefprivate
##begin functionlist
Class *PALETTE_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
