##begin config
basename PaletteGad
version 44.1
classid "palette.gadget"
superclass GADGETCLASS
classdatatype struct PaletteGadData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/palette.h>
##end cdef
##begin cdefprivate
#include "palette_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
##end methodlist
