##begin config
basename Button
version 44.1
classid "button.gadget"
superclass FRBUTTONCLASS
classdatatype struct ButtonData
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/button.h>
##end cdef
##begin cdefprivate
#include "button_intern.h"
##end cdefprivate
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
GM_GOINACTIVE
GM_DOMAIN
##end methodlist
