##begin config
version 0.1
residentpri 80
libbase RP1Base
libbasetype struct RP1Base
##end config
##begin cdef
#include <exec/types.h>
##end cdef
##begin cdefprivate
#include "rp1.h"
##end cdefprivate
