##begin config
version 0.1
residentpri 70
libbase RP1USBBase
libbasetype struct RP1USBBase
##end config
##begin cdef
#include <exec/types.h>
##end cdef
##begin cdefprivate
#include <exec/libraries.h>
struct RP1USBBase {
    struct Library  lib;
    IPTR            usb0_base;
    IPTR            usb1_base;
    BOOL            present;
};
##end cdefprivate
