##begin config
version 2.3
libbase ProcessorBase
libbasetype struct ProcessorBase
residentpri 99
##end config
##begin cdef

#include <utility/tagitem.h>
#include <resources/processor.h>

##end cdef
##begin cdefprivate
#include "processor_intern.h"
##end cdefprivate

##begin functionlist
VOID GetCPUInfo(struct TagItem * tagList) (A0)
const struct ProcessorTopology *GetCPUTopology() ()
BOOL GetCoreInfo(ULONG coreNo, struct TagItem * tagList) (D0, A0)
##end functionlist
