##begin config
version 1.0
libbase BtClsBase
libbasetype struct Library
residentpri 48
##end config

##begin cdef
#include <exec/types.h>
#include <exec/lists.h>
#include <exec/semaphores.h>
#include <exec/devices.h>
#include <exec/io.h>
#include <exec/ports.h>
#include <utility/utility.h>
#include <devices/timer.h>
#include <libraries/bluetooth.h>
#include <libraries/btclass.h>
##end cdef

##begin functionlist
LONG btcGetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
LONG btcSetAttrsA(ULONG type, APTR btstruct, struct TagItem *taglist) (D0,A0,A1)
SIPTR btcDoMethodA(ULONG methodid, IPTR *methoddata) (D0,A1)
##end functionlist
