#ifndef VG_MANGLE_H
#define VG_MANGLE_H
#define vgGetError mvgGetError
#define vgFlush mvgFlush
#define vgFinish mvgFinish
#define vgSetf mvgSetf
#define vgSeti mvgSeti
#define vgSetfv mvgSetfv
#define vgSetiv mvgSetiv
#define vgGetf mvgGetf
#define vgGeti mvgGeti
#define vgGetVectorSize mvgGetVectorSize
#define vgGetfv mvgGetfv
#define vgGetiv mvgGetiv
#define vgSetParameterf mvgSetParameterf
#define vgSetParameteri mvgSetParameteri
#define vgSetParameterfv mvgSetParameterfv
#define vgSetParameteriv mvgSetParameteriv
#define vgGetParameterf mvgGetParameterf
#define vgGetParameteri mvgGetParameteri
#define vgGetParameterVectorSize mvgGetParameterVectorSize
#define vgGetParameterfv mvgGetParameterfv
#define vgGetParameteriv mvgGetParameteriv
#define vgLoadIdentity mvgLoadIdentity
#define vgLoadMatrix mvgLoadMatrix
#define vgGetMatrix mvgGetMatrix
#define vgMultMatrix mvgMultMatrix
#define vgTranslate mvgTranslate
#define vgScale mvgScale
#define vgShear mvgShear
#define vgRotate mvgRotate
#define vgMask mvgMask
#define vgRenderToMask mvgRenderToMask
#define vgCreateMaskLayer mvgCreateMaskLayer
#define vgDestroyMaskLayer mvgDestroyMaskLayer
#define vgFillMaskLayer mvgFillMaskLayer
#define vgCopyMask mvgCopyMask
#define vgClear mvgClear
#define vgCreatePath mvgCreatePath
#define vgClearPath mvgClearPath
#define vgDestroyPath mvgDestroyPath
#define vgRemovePathCapabilities mvgRemovePathCapabilities
#define vgGetPathCapabilities mvgGetPathCapabilities
#define vgAppendPath mvgAppendPath
#define vgAppendPathData mvgAppendPathData
#define vgModifyPathCoords mvgModifyPathCoords
#define vgTransformPath mvgTransformPath
#define vgInterpolatePath mvgInterpolatePath
#define vgPathLength mvgPathLength
#define vgPointAlongPath mvgPointAlongPath
#define vgPathBounds mvgPathBounds
#define vgPathTransformedBounds mvgPathTransformedBounds
#define vgDrawPath mvgDrawPath
#define vgCreatePaint mvgCreatePaint
#define vgDestroyPaint mvgDestroyPaint
#define vgSetPaint mvgSetPaint
#define vgGetPaint mvgGetPaint
#define vgSetColor mvgSetColor
#define vgGetColor mvgGetColor
#define vgPaintPattern mvgPaintPattern
#define vgCreateImage mvgCreateImage
#define vgDestroyImage mvgDestroyImage
#define vgClearImage mvgClearImage
#define vgImageSubData mvgImageSubData
#define vgGetImageSubData mvgGetImageSubData
#define vgChildImage mvgChildImage
#define vgGetParent mvgGetParent
#define vgCopyImage mvgCopyImage
#define vgDrawImage mvgDrawImage
#define vgSetPixels mvgSetPixels
#define vgWritePixels mvgWritePixels
#define vgGetPixels mvgGetPixels
#define vgReadPixels mvgReadPixels
#define vgCopyPixels mvgCopyPixels
#define vgCreateFont mvgCreateFont
#define vgDestroyFont mvgDestroyFont
#define vgSetGlyphToPath mvgSetGlyphToPath
#define vgSetGlyphToImage mvgSetGlyphToImage
#define vgClearGlyph mvgClearGlyph
#define vgDrawGlyph mvgDrawGlyph
#define vgDrawGlyphs mvgDrawGlyphs
#define vgColorMatrix mvgColorMatrix
#define vgConvolve mvgConvolve
#define vgSeparableConvolve mvgSeparableConvolve
#define vgGaussianBlur mvgGaussianBlur
#define vgLookup mvgLookup
#define vgLookupSingle mvgLookupSingle
#define vgHardwareQuery mvgHardwareQuery
#define vgGetString mvgGetString
#define vguLine mvguLine
#define vguPolygon mvguPolygon
#define vguRect mvguRect
#define vguRoundRect mvguRoundRect
#define vguEllipse mvguEllipse
#define vguArc mvguArc
#define vguComputeWarpQuadToSquare mvguComputeWarpQuadToSquare
#define vguComputeWarpSquareToQuad mvguComputeWarpSquareToQuad
#endif
