##begin config
basename CheckBox
version 44.1
classid "checkbox.gadget"
superclass GADGETCLASS
classdatatype struct CheckboxData
libbasetype struct CheckBoxBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/checkbox.h>
##end cdef
##begin cdefprivate
#include "checkbox_intern.h"
##end cdefprivate
##begin functionlist
Class *CHECKBOX_GetClass() ()
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
##end methodlist
