##begin config
basename cd32mpeg
version  40.22
libbasetype struct CD32MPEGBase
residentpri 4
beginio_func BeginIO
abortio_func AbortIO
options noexpunge
##end config

##begin cdefprivate
#include "cd32mpeg_intern.h"
##end cdefprivate

##begin cdef
#include <exec/devices.h>
#include <exec/io.h>
#include <devices/cd32mpeg.h>
##end cdef
