#!/bin/zsh
# Creates amiga-m68k binary packages.

BUILDTARGET=amiga-m68k

source $SP/setup
# The log-name MUST match the name of the package script
setl   $BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating AROS/"$BUILDTARGET" system package..."
PACKAGE=$BASENAME-$BUILDTARGET-system
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2
ISOFILE=aros-$BUILDTARGET.iso

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
export  PATH=$PATH:$CFG_M68K_CROSSTOOLS
execute ./configure --target=$BUILDTARGET --enable-ccache --enable-build-type=nightly --with-serial-debug
make
make    bootdisk
make    bootiso

cd      $BUILD_BASE/AROS/bin/amiga-m68k
move    AROS $PACKAGE

delete  $BUILD_BASE/AROS/distfiles/aros-amiga-m68k.elf
delete  $BUILD_BASE/AROS/distfiles/aros-amiga-m68k-reloc.elf

copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
copy    $BUILD_BASE/AROS/distfiles/ $PACKAGE
delete  $PACKAGE/distfiles/$ISOFILE

#archive $ARCHIVE $PACKAGE
move    $PACKAGE AROS

printi "Creating AROS/"$BUILDTARGET" bootiso package..."
PACKAGE=$BASENAME-$BUILDTARGET-bootiso
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.zip

makedir $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
move    $BUILD_BASE/AROS/distfiles/$ISOFILE $PACKAGE
ziparc  $ARCHIVE $PACKAGE

delete  $PACKAGE

printi "Creating AROS/"$BUILDTARGET" boot package..."
PACKAGE=$BASENAME-$BUILDTARGET-boot
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.lha

move    $BUILD_BASE/AROS/distfiles $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE

lhaarc  $ARCHIVE $PACKAGE

cd      $ROOT
resetl
