#!/bin/zsh
# Creates AROS/pc-x86_64-smp grub2 bootiso binary packages.

CONFIGUREEXTRA=--with-binutils-version=2.25 --with-gcc-version=6.3.0

BUILDTARGET=pc-x86_64
VARIANT=smp
BOOTLOADER=grub2

source $SP/pkg/bootiso $BOOTLOADER no
