#!/bin/zsh
# Creates AROS/pc-x86_64-smp grub2 bootiso binary packages.

CONFIGUREEXTRA="--with-binutils-version=2.32 --with-gcc-version=8.2.0"

BUILDCPU=x86_64
BUILDTARGET=pc-$BUILDCPU
VARIANT=smp
BOOTLOADER=grub2

source $SP/pkg/bootiso $BOOTLOADER no
