#!/bin/zsh
# Generic bootiso binary package generator.

BOOTLOADER=$1

source  $SP/setup

# The log-name MUST match the name of the package script
setl   bootiso-$BOOTLOADER-$BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating AROS/$BUILDTARGET bootiso binary packages (with $BOOTLOADER)..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS
copy    $SOURCE_CONTRIB $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET --enable-ccache --with-bootloader=$BOOTLOADER --enable-build-type=nightly
make

ISOFILE=aros-$BUILDTARGET.iso
PACKAGE=$BASENAME-$BUILDTARGET-boot-iso
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.zip

CONTRIBPACKAGE=$BASENAME-$BUILDTARGET-contrib
CONTRIBARCHIVE=$ARCHIVE_ROOT/$VERSION/Binaries/$CONTRIBPACKAGE.tar.bz2
if [ -f $CONTRIBARCHIVE ]; then
    echo "--- Binary contrib package found, unarchiving..."
    cd      $BUILD_BASE/AROS/bin/$BUILDTARGET/AROS
    execute tar xjf $CONTRIBARCHIVE
    delete  Extras
    move    $CONTRIBPACKAGE Extras
else
    echo "--- Binary contrib package not found, skipping..."
fi

cd      $BUILD_BASE/AROS
make    bootiso
makedir $BUILD_BASE/$PACKAGE
copy    $BUILD_BASE/AROS/distfiles/$ISOFILE $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
ziparc  $ARCHIVE $PACKAGE
delete  $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl

