#!/bin/zsh
# Creates AROS/amiga-m68k contrib package.

BUILDTARGET=amiga-m68k

source  $SP/setup

# The log-name MUST match the name of the package script
setl    contrib-$BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating AROS/$BUILDTARGET contrib binary package..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS
copy    $SOURCE_CONTRIB $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
if [ "$CFG_M68K_CROSSTOOLS" != "" ]; then
    export  PATH=$PATH:$CFG_M68K_CROSSTOOLS
fi
execute ./configure --target=$BUILDTARGET --enable-ccache --enable-build-type=nightly --with-serial-debug $PORTSSOURCESOPT $AROSTOOLCHAININSTALLOPT $AROSTOOLCHAINOPT
make    tools mmake contrib

PACKAGE=$BASENAME-$BUILDTARGET-contrib
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

cd      $BUILD_BASE/AROS/bin/$BUILDTARGET
move    AROS $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl
