#!/bin/zsh
# Creates AROS/pc-i386 contrib package.

BUILDTARGET=pc-i386

source  $SP/setup
# The log-name MUST match the name of the package script
setl    contrib-$BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating AROS contrib binary package..."
PACKAGE=$BASENAME-$BUILDTARGET-contrib
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS    $BUILD_BASE/AROS
copy    $SOURCE_CONTRIB $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET --enable-ccache --enable-build-type=nightly
make    tools mmake contrib

cd      $BUILD_BASE/AROS/bin/$BUILDTARGET/AROS
move    Extras $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl
