#!/bin/zsh
# Generic crosstools package generator.

source  $SP/setup

# The log-name MUST match the name of the package script
setl   crosstools-$BUILDTARGET.log

printi "Creating AROS/$BUILDTARGET crosstools packages..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET --enable-ccache --enable-build-type=nightly $PORTSSOURCESOPT $AROSTOOLCHAININSTALLOPT
make    -j $MAKE_JOBS crosstools

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl

