#!/bin/zsh
# Generic crosstools package generator.

source  $SP/setup

# The log-name MUST match the name of the package script
setl   crosstools-$BUILDTARGET.log

printi "Creating AROS/$BUILDTARGET crosstools packages..."

delete  $BUILD_BASE/AROS-CROSSTOOLS
copy    $SOURCE_AROS $BUILD_BASE/AROS-CROSSTOOLS

CONFIGURE_OPTIONS="--target=$BUILDTARGET $CONFIGUREEXTRA --enable-ccache"
if [[ "$AROSTOOLCHAININSTALLOPT" != "" ]]; then
     CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS $AROSTOOLCHAININSTALLOPT"
fi
CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-build-type=nightly $PORTSSOURCESOPT"

cd      $BUILD_BASE/AROS-CROSSTOOLS
execute ./configure ${=CONFIGURE_OPTIONS}
make    -j $MAKE_JOBS crosstools

cd      $ROOT
delete  $BUILD_BASE/AROS-CROSSTOOLS
resetl

