#!/bin/zsh
# Creates hosted binary packages.

source $SP/setup
setl   hosted.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating hosted binary packages..."

printi "Creating AROS/"$HOST_CPU-$HOST_OS" system package..."
PACKAGE=$BASENAME-$HOST_CPU-$HOST_OS-system
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS      $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
execute ./configure --enable-build-type=nightly
make
make    default-x11keymaptable

cd      $BUILD_BASE/AROS/bin/$HOST_OS-$HOST_CPU
move    AROS $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl
