#!/bin/zsh
# Creates linux-armhf "hosted" binary packages.

BUILDTARGET=linux-armhf
BUILDTARGETDIR=linux-arm
BUILDEXTRAOPTS=(--enable-includes=/usr/arm-linux-gnueabihf/include/ --x-includes=/usr/arm-linux-gnueabihf/sysroot/usr/include --x-libraries=/usr/arm-linux-gnueabihf/sysroot/usr/lib)

source $SP/pkg/hosted
