#!/bin/zsh
# Creates hosted binary packages.

source $SP/setup
setl   hosted.log

printi "Creating hosted binary packages..."

printi "Creating AROS/"$HOST_CPU-$HOST_OS" system package..."
PACKAGE=$BASENAME-$HOST_CPU-$HOST_OS-system
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS      $BUILD_BASE/AROS
copy    $SOURCE_NECESSARY $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
execute ./configure --enable-build-type=nightly
make
make    default-x11keymaptable

cd      $BUILD_BASE/AROS/bin/$HOST_OS-$HOST_CPU
move    AROS $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS

if [[ $CFG_CONTRIB_TYPE == "hosted" ]]; then
    printi "Creating AROS/"$HOST_CPU"-all contrib package..."
    PACKAGE=$BASENAME-$HOST_CPU-all-contrib
    ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2
    
    copy    $SOURCE_AROS    $BUILD_BASE/AROS
    copy    $SOURCE_CONTRIB $BUILD_BASE/Contrib
    
    cd      $BUILD_BASE/AROS
    execute ./configure --enable-build-type=nightly
    make
    
    cd      $BUILD_BASE/AROS/bin/$HOST_OS-$HOST_CPU/AROS
    move    contrib $PACKAGE
    archive $ARCHIVE $PACKAGE
    
    cd      $ROOT
    delete  $BUILD_BASE/AROS
fi

cd      $ROOT
resetl

