#!/bin/zsh
# Creates AROS/i386-pc binary packages.

source $SP/setup
setl   i386-pc.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries

printi "Creating AROS/i386-pc binary packages..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS
copy    $SOURCE_NECESSARY $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
execute ./configure --target=pc-i386 --enable-build-type=nightly
make

PACKAGE=$BASENAME-i386-pc-boot-floppy
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

make    bootdisk-pc-i386
makedir $BUILD_BASE/$PACKAGE
copy    $BUILD_BASE/AROS/bin/pc-i386/gen/rom/boot/aros.bin $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE
delete  $PACKAGE

PACKAGE=$BASENAME-i386-pc-boot-iso
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

CONTRIB_ARCHIVE=$ARCHIVE_ROOT/$VERSION/Binaries/AROS-$VERSION-i386-all-contrib.tar.bz2
if [ -f $ARCHIVE_ROOT/$VERSION/Binaries/AROS-$VERSION-i386-all-contrib.tar.bz2 ]; then
    echo "--- Binary contrib package found, unarchiving..."
    cd      $BUILD_BASE/AROS/bin/pc-i386/AROS
    execute tar xjf $CONTRIB_ARCHIVE
    delete  Contrib
    move    AROS-$VERSION-i386-all-contrib Contrib
else
    echo "--- Binary contrib package not found, skipping..."
fi

cd      $BUILD_BASE/AROS
make    bootiso-pc-i386
makedir $BUILD_BASE/$PACKAGE
copy    $BUILD_BASE/AROS/bin/pc-i386/gen/rom/boot/aros.iso $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE
delete  $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl
