#!/bin/zsh
# Creates AROS/i386-pc binary packages.

source $SP/setup
setl   i386-pc.log

ARCHIVE_BASE=$ARCHIVE_BASE/Binaries
BUILDTARGET=pc-i386

printi "Creating AROS/i386-pc binary packages..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS
copy    $SOURCE_NECESSARY $BUILD_BASE/AROS/contrib

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET --enable-build-type=nightly
make

ISOFILE=aros-$BUILDTARGET.iso
PACKAGE=$BASENAME-i386-pc-boot-iso
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.zip

CONTRIB_ARCHIVE=$ARCHIVE_ROOT/$VERSION/Binaries/AROS-$VERSION-i386-all-contrib.tar.bz2
if [ -f $CONTRIB_ARCHIVE ]; then
    echo "--- Binary contrib package found, unarchiving..."
    cd      $BUILD_BASE/AROS/bin/pc-i386/AROS
    execute tar xjf $CONTRIB_ARCHIVE
    delete  Extras
    move    AROS-$VERSION-i386-all-contrib Extras
else
    echo "--- Binary contrib package not found, skipping..."
fi

cd      $BUILD_BASE/AROS
make    bootiso
makedir $BUILD_BASE/$PACKAGE
copy    $BUILD_BASE/AROS/distfiles/$ISOFILE $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
ziparc  $ARCHIVE $PACKAGE
delete  $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS
resetl

