#!/bin/zsh
# Creates generic SDK package.

source  $SP/setup

# The log-name MUST match the name of the package script
setl   sdk-$BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Development_Tools

printi "Creating AROS/$BUILDTARGET SDK package..."

delete  $BUILD_BASE/AROS
copy    $SOURCE_AROS      $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET --enable-build-type=nightly --enable-debug=symbols --with-optimization="-O2"
make    sdk

PACKAGE=$BASENAME-$BUILDTARGET-sdk
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

if [ -z ${BUILDTARGETDIR+x} ]; then BUILDTARGETDIR=$BUILDTARGET; fi

cd      $BUILD_BASE/AROS/bin/$BUILDTARGETDIR
move    AROS-SDK $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS

cd      $ROOT
resetl

