#!/bin/zsh
# Creates SDK package.

source $SP/setup
setl   sdk.log

ARCHIVE_BASE=$ARCHIVE_BASE/Development_Tools

printi "Creating AROS/"$HOST_CPU" SDK package..."
PACKAGE=$BASENAME-$HOST_CPU-all-sdk
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS      $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
execute ./configure --enable-build-type=nightly --enable-debug=symbols --with-optimization="-O2"
make    sdk

cd      $BUILD_BASE/AROS/bin/$HOST_OS-$HOST_CPU
move    AROS-SDK $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS

cd      $ROOT
resetl

