#!/bin/zsh
# Creates AROS/pc-i386 SDK package.

BUILDTARGET=pc-i386

source $SP/setup
setl   sdk-$BUILDTARGET.log

ARCHIVE_BASE=$ARCHIVE_BASE/Development_Tools

printi "Creating AROS/"$BUILDTARGET" SDK package..."
PACKAGE=$BASENAME-$BUILDTARGET-sdk
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS      $BUILD_BASE/AROS

cd      $BUILD_BASE/AROS
execute ./configure --target=$BUILDTARGET--enable-build-type=nightly --enable-debug=symbols --with-optimization="-O2"
make    sdk

cd      $BUILD_BASE/AROS/bin/$BUILDTARGET
move    AROS-SDK $PACKAGE
archive $ARCHIVE $PACKAGE

cd      $ROOT
delete  $BUILD_BASE/AROS

cd      $ROOT
resetl

