#!/bin/zsh
# Creates source packages.

source $SP/setup
setl   sources.log 

ARCHIVE_BASE=$ARCHIVE_BASE/Sources

printi "Creating source packages..."

printi "Creating AROS source package..."
PACKAGE=$BASENAME-source
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_AROS $BUILD_BASE/$PACKAGE
copy    $SOURCE_NECESSARY $BUILD_BASE/$PACKAGE/contrib
cd      $BUILD_BASE/$PACKAGE
prune   
cd      $BUILD_BASE
archive $ARCHIVE $PACKAGE
cd      $ROOT
delete  $BUILD_BASE/$PACKAGE

printi "Creating contrib source package..."
PACKAGE=$BASENAME-contrib-source
ARCHIVE=$ARCHIVE_BASE/ $PACKAGE.tar.bz2

copy    $SOURCE_CONTRIB $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE/$PACKAGE
prune
cd      $BUILD_BASE
archive $ARCHIVE $PACKAGE
cd      $ROOT
delete  $BUILD_BASE/$PACKAGE

printi "Creating documentation source package..."
PACKAGE=$BASENAME-docs-source
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

copy    $SOURCE_DOCS $BUILD_BASE/$PACKAGE
cd      $BUILD_BASE/$PACKAGE
prune
cd      $BUILD_BASE
archive $ARCHIVE $PACKAGE
cd      $ROOT
delete  $BUILD_BASE/$PACKAGE

cd      $ROOT
resetl

