#!/bin/zsh
# Creates source packages.

source $SP/setup
setl   sources.log 

ARCHIVE_BASE=$ARCHIVE_BASE/Sources

printi "Creating source packages..."
cd      $SOURCE_ROOT

printi "Creating AROS source package..."
PACKAGE=$BASENAME-source
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

move    $SOURCE_AROS $PACKAGE
move    $SOURCE_NECESSARY $PACKAGE/contrib
archive $ARCHIVE $PACKAGE
move    $PACKAGE/contrib $SOURCE_NECESSARY
move    $PACKAGE $SOURCE_AROS

printi "Creating contrib source package..."
PACKAGE=$BASENAME-contrib-source
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

move    $SOURCE_CONTRIB $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE
move    $PACKAGE $SOURCE_CONTRIB

printi "Creating documentation source package..."
PACKAGE=$BASENAME-docs-source
ARCHIVE=$ARCHIVE_BASE/$PACKAGE.tar.bz2

move    $SOURCE_DOCS $PACKAGE
copy    $SOURCE_AROS/LICENSE $PACKAGE
copy    $SOURCE_AROS/ACKNOWLEDGEMENTS $PACKAGE
archive $ARCHIVE $PACKAGE
move    $PACKAGE $SOURCE_DOCS

cd      $ROOT
resetl
