##begin config
basename        VBTHCI
version         45.1
libbasetype     struct VBTHCIBase
beginio_func    BeginIO
abortio_func    AbortIO
##end config

##begin cdefprivate
#include "vbthci_intern.h"
##end cdefprivate
