##begin config
basename ListBrowser
version 44.1
classid "listbrowser.gadget"
superclass GADGETCLASS
classdatatype struct ListBrowserData
libbasetype struct ListBrowserBase_intern
classptr_field rc_Class
##end config
##begin cdef
#include <intuition/gadgetclass.h>
#include <gadgets/listbrowser.h>
##end cdef
##begin cdefprivate
#include "listbrowser_intern.h"
##end cdefprivate
##begin functionlist
Class *LISTBROWSER_GetClass() ()
struct Node *AllocListBrowserNodeA(UWORD columns, struct TagItem *tags) (D0, A0)
void FreeListBrowserNode(struct Node *node) (A0)
void SetListBrowserNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void GetListBrowserNodeAttrsA(struct Node *node, struct TagItem *tags) (A0, A1)
void ListBrowserSelectAll(struct List *list) (A0)
void ShowListBrowserNodeChildren(struct Node *node, WORD depth) (A0, D0)
void HideListBrowserNodeChildren(struct Node *node) (A0)
void ShowAllListBrowserChildren(struct List *list) (A0)
void HideAllListBrowserChildren(struct List *list) (A0)
void FreeListBrowserList(struct List *list) (A0)
struct ColumnInfo *AllocLBColumnInfoA(UWORD columns, struct TagItem *tags) (D0, A0)
LONG SetLBColumnInfoAttrsA(struct ColumnInfo *colinfo, struct TagItem *tags) (A1, A0)
LONG GetLBColumnInfoAttrsA(struct ColumnInfo *colinfo, struct TagItem *tags) (A1, A0)
void FreeLBColumnInfo(struct ColumnInfo *colinfo) (A0)
void ListBrowserClearAll(struct List *list) (A0)
##end functionlist
##begin methodlist
OM_NEW
OM_DISPOSE
OM_SET
.alias OM_UPDATE
OM_GET
GM_RENDER
GM_GOACTIVE
GM_HANDLEINPUT
GM_GOINACTIVE
GM_DOMAIN
##end methodlist
